(import "cas/rsbm.lisp")
(define p 11) (define a (primitive-root 11)) (define t 2) (define msg (list 3 1 4 1 5 9))
(define cw (rsbm-encode msg a t p))
(display a) (newline)
(display (gen-poly a t p)) (newline)
(display cw) (newline)
(display (syndromes cw a t p)) (newline)
(display (rsbm-decode cw a t p)) (newline)
(display (rsbm-decode (rsbm-corrupt cw (list (cons 1 5) (cons 6 8)) p) a t p)) (newline)
(display (rsbm-decode (rsbm-corrupt cw (list (cons 0 1) (cons 4 2) (cons 9 3)) p) a t p)) (newline)
(display (list (rsbm-locator-ok? msg a t p (list (cons 1 5) (cons 6 8))) (rsbm-roundtrip-ok? (list 1 2 3 4 5 6) (primitive-root 13) 3 13 (list (cons 1 5) (cons 6 9) (cons 11 12))))) (newline)
