(import "cas/tower2exphermite.lisp")
(define EXP1 (list 'exp (list 0 1)))
(define t1 (list (list (rat-zero) (rat-one)) (list (rat-one))))
(define A (list (k1-zero) (k1-neg t1)))
(define D (list (k1-one) (k1-iscale -2 (k1-one)) (k1-one)))
(define H (t2e-hermite A D t1 EXP1))
(define g (car H))
(display (h2-zero? (car (cdr H)))) (newline)
(display (h2tr-equal? (t2eh-deriv (car g) (car (cdr g)) t1 EXP1) (list A D))) (newline)
