(import "cas/nullstellensatz.lisp")
(define x (list (cons 1 (list 1))))
(define x-1 (list (cons 1 (list 1)) (cons -1 (list 0))))
(display (nss-decide (list x x-1))) (display " ") (display (nss-verify-refutation (list x x-1))) (newline)
(define xy-1 (list (cons 1 (list 1 1)) (cons -1 (list 0 0))))
(define x2 (list (cons 1 (list 1 0))))
(display (nss-decide (list xy-1 x2))) (display " ") (display (nss-verify-refutation (list xy-1 x2))) (newline)
(define x-5 (list (cons 1 (list 1)) (cons -5 (list 0))))
(display (nss-decide (list x-5))) (display " ") (display (car (nss-certificate (list x-5)))) (newline)
(define circ (list (cons 1 (list 2 0)) (cons 1 (list 0 2)) (cons -1 (list 0 0))))
(define x-2 (list (cons 1 (list 1 0)) (cons -2 (list 0 0))))
(display (nss-decide (list circ x-2))) (newline)
(display (nss-decide (quote ()))) (newline)
