(import "cas/tower2exprde.lisp")
(define EXP1 (list 'exp (list 0 1)))
(define t1   (list (list (rat-zero) (rat-one)) (list (rat-one))))
(define t1sq (k1-mul t1 t1))
(define a1   (k1-add t1 (k1-mul t1sq t1)))
(define b1 (exp-rde a1 1 t1sq EXP1))
(display (tr-equal? (tr-reduce b1) (tr-reduce t1))) (newline)
(define P (list (k1-zero) a1))
(display (t2e-int-rde-verify P t1sq EXP1)) (newline)
