(import "cas/cdcl2.lisp")
(define (pv i j h) (+ (* (- i 1) h) j))
(define (build-php p h) (append (be p h 1) (bn p h 1)))
(define (be p h i) (cond ((> i p) (quote ())) (else (cons (row i h 1) (be p h (+ i 1))))))
(define (row i h j) (cond ((> j h) (quote ())) (else (cons (pv i j h) (row i h (+ j 1))))))
(define (bn p h j) (cond ((> j h) (quote ())) (else (append (pfh p h j 1) (bn p h (+ j 1))))))
(define (pfh p h j i) (cond ((> i p) (quote ())) (else (append (pik p h j i (+ i 1)) (pfh p h j (+ i 1))))))
(define (pik p h j i k) (cond ((> k p) (quote ())) (else (cons (list (- 0 (pv i j h)) (- 0 (pv k j h))) (pik p h j i (+ k 1))))))
(display (cdcl2-solve 2 (list (list 1 2) (list -1 2) (list 1 -2) (list -1 -2)))) (newline)
(display (cdcl2-sat? 3 (list (list 1 2) (list -1 3)))) (newline)
(display (cdcl2-solve 3 (list (list 1) (list -1 2) (list -2 3) (list -3)))) (newline)
(display (cdcl2-solve 6 (build-php 3 2))) (newline)
(display (cdcl2-solve 12 (build-php 4 3))) (newline)
(display (cdcl2-solve 20 (build-php 5 4))) (newline)
(define big (list (list 1 2 3) (list -1 -2) (list -2 -3) (list 4 5) (list -4 6) (list -5 -6) (list 7 8) (list -7 -8) (list 1 -4) (list 3 7)))
(display (cdcl2-sat? 8 big)) (newline)
(display (cdcl2-check-model big (cdcl2-model))) (newline)
