(import "cas/nestalg.lisp")
(define p (list 0 1))
(define w (sf-set (sf-set (sf-zeros 2) 0 (rat-one)) 1 (rat-one)))
(define tp (na-t1prime p 2 w))
(display (sf-equal? (sf-product p 2 tp w) (sf-deriv p 2 w))) (newline)
(display (na-q-eq? p 2 (na-tcoeff p 2 (na-deriv p 2 tp (na-answer-t2 2)) 0) (na-t2prime p 2 tp))) (newline)
(display (na-certify p 2 tp (na-answer-t2 2) (na-integrand p 2 tp))) (newline)
(define E2 (list (na-q-zero 2) (na-q-zero 2) (na-q-one 2)))
(display (na-certify p 2 tp E2 (na-deriv p 2 tp E2))) (newline)
(define p3 (list 0 1))
(define w3 (sf-set (sf-set (sf-zeros 3) 0 (rat-one)) 1 (rat-one)))
(define tp3 (na-t1prime p3 3 w3))
(display (na-certify p3 3 tp3 (na-answer-t2 3) (na-integrand p3 3 tp3))) (newline)
