(import "cas/elliptic3complete.lisp")
(define q3 (rat-from-poly (list 1 0 0 1)))
(define om3 (e3-logderiv q3 (af-make (rat-from-poly (list 0 1)) (rat-one))))
(define r3 (e3c-solve q3 om3))
(display (car r3)) (display " ") (display (e3-certify q3 (car (cdr r3)) om3)) (newline)
(define q5 (rat-from-poly (list 1 0 0 0 0 1)))
(define omhi (e3-logderiv q5 (af-make (rat-from-poly (list -1 0 1)) (rat-one))))
(define rhi (e3c-solve q5 omhi))
(display (car rhi)) (display " ") (display (e3-certify q5 (car (cdr rhi)) omhi)) (newline)
(define q7 (rat-from-poly (list 1 0 0 0 0 0 0 1)))
(define om7 (e3-logderiv q7 (af-make (rat-from-poly (list 0 2 0 1)) (rat-one))))
(define r7 (e3c-solve q7 om7))
(display (car r7)) (display " ") (display (e3-certify q7 (car (cdr r7)) om7)) (newline)
(display (car (e3c-solve q3 (af-make (rat-zero) (rat-make (list 1) (list 1 0 0 1)))))) (newline)
