(import "cas/primint.lisp")
(define (R n d) (rde-rmake n d))
(define Z (R (list 0) (list 1)))
(display (car (cdr (int-prim-poly (list Z (R (list 1) (list 0 1))))))) (newline)
(display (car (cdr (int-prim-poly (list Z (R (list 1) (list 0 0 1))))))) (newline)
(display (int-prim-poly-verify (list Z (R (list 1) (list 0 1))))) (newline)
(display (int-prim-poly-verify (list Z (R (list 1) (list 0 0 1))))) (newline)
(display (int-prim-poly-elementary? (list Z (R (list 1) (list 1 0 1))))) (newline)
(display (int-prim-poly-elementary? (list Z (R (list 1) (list -1 1))))) (newline)
