(import "cas/vanhoeij.lisp")
(define F (list (list 0 -1 -1 -1) (list 1)))
(define br (car (vh-branches F 6)))
(display (vh-correction br 2)) (newline)
(display (vh-correction br 3)) (newline)
(display (vh-correct-level1 F 2 6)) (newline)
(display (vh-correct-level1 F 3 6)) (newline)
(display (vh-certify-correction F (list (list 0 -1) (list 1)) 2 6)) (newline)
(display (vh-correct-level1 F 1 6)) (newline)
(define Fc (list (list 0 0 0 -1) (list) (list 1)))
(display (vh-correct-level1 Fc 2 6)) (newline)
