(import "cas/rischrat.lisp")
(define A1 (list 1)) (define D1 (poly-mul (list 0 0 1) (list -1 1)))
(define r1 (rat-integrate A1 D1))
(display (list (car r1) (ri-cadr r1) (ri-caddr r1) (ri-cadddr r1))) (newline)
(display (list (rat-integrate-complete? A1 D1) (rat-integrate-verify A1 D1))) (newline)
(display (rat-integrate (list 1 2) (list 0 -1 0 1))) (newline)
(display (list (rat-integrate-verify (list 1 2) (list 0 -1 0 1))
               (rat-integrate-verify (list 1) (poly-mul (hm-pow (list -1 1) 2) (list -2 1)))
               (rat-integrate-verify (list 3 1) (poly-mul (list 0 0 1) (list -1 0 1))))) (newline)
(display (list (rat-integrate-complete? (list 2 3 5) (list -1 0 0 0 1))
               (rat-integrate-rational-ok? (list 2 3 5) (list -1 0 0 0 1)))) (newline)
