(import "cas/tower2rt.lisp")
(define EXP1 (list 'exp (list 0 1)))
(define Dth2 (list (list (rat-zero) (rat-one)) (list (rat-one) (rat-one))))
(define A (list (k1-neg Dth2) (k1-mul (k1-from-int 3) Dth2)))
(define D (list (k1-zero) (k1-neg (k1-one)) (k1-one)))
(define res (int-h2-full A D Dth2 EXP1))
(display (car res)) (newline)
(display (car (car (cdr (cdr res))))) (newline)
(display (length (car (cdr (car (cdr (cdr res))))))) (newline)
(display (h2tr-equal? (int-h2-full-deriv res Dth2 EXP1) (list A D))) (newline)
