(import "cas/tower2alg.lisp")
(define EXP1 (list 'exp (list 0 1)))
(define Dth2 (list (list (rat-zero) (rat-one)) (list (rat-one) (rat-one))))
(define A (list Dth2))
(define D (list (k1-one) (k1-zero) (k1-one)))
(define q (h2alg-respoly A D Dth2 EXP1))
(display (poly-deg q)) (newline)
(display (h2alg-irreducible-quadratic? q)) (newline)
(define lead (poly-lead q))
(define ac1 (k1-from-rat (/ (poly-coeff q 1) lead)))
(define ac0 (k1-from-rat (/ (poly-coeff q 0) lead)))
(display (h2alg-verify A D Dth2 EXP1)) (newline)
