(import "cas/inetreflect.lisp")
(define term (quote (lam (x A) x)))
(display (iref-observe-head term)) (newline)
(display (iref-is-compound? term)) (newline)
(display (iref-roundtrip? term)) (newline)
(display (iref-roundtrip? (quote (Pi (x A) (app F x))))) (newline)
(define boxed (itm-box (itm-sort 0)))
(display (iref-necessity-is-code? boxed)) (newline)
(display (equal? (iref-as-code boxed) (quote (box (U 0))))) (newline)
