(import "cas/rischrde2.lisp")
(define d1 (re2-decide (rat-from-poly (list 0 1)) (list 0 1)))
(display d1) (newline)
(display (re2-certify (rat-from-poly (list 0 1)) (list 0 1) (car (cdr d1)))) (newline)
(display (re2-decide (rat-make (list 1) (list 0 1)) (list 0 1))) (newline)
(define d3 (re2-decide (rat-make (list -1 1) (list 0 0 1)) (list 0 1)))
(display d3) (newline)
(display (re2-certify (rat-make (list -1 1) (list 0 0 1)) (list 0 1) (car (cdr d3)))) (newline)
(define d4 (re2-decide (rat-from-poly (list 0 1)) (list 0 0 1)))
(display d4) (newline)
(display (re2-decide (rat-from-poly (list 1)) (list 0 0 1))) (newline)
