(import "cas/cad2d.lisp")
(define circle (list (list -1 0 1) (list) (list 1)))
(display (cad2-decide (quote exists) (cons (quote neg) circle))) (newline)
(display (cad2-decide (quote exists) (cons (quote neg) (list (list 1 0 1) (list) (list 1))))) (newline)
(display (cad2-decide (quote forall) (cons (quote nonneg) (list (list 0 0 1) (list) (list 1))))) (newline)
(display (cad2-decide (quote forall) (cons (quote nonneg) circle))) (newline)
(define parab (list (list 0 -1) (list) (list 1)))
(display (cad2-decide (quote exists) (list (quote and) (cons (quote zero) parab) (cons (quote zero) (list (list -4 1)))))) (newline)
(display (cad2-decide (quote exists) (list (quote and) (cons (quote zero) parab) (cons (quote neg) (list (list 1 1)))))) (newline)
(define hyp (list (list -1) (list 0 1)))
(display (cad2-decide (quote exists) (list (quote and) (cons (quote zero) hyp) (cons (quote pos) (list (list 0 1))) (cons (quote pos) (list (list) (list 1)))))) (newline)
(define circ2 (list (list -2 0 1) (list) (list 1)))
(define linexy (list (list 0 1) (list -1)))
(display (cad2-decide (quote exists) (list (quote and) (cons (quote zero) circ2) (cons (quote zero) linexy)))) (newline)
(define linexy2 (list (list 0 1) (list -1)))
(display (cad2-decide (quote exists) (list (quote and) (cons (quote zero) circle) (cons (quote zero) linexy2)))) (newline)
(define xsq2 (list (list -2 0 1)))
(define y0c (list (list) (list 1)))
(display (cad2-decide (quote exists) (list (quote and) (cons (quote zero) xsq2) (cons (quote zero) y0c)))) (newline)
