(import "cas/rischcrdem.lisp")
(import "cas/rischintn.lisp")
(define t1 (list (list (quote exp) (rat-from-poly (list 0 1)))))
(define t1log (list (list (quote log) (rat-from-poly (list 0 1)))))
(define t2 (list (list (quote exp) (rat-from-poly (list 0 1))) (list (quote exp) (list (rat-zero) (rat-one)))))
(define cols (list (list (rat-from-poly (list 1)) (rat-from-poly (list 1)) (rat-from-poly (list 0))) (list (rat-from-poly (list 1)) (rat-from-poly (list -1)) (rat-from-poly (list 1))) (list (rat-from-poly (list 1)) (rat-from-poly (list 0)) (rat-from-poly (list -1)))))
(define rhs (list (rat-from-poly (list 6)) (rat-from-poly (list 0)) (rat-from-poly (list -1))))
(display (te-ratsolve t1 1 cols rhs 3)) (newline)
(define f2 (list (te-zero 1) (list (rat-zero) (rat-one))))
(define r (te-crdem-integrate t2 2 f2))
(display (car r)) (newline)
(display (if (equal? (car r) (quote elementary)) (te-crde-certify t2 2 (te-zero 2) f2 (car (cdr r))) (quote na))) (newline)
(define g (list (rat-zero) (rat-zero) (rat-one)))
(define rl (te-crdem-integrate t1log 1 g))
(display (car rl)) (newline)
(display (if (equal? (car rl) (quote elementary)) (te-int-certify t1log 1 g (car (cdr rl))) (quote na))) (newline)
(display (car (te-crdem-integrate t2 2 (list (te-zero 1) (te-one 1))))) (newline)
(display (car (te-crdem-integrate t1 1 (list (rat-zero) (rat-make (list 1) (list 0 1)))))) (newline)
