(import "cas/cplxtuples.lisp")
(display (gr-equal? (gr-mul (gr-make 0 1) (gr-make 0 1)) (gr-make -1 0))) (newline)
(display (cxt-roots-of (list 'complex 0 1))) (newline)
(define g_x2 (list (cons 1 (list 2 0)) (cons 1 (list 0 0))))
(define g_yx (list (cons 1 (list 0 1)) (cons -1 (list 1 0))))
(define tup (cxt-tuple (list 'complex 0 1) (list (list 0 1))))
(display tup) (newline)
(display (cxt-certify (list g_x2 g_yx) tup)) (newline)
(define g_yx2 (list (cons 1 (list 0 1)) (cons -1 (list 2 0))))
(define tup2 (cxt-tuple (list 'complex 0 1) (list (list 0 0 1))))
(display (car (cdr tup2))) (display " ") (display (cxt-certify (list g_x2 g_yx2) tup2)) (newline)
(display (cxt-roots-of (list 'complex 1 1))) (newline)
(display (cxt-roots-of (list 'complex (/ -1 2) (/ 3 4)))) (newline)
(display (cxt-certify (list g_x2 g_yx) (list (gr-make 0 1) (gr-make 1 0)))) (newline)
