(import "cas/rischcoupled.lisp")
(define b (rat-from-poly (list 0 1)))
(display (rc-exp-solve b (list (rat-one) (rat-one)) (list (rat-one)) 4)) (newline)
(define ytest (list (rat-zero) (rat-one)))
(define gtest (rc-add (rc-exp-deriv b ytest) (rc-mul (list (rat-zero) (rat-one)) ytest)))
(define v2 (rc-exp-solve b (list (rat-zero) (rat-one)) gtest 5))
(display (rc-exp-certify b (list (rat-zero) (rat-one)) gtest (car (cdr v2)))) (newline)
(define vlog (rc-int-log-x))
(display vlog) (newline)
(display (rc-log-certify (rat-make (list 1) (list 0 1)) (rat-zero) (list (rat-zero) (rat-one)) (car (cdr vlog)))) (newline)
(define vlog2 (rc-log-solve (rat-make (list 1) (list 0 1)) (rat-zero) (list (rat-zero) (rat-from-poly (list 2)))))
(display (rc-log-certify (rat-make (list 1) (list 0 1)) (rat-zero) (list (rat-zero) (rat-from-poly (list 2))) (car (cdr vlog2)))) (newline)
