(import "cas/pratt.lisp")
(define (all-agree lo hi) (cond ((> lo hi) #t) ((pratt-agrees? lo) (all-agree (+ lo 1) hi)) (else #f)))
(display (list (pratt-prime? 7) (pratt-prime? 1009) (pratt-prime? 9973) (pratt-prime? 104729))) (newline)
(display (list (pratt-prime? 9) (pratt-prime? 121) (pratt-prime? 561) (pratt-prime? 1000))) (newline)
(display (list (witness-of 7) (witness-of 13) (witness-of 1009))) (newline)
(display (list (cert-size (pratt 7)) (cert-size (pratt 1009)) (cert-size (pratt 9973)))) (newline)
(display (all-agree 2 150)) (newline)
(display (pratt 1009)) (newline)
(define good (pratt 1009))
(display (list (pratt-check good) (pratt-check (list 1009 3 (car (cdr (cdr good))))))) (newline)
