(import "cas/puiseuxr.lisp")
(define Fn (list (list 0 0 -1 -1) (list) (list 1)))
(display (pr-branch-leads Fn 2)) (newline)
(define F3 (list (list 0 0 0 -6) (list 0 0 11) (list 0 -6) (list 1)))
(display (pr-branch-leads F3 2)) (newline)
(define F (list (list 0 0 0 0 1 1) (list 0 0 -2 -1) (list 1)))
(display (pr-deflate (pr-subst F 1 2)) ) (newline)
(display (pr-branch-leads F 3)) (newline)
(display (pr-roots-mult (list 1 -2 1) 4)) (newline)
