(import "cas/algresq.lisp")
(define r1 (algresq-integrate 0 1 0 -2))
(display r1) (newline)
(display (algresq-certify 0 1 0 -2 r1)) (newline)
(display (algresq-certify 1 0 0 -2 (algresq-integrate 1 0 0 -2))) (newline)
(display (algresq-certify 1 1 0 -2 (algresq-integrate 1 1 0 -2))) (newline)
(display (algresq-certify 2 3 0 -3 (algresq-integrate 2 3 0 -3))) (newline)
(display (algresq-certify 0 1 1 -1 (algresq-integrate 0 1 1 -1))) (newline)
(display (car (algresq-integrate 0 1 0 -4))) (newline)
(display (car (algresq-integrate 0 1 0 1))) (newline)
