(import "cas/ntrisch.lisp")
(define t1 (nt-monomial 1 (rat-one) 1))
(define s1 (list (list (quote exp) (rat-one))))
(define s2 (list (list (quote exp) (rat-one)) (list (quote exp) t1)))
(define s3 (list (list (quote exp) (rat-one)) (list (quote exp) t1) (list (quote exp) (nt-monomial 2 (nt-lift 1 (rat-one)) 1))))
(define sLOG (list (list (quote prim) (rat-make (list 1) (list 0 1)))))
(display (nt-integrate-verify 0 (quote ()) (rat-from-poly (list 0 2)))) (display " ")
(display (nt-integrate-verify 1 s1 (nt-monomial 1 (rat-from-poly (list 0 2)) 1))) (newline)
(display (nt-integrate-verify 2 s2 (nt-monomial 2 t1 1))) (display " ")
(display (car (nt-integrate 2 s2 (nt-monomial 2 (nt-lift 1 (rat-one)) 1)))) (newline)
(display (nt-integrate-verify 3 s3 (nt-monomial 3 (nt-monomial 2 (nt-lift 1 (rat-one)) 1) 1))) (display " ")
(display (car (nt-integrate 3 s3 (nt-monomial 3 (nt-lift 2 (rat-one)) 1)))) (newline)
(display (nt-integrate-verify 1 sLOG (nt-monomial 1 (rat-one) 1))) (display " ")
(display (nt-integrate-verify 1 sLOG (nt-monomial 1 (rat-one) 3))) (newline)
