(import "cas/intbasis.lisp")
(define D1 (list 0 0 1 1))
(display (car (cdr (ib-quadratic D1)))) (display " ") (display (ib-quadratic-certify D1)) (newline)
(define D2 (list 0 0 0 1))
(display (car (cdr (ib-quadratic D2)))) (display " ") (display (ib-quadratic-certify D2)) (newline)
(define D4 (list 0 0 0 0 1 1))
(display (car (cdr (ib-quadratic D4)))) (display " ") (display (ib-quadratic-certify D4)) (newline)
(define D3 (list 1 0 0 1))
(display (ib-quadratic-extends? D3)) (newline)
(define F (list (list 0 0 -1 -1) (list) (list 1)))
(define br (pg-branches F 6))
(define Ny (list (list 0) (list 1)))
(display (ib-integral-at0? Ny 1 br 6)) (display " ") (display (ib-integral-at0? Ny 2 br 6)) (newline)
