(import "cas/tower2expff.lisp")
(define MEXP (list 'exp (list 0 1)))
(define TH1 (list (list (rat-zero) (rat-one)) (list (rat-one))))
(define UP TH1)
(define w1 (list (k1-neg TH1) (k1-one)))
(define w2 (list (k1-neg (k1-iscale 2 TH1)) (k1-one)))
(define w3 (list TH1 (k1-one)))
(define D (h2-mul (h2-mul w1 w2) w3))
(define A (h2-add (h2-add (h2-cscale (k1-from-int 1) (h2-mul (t2e-deriv w1 UP MEXP) (h2-mul w2 w3)))
                          (h2-cscale (k1-from-int 2) (h2-mul (t2e-deriv w2 UP MEXP) (h2-mul w1 w3))))
                  (h2-cscale (k1-from-int 3) (h2-mul (t2e-deriv w3 UP MEXP) (h2-mul w1 w2)))))
(define lg (h2rt-logpart-exp-ff A D UP MEXP))
(display (car lg)) (newline)
(display (map car (car (cdr lg)))) (newline)
(display (h2tr-equal? (h2rt-logderiv-exp (car (cdr lg)) UP MEXP (h2tr-zero)) (list A D))) (newline)
