(import "cas/cadqenx.lisp")
(import "cas/cadqemin.lisp")
(define (cadr l) (car (cdr l))) (define (caddr l) (car (cdr (cdr l))))
(define (mem x s) (cond ((null? s) #f) ((equal? x (car s)) #t) (else (mem x (cdr s)))))
(display (cadqenx-rat-roots (list 1 -4))) (newline)
(display (null? (cadqenx-rat-roots (list -2 0 1)))) (newline)
(define genq (list (list (cons 1 (list 0 0 1))) (list (cons 1 (list 0 1 0))) (list (cons 1 (list 1 0 0)))))
(define factors (list (list (list 1 1 0 0)) (list (list 1 0 1 0)) (list (list 1 0 0 1)) (list (list 1 0 2 0) (list -4 1 0 1))))
(define tf (cadqenx-elim2 factors 3 (quote exists) (cons (quote zero) genq)))
(display (mem (list 1 1 1 0) (cadr tf))) (newline)
(display (mem (list 1 -1 1 0) (cadr tf))) (newline)
(display (length (cadqemin-cover (cadr tf) (caddr tf)))) (newline)
