(import "cas/mfactor.lisp")
(define x+y (list (list 0 1) (list 1)))
(define x-y (list (list 0 -1) (list 1)))
(define x+1 (list (list 1) (list 1)))
(define x-1 (list (list -1) (list 1)))
(define x2+y (list (list 0 1) (list) (list 1)))
(display (factor-bivariate->string (factor-bivariate (xy-mul x+y x-y)))) (newline)
(display (factor-bivariate->string (factor-bivariate (xy-mul x+1 x-1)))) (newline)
(display (factor-bivariate->string (factor-bivariate (xy-mul x+1 x2+y)))) (newline)
(display (factor-bivariate->string (factor-bivariate (xy-mul (xy-mul x+y x+y) x-1)))) (newline)
(display (factor-ok? (xy-mul (xy-mul x+y x-y) x+1) (factor-bivariate (xy-mul (xy-mul x+y x-y) x+1)))) (newline)
