(import "cas/tower2sub.lisp")
(define MEXP (list 'exp (list 0 1)))
(define TH1 (list (list (rat-zero) (rat-one)) (list (rat-one))))
(define EDth2 (list (k1-zero) TH1))
(define EA1 (list (k1-zero) TH1))
(define ED1 (list (k1-from-int 1) (k1-from-int 0) (k1-from-int 1)))
(display (int-h2-sub-elementary? EA1 ED1 EDth2 MEXP)) (newline)
(display (int-h2-sub-verify EA1 ED1 EDth2 MEXP)) (newline)
(define ED2 (list (k1-from-int -1) (k1-from-int 1)))
(display (int-h2-sub-verify EA1 ED2 EDth2 MEXP)) (newline)
