(import "cas/intbasis.lisp")
(define g (list 0 0 0 0 1 -2 1))
(define F (list (poly-neg g) (list) (list) (list 1)))
(display (ib-sing-places-superelliptic g 6)) (newline)
(define gb (ib-global-basis-superelliptic F g 3 4))
(display (ib-nth gb 0)) (display " ") (display (ib-nth gb 1)) (display " ") (display (ib-nth gb 2)) (newline)
(define D2 (list 0 0 1 -1 -1 1))
(define Fq (list (poly-neg D2) (list) (list 1)))
(display (ib-global-basis-superelliptic Fq D2 3 4)) (newline)
