(import "cas/hyperpell.lisp")
(define f (list 1 0 0 0 0 0 1))
(define h (list 0 0 0 1))
(display (hp-is-unit-curve? f h 1)) (display " ") (display (hp-unit-norm h 1)) (newline)
(display (hp-unit-power f h 2)) (newline)
(display (hp-B-nonconstant? f h 2)) (display " ") (display (hp-certify f h 1 2)) (display " ") (display (hp-log-cert f h 2)) (newline)
(display (hp-B-nonconstant? f h 3)) (display " ") (display (hp-certify f h 1 3)) (display " ") (display (hp-log-cert f h 3)) (newline)
(display (hp-is-unit-curve? (list 1 0 0 0 0 1) h 1)) (newline)
(define h2 (list 0 1 0 1))
(define f2 (poly-add (poly-mul h2 h2) (list 2)))
(display (hp-is-unit-curve? f2 h2 2)) (display " ") (display (hp-certify f2 h2 2 2)) (display " ") (display (hp-log-cert f2 h2 2)) (newline)
