(import "cas/tower2primfull.lisp")
(define EXP1 (list 'exp (list 0 1)))
(define Dth2 (list (list (rat-zero) (rat-one)) (list (rat-one) (rat-one))))
(define A1 (list Dth2))
(define D1 (list (k1-from-int 1) (k1-from-int 0) (k1-from-int 1)))
(display (int-h2-prim-full-elementary? A1 D1 Dth2 EXP1)) (newline)
(display (int-h2-prim-full-verify A1 D1 Dth2 EXP1)) (newline)
(define A2 (list (k1-iscale 1 Dth2) (k1-iscale 1 Dth2) (k1-iscale 1 Dth2)))
(define D2 (list (k1-from-int 0) (k1-from-int 1) (k1-from-int 0) (k1-from-int 1)))
(display (int-h2-prim-full-verify A2 D2 Dth2 EXP1)) (newline)
