(import "cas/cadsecn.lisp")
(define (cn c n) (if (= n 0) c (list (cn c (- n 1)))))
(define p3 (cadsecn-diagonal (list -1 0 3) 0 1 3))
(define sph (list (list (list -1 0 1) (list) (list 1)) (cn 0 2) (cn 1 2)))
(define xy (list (list (list) (list -1)) (cn 1 2)))
(define yz (list (list (list 0 -1) (list 1))))
(define xc (list (list) (list (list 1))))
(display (cadsecn-holds? (cons (quote pos) xc) p3)) (display " ") (display (cadsecn-holds? (cons (quote zero) sph) p3)) (display " ") (display (cadsecn-holds? (cons (quote zero) xy) p3)) (newline)
(display (cadsecn-holds? (cons (quote neg) (list (list (list -2 1) (list 1)) (cn 1 2))) p3)) (newline)
(display (cadsecn-decide-conj (list (cons (quote zero) sph) (cons (quote zero) xy) (cons (quote zero) yz) (cons (quote pos) xc)) p3)) (newline)
(define p4 (cadsecn-diagonal (list -1 0 4) 0 1 4))
(define s3 (list (list (list -1 0 1) (list) (list 1)) (cn 0 2) (cn 1 2)))
(define ball4 (list s3 (cn 0 3) (cn 1 3)))
(display (cadsecn-holds? (cons (quote zero) ball4) p4)) (display " ") (display (cadsecn-holds? (cons (quote zero) (list (cn (/ -1 2) 3) (cn 1 3))) p4)) (newline)
