(import "cas/cadlift.lisp")
(define yz-ball (list (list -1 0 1) (list) (list 1)))
(define ball (list yz-ball (list (list)) (list (list 1))))
(display (cadlift-decide (quote exists) (cons (quote neg) ball))) (newline)
(define ballp (list (list (list 1 0 1) (list) (list 1)) (list (list)) (list (list 1))))
(display (cadlift-decide (quote exists) (cons (quote neg) ballp))) (newline)
(define sumsq (list (list (list 0 0 1) (list) (list 1)) (list (list)) (list (list 1))))
(display (cadlift-decide (quote forall) (cons (quote nonneg) sumsq))) (newline)
(display (cadlift-decide (quote forall) (cons (quote nonneg) ball))) (newline)
(define xpos (list (list) (list (list 1))))
(define ypos (list (list (list) (list 1))))
(define zpos (list (list (list 0 1))))
(define slab (list (list (list -2 1) (list 1)) (list (list 1))))
(display (cadlift-decide (quote exists) (list (quote and) (cons (quote pos) xpos) (cons (quote pos) ypos) (cons (quote pos) zpos) (cons (quote neg) slab)))) (newline)
(display (cadlift-decide (quote exists) (list (quote and) (cons (quote pos) xpos) (cons (quote neg) xpos)))) (newline)
