(import "cas/itexp.lisp")
(display (ie-mvec (car (ie-Ek-deriv 3 1)))) (newline)
(display (ie-mvec (car (ie-Ek-deriv 3 2)))) (newline)
(display (ie-mvec (car (ie-Ek-deriv 3 3)))) (newline)
(display (ie-certify 2 (ie-top 2) (ie-full-product 2))) (newline)
(display (ie-certify 3 (ie-top 3) (ie-full-product 3))) (newline)
(display (ie-certify 4 (ie-top 4) (ie-full-product 4))) (newline)
(display (ie-certify 5 (ie-top 5) (ie-full-product 5))) (newline)
(display (ie-deriv 3 (ie-full-product 3))) (newline)
(display (ie-certify 3 (ie-top 3) (ie-full-product 2))) (newline)
