(import "cas/tower2rt.lisp")
(define MEXP (list 'exp (list 0 1)))
(define TH1 (list (list (rat-zero) (rat-one)) (list (rat-one))))
(define Dth2 (list (list (rat-zero) (rat-one)) (list (rat-one) (rat-one))))
(define v1 (list (k1-neg TH1) (k1-one)))
(define v3 (list TH1 (k1-one)))
(define D (h2-mul v1 v3))
(define A (h2-add (h2-cscale (k1-from-int 1) (h2-mul (t2-deriv v1 Dth2 MEXP) v3))
                  (h2-cscale (k1-from-int 2) (h2-mul (t2-deriv v3 Dth2 MEXP) v1))))
(define lg (h2rt-logpart A D Dth2 MEXP))
(display (car lg)) (newline)
(display (length (car (cdr lg)))) (newline)
(display (h2tr-equal? (h2rt-logderiv (car (cdr lg)) Dth2 MEXP (h2tr-zero)) (list A D))) (newline)
