(import "cas/realqe.lisp")
(display (qe-decide (quote exists) (cons (quote neg) (list -1 0 1)))) (newline)
(display (qe-decide (quote forall) (cons (quote pos) (list 1 0 1)))) (newline)
(display (qe-decide (quote forall) (cons (quote nonneg) (list -1 0 1)))) (newline)
(display (qe-decide (quote forall) (cons (quote nonneg) (list 0 0 1)))) (newline)
(display (qe-decide (quote exists) (cons (quote zero) (list 1 0 1)))) (newline)
(display (qe-decide (quote exists) (list (quote and) (cons (quote zero) (list 2 -3 1)) (cons (quote zero) (list -1 1))))) (newline)
(display (qe-decide (quote exists) (list (quote and) (cons (quote zero) (list -2 1)) (cons (quote pos) (list 2 -3 1))))) (newline)
(display (qe-decide (quote exists) (list (quote and) (cons (quote zero) (list -3 1)) (cons (quote pos) (list 2 -3 1))))) (newline)
(display (qe-decide (quote forall) (cons (quote pos) (list 1 0 0 0 1)))) (newline)
