(import "cas/elliptic3general.lisp")
(define q (rat-from-poly (list 1 0 1)))
(define g1 (af-make (rat-from-poly (list 1 0 1)) (rat-from-poly (list 0 1))))
(display (e3g-norm q g1)) (newline)
(display (e3g-recognize q g1 (e3g-logderiv q g1))) (display " ") (display (e3g-norm-relation? q g1)) (newline)
(define g2 (af-make (rat-from-poly (list 0 1)) (rat-from-poly (list 0 1))))
(display (e3g-recognize q g2 (e3g-logderiv q g2))) (display " ") (display (e3g-norm-relation? q g2)) (newline)
(define wrong (af-make (rat-from-poly (list 1)) (rat-zero)))
(display (e3g-recognize q g1 wrong)) (newline)
