(import "cas/cadqemin.lisp")
(define factors (list (list (list 1 1 0 0)) (list (list 1 0 1 0)) (list (list 1 0 0 1)) (list (list 1 0 2 0) (list -4 1 0 1))))
(define (law sa sb sc sd) (cond ((not (= sa 0)) (if (= sd 1) #t (= sd 0))) (else (if (not (= sb 0)) #t (= sc 0)))))
(define (all-patterns m) (if (= m 0) (list (quote ())) (pre-each (list 1 0 -1) (all-patterns (- m 1)))))
(define (pre-each sgns rest) (if (null? sgns) (quote ()) (app (pre1 (car sgns) rest) (pre-each (cdr sgns) rest))))
(define (pre1 s rest) (if (null? rest) (quote ()) (cons (cons s (car rest)) (pre1 s (cdr rest)))))
(define (app a b) (if (null? a) b (cons (car a) (app (cdr a) b))))
(define (cadr l) (car (cdr l))) (define (caddr l) (car (cdr (cdr l)))) (define (cadddr l) (car (cdr (cdr (cdr l)))))
(define (split ps ts fs) (cond ((null? ps) (list ts fs)) ((law (car (car ps)) (cadr (car ps)) (caddr (car ps)) (cadddr (car ps))) (split (cdr ps) (cons (car ps) ts) fs)) (else (split (cdr ps) ts (cons (car ps) fs)))))
(define sp (split (all-patterns 4) (quote ()) (quote ())))
(define trues (car sp)) (define falses (cadr sp))
(display (length (cadqemin-cover trues falses))) (newline)
(display (length (cadqemin-cover-exact trues falses))) (newline)
(display (cadqemin-minimize-exact factors trues falses)) (newline)
(display (cadqemin-minimize (list (list (list 1 1))) (list (list 1) (list 0)) (list (list -1)))) (newline)
