(import "cas/rischlaurent.lisp")
(define t1log (list (list (quote log) (rat-from-poly (list 0 1)))))
(define r (laurent-int-x-logx))
(display (car r)) (newline)
(display (rat-equal? (car (cdr (cdr r))) (rat-one))) (newline)
(define r2 (laurent-integrate t1log 1 (list (rat-make (list 1) (list 0 1))) (list (rat-zero) (rat-one))))
(display (te-int-certify t1log 1 (list (rat-zero) (rat-one)) (car (cdr r2)))) (newline)
(display (rat-equal? (car (cdr (cdr r2))) (rat-one))) (newline)
(display (car (laurent-integrate t1log 1 (list (rat-one)) (quote ())))) (newline)
(display (car (laurent-integrate t1log 1 (list (rat-make (list 1) (list 0 1)) (rat-one)) (quote ())))) (newline)
