(import "cas/cadqenr.lisp")
(define (cadr l) (car (cdr l))) (define (caddr l) (car (cdr (cdr l))))
(define (mem x s) (cond ((null? s) #f) ((equal? x (car s)) #t) (else (mem x (cdr s)))))
(display (cadqenr-sign-of (list -1 1) (list -2 0 1) 0 2)) (newline)
(display (cadqenr-sign-of (list -2 1) (list -2 0 1) 0 2)) (newline)
(display (cadqenr-sign-of (list -2 0 1) (list -2 0 1) 0 2)) (newline)
(define xmp (list (list (cons -1 (list 1))) (list (cons 1 (list 0)))))
(define xx2 (list (list (cons -2 (list 0))) (quote ()) (list (cons 1 (list 0)))))
(define phi2 (list (quote and) (cons (quote zero) xmp) (cons (quote zero) xx2)))
(define tf2 (cadqenr-elim2-1 (list (list (list -2 0) (list 1 2))) (quote exists) phi2))
(display (mem (list 0) (cadr tf2))) (newline)
(display (mem (list 1) (caddr tf2))) (newline)
(define xx3 (list (list (cons -2 (list 0))) (quote ()) (quote ()) (list (cons 1 (list 0)))))
(define phi3 (list (quote and) (cons (quote zero) xmp) (cons (quote zero) xx3)))
(display (mem (list 0) (cadr (cadqenr-elim2-1 (list (list (list -2 0) (list 1 3))) (quote exists) phi3)))) (newline)
