(import "cas/sturm.lisp")
(display (num-real-roots (list -2 0 1))) (newline)
(display (num-real-roots (list 1 0 1))) (newline)
(display (num-real-roots (list -6 11 -6 1))) (newline)
(display (num-real-roots (list 2 -3 0 1))) (newline)
(display (num-real-roots (list 0 -1 0 0 0 1))) (newline)
(display (intervals->string (isolate-roots (list -6 11 -6 1)))) (newline)
(display (intervals->string (isolate-roots (list 4 0 -5 0 1)))) (newline)
(display (count-real-roots (list -6 11 -6 1) 1 3)) (newline)
(display (isolation-ok? (list 4 0 -5 0 1) (isolate-roots (list 4 0 -5 0 1)))) (newline)
