(import "cas/special.lisp")
(display (sp-gamma-int 5)) (newline)
(display (sp-gamma-half 3)) (newline)
(display (sp-gamma-func-check 2)) (newline)
(display (sp-erf-coeffs 8)) (newline)
(display (sp-erf-deriv-check 8)) (newline)
(display (sp-besselj 0 7)) (newline)
(display (sp-besselj 1 6)) (newline)
(display (sp-besselj 2 7)) (newline)
(display (sp-bessel-deriv-check 6)) (newline)
(display (sp-bessel-ode-check 7)) (newline)
