(import "cas/cyclotomic.lisp")
(display (cyclotomic->string 1)) (newline)
(display (cyclotomic->string 4)) (newline)
(display (cyclotomic->string 6)) (newline)
(display (cyclotomic->string 12)) (newline)
(display (cyclotomic->string 15)) (newline)
(display (list (poly-deg (cyclotomic 5)) (poly-deg (cyclotomic 15)) (poly-deg (cyclotomic 36)))) (newline)
(define t105 (cyclo-table 105))
(display (list (poly-deg (lookup 105 t105)) (min-coeff-tab 105 t105) (max-coeff-tab 105 t105))) (newline)
(display (cyclotomic-ok-tab? 105 t105)) (newline)
