(import "cas/twosquares.lisp")
(display (two-squares->string 13)) (newline)
(display (two-squares->string 97)) (newline)
(display (two-squares->string 50)) (newline)
(display (two-squares->string 325)) (newline)
(display (two-squares->string 45)) (newline)
(display (two-squares->string 1000033)) (newline)
(display (two-squares 3)) (newline)
(display (list (sum-of-two-squares? 3) (sum-of-two-squares? 21) (sum-of-two-squares? 45) (sum-of-two-squares? 50))) (newline)
(display (list (two-squares-ok? 97) (two-squares-ok? 325) (two-squares-ok? 1000033) (two-squares-ok? 7))) (newline)
