(import "cas/itlog.lisp")
(display (il-mvec (car (il-Lk-deriv 3 1)))) (newline)
(display (il-mvec (car (il-Lk-deriv 3 2)))) (newline)
(display (il-mvec (car (il-Lk-deriv 3 3)))) (newline)
(display (il-certify 2 (il-top 2) (il-int-denom 2))) (newline)
(display (il-certify 3 (il-top 3) (il-int-denom 3))) (newline)
(display (il-certify 4 (il-top 4) (il-int-denom 4))) (newline)
(display (il-certify 5 (il-top 5) (il-int-denom 5))) (newline)
(display (il-certify 3 (il-top 3) (il-int-denom 2))) (newline)
