(import "cas/tower2exprde.lisp")
(define EXP1 (list 'exp (list 0 1)))
(define t1   (list (list (rat-zero) (rat-one)) (list (rat-one))))
(define t1sq (k1-mul t1 t1))
(define t1p  (k1-add t1 t1sq))
(define b (exp-rde t1p 1 t1 EXP1))
(display (tr-equal? (tr-reduce b) (tr-reduce t1))) (newline)
(define P (list (k1-zero) t1p (k1-iscale 6 t1)))
(display (t2e-rde-integrable? P t1 EXP1)) (newline)
(display (t2e-int-rde-verify P t1 EXP1)) (newline)
