(import "cas/inetunivalence.lisp")
(kernel-assume (quote A) (quote (Sort 0)))
(kernel-assume (quote A1) (quote (Sort 0)))
(kernel-assume (quote B) (quote (Sort 0)))
(kernel-assume (quote B1) (quote (Sort 0)))
(kernel-assume (quote PA) (quote (Path (Sort 0) A A1)))
(kernel-assume (quote PB) (quote (Path (Sort 0) B B1)))
(kernel-assume (quote f) (quote (Pi (x A) B)))
(display (iuv-ineg-check (quote (ineg i0)) (quote i1))) (newline)
(display (iuv-ineg-check (quote (ineg (ineg i0))) (quote i0))) (newline)
(display (iuv-transp-pi-check (quote (transp (plam i (Pi (x (papp PA i)) (papp PB i))) f)) (quote (Pi (x A1) B1)))) (newline)
(display (iuv-id-equiv-check (quote (id-equiv A)) (quote (Equiv A A)))) (newline)
(display (iuv-id-equiv-check (quote (ua (id-equiv A))) (quote (Id (Sort 0) A A)))) (newline)
(kernel-assume (quote aa) (quote A))
(display (iuv-hcomp-check (quote (hcomp A aa)) (quote A))) (newline)
(display (iuv-hcomp-reduces? (quote (hcomp A aa)) (quote aa))) (newline)
(kernel-assume (quote uu) (quote A))
(kernel-assume (quote uu2) (quote A))
(display (iuv-hcomp1-check (quote (hcomp1 A (cofib i1 i1) uu uu)) (quote A))) (newline)
(display (iuv-hcomp1-reduces? (quote (hcomp1 A (cofib i0 i1) uu2 uu)) (quote uu))) (newline)
(display (not (iuv-hcomp1-check (quote (hcomp1 A (cofib i1 i1) uu2 uu)) (quote A)))) (newline)
(kernel-assume (quote w0) (quote A))
(kernel-assume (quote w1) (quote A))
(display (iuv-hcomp2-reduces? (quote (hcomp2 A (cofib i0 i1) w1 (cofib i0 i1) w1 w0)) (quote w0))) (newline)
(display (not (iuv-hcomp2-check (quote (hcomp2 A (cofib i1 i1) w1 (cofib i1 i1) w0 w1)) (quote A)))) (newline)
(kernel-assume (quote Tg) (quote (Sort 0)))
(kernel-assume (quote eg) (quote (Equiv Tg A)))
(kernel-assume (quote ag) (quote A))
(display (iuv-glue-check (quote (Glue A (cofib i0 i1) Tg eg)) (quote (Sort 0)))) (newline)
(display (iuv-glue-reduces? (quote (Glue A (cofib i1 i1) Tg eg)) (quote Tg))) (newline)
(display (iuv-glue-reduces? (quote (equiv-fun (id-equiv A))) (quote (lam (x A) x)))) (newline)
(display (iuv-unglue-reduces? (quote (unglue A (cofib i1 i1) A (id-equiv A) ag)) (quote ag))) (newline)
(display (iuv-glue-empty-boundary? (quote (Glue A (cofib i0 i1) Tg eg)) (quote A))) (newline)
(display (iuv-glue-transp-reduces? (quote (transp (plam i (Glue A (cofib i0 i1) Tg eg)) ag)) (quote ag))) (newline)
(kernel-assume (quote Th) (quote (Sort 0)))
(kernel-assume (quote eh) (quote (Equiv Th A)))
(kernel-assume (quote th) (quote Th))
(display (iuv-glue-transp-held? (quote (transp (plam i (Glue A (cofib i1 i1) Th eh)) th)) (quote Th))) (newline)
(display (iuv-glue-transp-held-reduces? (quote (transp (plam i (Glue A (cofib i1 i1) Th eh)) th)) (quote th))) (newline)
(kernel-assume (quote Tk) (quote (Sort 0)))
(kernel-assume (quote ek) (quote (Equiv Tk A)))
(kernel-assume (quote g0k) (quote A))
(display (iuv-equiv-inv-reduces? (quote (equiv-inv (id-equiv A))) (quote (lam (x A) x)))) (newline)
(display (iuv-gtransp-reduces? (quote (gtransp A (cofib i0 i1) A (id-equiv A) g0k)) (quote g0k))) (newline)
(display (not (iuv-gtransp-reduces? (quote (gtransp A (cofib i0 i1) Tk ek g0k)) (quote g0k)))) (newline)
(display (iuv-mk-equiv-check (quote (mk-equiv A A (lam (x A) x) (lam (x A) x) (lam (x A) (refl x)) (lam (y A) (refl y)))) (quote (Equiv A A)))) (newline)
(display (iuv-equiv-proj-reduces? (quote (equiv-fun (mk-equiv A A (lam (x A) x) (lam (x A) x) (lam (x A) (refl x)) (lam (y A) (refl y))))) (quote (lam (x A) x)))) (newline)
(display (iuv-gtransp-reduces? (quote (gtransp A (cofib i0 i1) A (mk-equiv A A (lam (x A) x) (lam (x A) x) (lam (x A) (refl x)) (lam (y A) (refl y))) a)) (quote a))) (newline)
(kernel-assume (quote Te) (quote (Sort 0)))
(kernel-assume (quote ee) (quote (Equiv Te A)))
(kernel-assume (quote g0e) (quote A))
(display (iuv-gtransp-empty-face-reduces? (quote (gtransp A (cofib i0 i1) Te ee g0e)) (quote g0e))) (newline)
(display (not (iuv-gtransp-reduces? (quote (gtransp A (cofib i1 i1) Te ee g0e)) (quote g0e)))) (newline)
(kernel-assume (quote g0h) (quote A))
(display (iuv-gtransp-held-face-reduces? (quote (gtransp A (cofib i1 i1) A (mk-equiv A A (lam (x A) x) (lam (x A) x) (lam (x A) (refl x)) (lam (x A) (refl x))) g0h)) (quote g0h))) (newline)
(kernel-assume (quote Qx) (quote (Sort 0)))
(kernel-assume (quote Qy) (quote (Sort 0)))
(kernel-assume (quote PQx) (quote (Path (Sort 0) Qx Qy)))
(kernel-assume (quote ppx) (quote A))
(kernel-assume (quote qqx) (quote Qx))
(display (iuv-transp-glue-line-reduces? (quote (transp (plam i (Glue (Sigma (_ A) (papp PQx i)) (cofib i0 i1) Te ee)) (pair ppx qqx))) (quote (transp (plam i (Sigma (_ A) (papp PQx i))) (pair ppx qqx))))) (newline)
(kernel-assume (quote Rz) (quote (Sort 0)))
(kernel-assume (quote eRz) (quote (Equiv Rz A)))
(kernel-assume (quote rz) (quote Rz))
(display (iuv-transp-held-glue-line-reduces? (quote (transp (plam i (Glue A (cofib i1 i1) (Sigma (_ Rz) (papp PQx i)) eRz)) (pair rz qqx))) (quote (transp (plam i (Sigma (_ Rz) (papp PQx i))) (pair rz qqx))))) (newline)
(kernel-assume (quote Cz0) (quote (Sort 0)))
(kernel-assume (quote Cz1) (quote (Sort 0)))
(kernel-assume (quote CPAz) (quote (Path (Sort 0) Cz0 Cz1)))
(kernel-assume (quote czx) (quote Cz0))
(display (iuv-comp-reduces? (quote (comp (plam i (papp CPAz i)) (cofib i0 i1) czx czx)) (quote (transp (plam i (papp CPAz i)) czx)))) (newline)
(display (iuv-comp-total-reduces? (quote (comp (plam i (papp CPAz i)) (cofib i1 i1) czx czx)) (quote (hcomp1 Cz1 (cofib i1 i1) (transp (plam i (papp CPAz i)) czx) (transp (plam i (papp CPAz i)) czx))))) (newline)
(kernel-assume (quote DSa0) (quote (Sort 0)))
(kernel-assume (quote DSa1) (quote (Sort 0)))
(kernel-assume (quote DSPA) (quote (Path (Sort 0) DSa0 DSa1)))
(kernel-assume (quote dsa) (quote DSa0))
(kernel-assume (quote dsb) (quote (Id DSa0 dsa dsa)))
(display (iuv-dep-sigma-reduces? (quote (transp (plam i (Sigma (x (papp DSPA i)) (Id (papp DSPA i) x x))) (pair dsa dsb))) (quote (pair (transp (plam i (papp DSPA i)) dsa) (transp (plam i (Id (papp DSPA i) (transp (plam k (papp DSPA (imeet k i))) dsa) (transp (plam k (papp DSPA (imeet k i))) dsa))) dsb))))) (newline)
(display (iuv-dep-sigma-check (quote (transp (plam i (Sigma (x (papp DSPA i)) (Id (papp DSPA i) x x))) (pair dsa dsb))) (quote (Sigma (x (papp DSPA i1)) (Id (papp DSPA i1) x x))))) (newline)
(display (iuv-imeet-reduces? (quote (imeet i1 dsa)) (quote dsa))) (newline)
(kernel-assume (quote IVa0) (quote (Sort 0)))
(kernel-assume (quote IVa1) (quote (Sort 0)))
(kernel-assume (quote IVPA) (quote (Path (Sort 0) IVa0 IVa1)))
(kernel-assume (quote ivx0) (quote IVa0))
(display (iuv-ivcomp-held-reduces? (quote (comp (plam i (papp IVPA i)) (cofib i1 i1) (plam i (transp (plam k (papp IVPA (imeet k i))) ivx0)) ivx0)) (quote (transp (plam k (papp IVPA (imeet k i1))) ivx0)))) (newline)
(display (iuv-ivcomp-check (quote (comp (plam i (papp IVPA i)) (cofib i1 i1) (plam i (transp (plam k (papp IVPA (imeet k i))) ivx0)) ivx0)) (quote IVa1))) (newline)
(kernel-assume (quote ivsec) (quote (Pi (i I) (papp IVPA i))))
(display (not (kernel-equal? (quote (transp (plam i (papp IVPA i)) (app ivsec i0))) (quote (app ivsec i1))))) (newline)
(kernel-assume (quote PLa0) (quote (Sort 0)))
(kernel-assume (quote PLa1) (quote (Sort 0)))
(kernel-assume (quote PLPA) (quote (Path (Sort 0) PLa0 PLa1)))
(kernel-assume (quote plu) (quote PLa0))
(kernel-assume (quote plw) (quote PLa0))
(kernel-assume (quote plpp) (quote (Path PLa0 plu plw)))
(display (iuv-comp2-reduces? (quote (comp2 (plam i (papp PLPA i)) (cofib i1 i1) (plam i (transp (plam k (papp PLPA (imeet k i))) plu)) (cofib i0 i1) (plam i (transp (plam k (papp PLPA (imeet k i))) plu)) plu)) (quote (transp (plam k (papp PLPA (imeet k i1))) plu)))) (newline)
(display (iuv-pathline-transport-endpoint (quote (transp (plam i (Path (papp PLPA i) (transp (plam k (papp PLPA (imeet k i))) plu) (transp (plam k (papp PLPA (imeet k i))) plw))) plpp)) (quote i0) (quote (transp (plam k (papp PLPA (imeet k i1))) plu)))) (newline)
(display (iuv-pathline-transport-endpoint (quote (transp (plam i (Path (papp PLPA i) (transp (plam k (papp PLPA (imeet k i))) plu) (transp (plam k (papp PLPA (imeet k i))) plw))) plpp)) (quote i1) (quote (transp (plam k (papp PLPA (imeet k i1))) plw)))) (newline)
(kernel-assume (quote GGA) (quote (Sort 0)))
(kernel-assume (quote GGT) (quote (Sort 0)))
(kernel-assume (quote GGf) (quote (Pi (_ GGT) GGA)))
(kernel-assume (quote GGg) (quote (Pi (_ GGA) GGT)))
(kernel-assume (quote GGeta) (quote (Pi (x GGT) (Id GGT (app GGg (app GGf x)) x))))
(kernel-assume (quote GGeps) (quote (Pi (y GGA) (Id GGA (app GGf (app GGg y)) y))))
(kernel-assume (quote GGtt) (quote GGT))
(display (iuv-glue-intro-reduces? (quote (glue GGA (cofib i1 i1) GGT (mk-equiv GGT GGA GGf GGg GGeta GGeps) GGtt (app GGf GGtt))) (quote GGtt))) (newline)
(display (iuv-glue-intro-reduces? (quote (glue GGA (cofib i0 i1) GGT (mk-equiv GGT GGA GGf GGg GGeta GGeps) GGtt (app GGf GGtt))) (quote (app GGf GGtt)))) (newline)
(display (iuv-unglue-beta? (quote (unglue GGA (cofib i1 i1) GGT (mk-equiv GGT GGA GGf GGg GGeta GGeps) (glue GGA (cofib i1 i1) GGT (mk-equiv GGT GGA GGf GGg GGeta GGeps) GGtt (app GGf GGtt)))) (quote (app GGf GGtt)))) (newline)
(kernel-assume (quote PpA) (quote (Sort 0)))
(display (iuv-partial-reduces? (quote (Partial (cofib i1 i1) PpA)) (quote PpA))) (newline)
(display (iuv-partial-reduces? (quote (Partial (cofib i0 i1) PpA)) (quote Unit))) (newline)
(kernel-assume (quote QA0) (quote (Sort 0))) (kernel-assume (quote QA1) (quote (Sort 0)))
(kernel-assume (quote QPA) (quote (Path (Sort 0) QA0 QA1)))
(kernel-assume (quote QT0) (quote (Sort 0))) (kernel-assume (quote QT1) (quote (Sort 0)))
(kernel-assume (quote QPT) (quote (Path (Sort 0) QT0 QT1)))
(kernel-assume (quote Qe) (quote (Pi (i I) (Equiv (papp QPT i) (papp QPA i)))))
(kernel-assume (quote Qj) (quote I))
(kernel-assume (quote Qg) (quote (Glue QA0 (cofib Qj i1) QT0 (app Qe i0))))
(display (not (error-object? (kernel-infer (quote (transp (plam i (Glue (papp QPA i) (cofib Qj i1) (papp QPT i) (app Qe i))) Qg)))))) (newline)
(kernel-assume (quote SsA) (quote (Sort 0)))
(kernel-assume (quote Ssa) (quote SsA))
(display (iuv-psys-reduces? (quote (psys (cofib i1 i1) SsA Ssa)) (quote Ssa))) (newline)
(display (iuv-psys-reduces? (quote (psys (cofib i0 i1) SsA Ssa)) (quote *))) (newline)
(kernel-assume (quote Ssj) (quote I))
(display (not (error-object? (kernel-infer (quote (psys (cofib Ssj i1) SsA Ssa)))))) (newline)
(kernel-assume (quote ZT) (quote (Sort 0)))
(kernel-assume (quote Zg) (quote ZT))
(kernel-assume (quote Zu) (quote (Pi (i I) ZT)))
(kernel-assume (quote Zk) (quote I))
(display (iuv-comp2-reduces? (quote (comp2 (plam l ZT) (cofib i1 i1) (plam l (app Zu (imeet Zk l))) (cofib Zk i0) (plam l Zg) Zg)) (quote (app Zu Zk)))) (newline)
(display (iuv-comp2-reduces? (quote (comp2 (plam l ZT) (cofib Zk i1) (plam l (app Zu l)) (cofib i1 i0) (plam l Zg) Zg)) (quote (comp (plam l ZT) (cofib Zk i1) (plam l (app Zu l)) Zg)))) (newline)
(kernel-assume (quote WA) (quote (Sort 0))) (kernel-assume (quote WT) (quote (Sort 0)))
(kernel-assume (quote Wee) (quote (Equiv WT WA)))
(kernel-assume (quote Wj) (quote I))
(kernel-assume (quote Wg) (quote (Glue WA (cofib Wj i1) WT Wee)))
(kernel-assume (quote Wu) (quote (Pi (i I) (Glue WA (cofib Wj i1) WT Wee))))
(display (not (error-object? (kernel-infer (quote (comp (plam i (Glue WA (cofib Wj i1) WT Wee)) (cofib Wj i1) (plam i (app Wu i)) Wg)))))) (newline)
(display (kernel-equal? (quote (comp (plam i (Glue WA (cofib Wj i1) WT Wee)) (cofib i1 i1) (plam i (app Wu i)) Wg)) (quote (app Wu i1)))) (newline)
(kernel-assume (quote ZA) (quote (Sort 0))) (kernel-assume (quote Za) (quote ZA)) (kernel-assume (quote Zj) (quote I))
(display (not (error-object? (kernel-infer (quote (cofib-or (cofib Zj i1) (cofib i1 i1))))))) (newline)
(display (kernel-equal? (quote (hcomp1 ZA (cofib-or (cofib i1 i1) (cofib Zj i1)) Za Za)) (quote Za))) (newline)
(kernel-assume (quote YA0) (quote (Sort 0))) (kernel-assume (quote YA1) (quote (Sort 0))) (kernel-assume (quote YPA) (quote (Path (Sort 0) YA0 YA1)))
(kernel-assume (quote YT0) (quote (Sort 0))) (kernel-assume (quote YT1) (quote (Sort 0))) (kernel-assume (quote YPT) (quote (Path (Sort 0) YT0 YT1)))
(kernel-assume (quote Yef) (quote (Pi (i I) (Equiv (papp YPT i) (papp YPA i))))) (kernel-assume (quote Ywt) (quote (Pi (i I) (papp YPT i))))
(display (not (error-object? (kernel-infer (list (quote lam) (quote (m I)) (list (quote lam) (quote (i I)) (quote (comp2 (plam l (papp YPT (imeet i l))) (cofib m i1) (plam l (app Ywt (imeet i l))) (cofib i i0) (plam l (app Ywt i0)) (app Ywt i0))))))))) (newline)
(kernel-assume (quote ZZA0) (quote (Sort 0))) (kernel-assume (quote ZZA1) (quote (Sort 0))) (kernel-assume (quote ZZPA) (quote (Path (Sort 0) ZZA0 ZZA1)))
(kernel-assume (quote ZZT0) (quote (Sort 0))) (kernel-assume (quote ZZT1) (quote (Sort 0))) (kernel-assume (quote ZZPT) (quote (Path (Sort 0) ZZT0 ZZT1)))
(kernel-assume (quote ZZef) (quote (Pi (i I) (Equiv (papp ZZPT i) (papp ZZPA i))))) (kernel-assume (quote ZZm) (quote I)) (kernel-assume (quote ZZwt) (quote (Pi (i I) (papp ZZPT i))))
(display (kernel-equal?
  (list (quote comp) (quote (plam i (Glue (papp ZZPA i) (cofib ZZm i1) (papp ZZPT i) (app ZZef i)))) (quote (cofib i1 i1)) (list (quote plam) (quote i) (quote (glue (papp ZZPA i) (cofib ZZm i1) (papp ZZPT i) (app ZZef i) (app ZZwt i) (app (equiv-fun (app ZZef i)) (app ZZwt i))))) (quote (glue ZZA0 (cofib ZZm i1) ZZT0 (app ZZef i0) (app ZZwt i0) (app (equiv-fun (app ZZef i0)) (app ZZwt i0)))))
  (quote (glue (papp ZZPA i1) (cofib ZZm i1) (papp ZZPT i1) (app ZZef i1) (app ZZwt i1) (app (equiv-fun (app ZZef i1)) (app ZZwt i1)))))) (newline)
(display (kernel-equal? (quote (cofib-forall i (cofib i i1))) (quote (cofib i0 i1)))) (newline)
(display (kernel-equal? (quote (cofib-forall i (cofib i1 i1))) (quote (cofib i1 i1)))) (newline)
