(import "cas/certkernel.lisp")
(display (certkernel-check-nonneg (list 1 1 1))) (newline)
(display (certkernel-check-nonneg (list 1 0 1))) (newline)
(display (certkernel-check-nonneg (list 1 -2 1))) (newline)
(display (certkernel-check-nonneg (list 1 -4 5))) (newline)
(display (certkernel-check-nonneg (list -1 0 1))) (newline)
(display (certkernel-check-nonneg (list 0 1))) (newline)
(display (certkernel-check-deriv (cas (list (quote *) (quote x) (quote x))))) (newline)
(display (certkernel-check-deriv (kapp (quote sin) (quote x)))) (newline)
