(import "cas/bch.lisp")
(define p 2) (define m 4) (define mod (gf-modulus p m)) (define n 15) (define alpha (gf-elt 2 p m))
(define g (bch-generator alpha 2 mod p n))
(define msg (list 1 0 1 1 0 0 1))
(define cw (bch-encode msg g n))
(display (trim g)) (newline)
(display (list (bch-deg g) (bch-k n g))) (newline)
(display cw) (newline)
(display (bch-all-zero? (bch-syndromes cw alpha 2 mod p))) (newline)
(display (bch-clean-ok? msg alpha 2 mod p n g)) (newline)
(display (list (bch-roundtrip-ok? msg alpha 2 mod p n g (list 5)) (bch-roundtrip-ok? msg alpha 2 mod p n g (list 2 11)))) (newline)
(define g3 (bch-generator alpha 3 mod p n))
(display (list (bch-deg g3) (bch-roundtrip-ok? (list 1 0 1 1 0) alpha 3 mod p n g3 (list 0 7 14)))) (newline)
