(import "cas/idt.lisp")
(define (V n) (list (quote var) n))
(define ctxAa (list (V 0) (quote type)))
(display (idt-equal? (idt-infer ctxAa (idt-Id (V 1) (V 0) (V 0))) (quote type))) (newline)
(display (idt-check ctxAa (idt-refl (V 1) (V 0)) (idt-Id (V 1) (V 0) (V 0)))) (newline)
(define A1 (V 1))
(define motive (list (quote lam) A1 (list (quote lam) (idt-shift 1 0 A1) (list (quote lam) (idt-Id (idt-shift 2 0 A1) (V 1) (V 0)) (idt-Id (idt-shift 3 0 A1) (V 2) (V 2))))))
(define base (list (quote lam) A1 (idt-refl (idt-shift 1 0 A1) (V 0))))
(display (idt-equal? (idt-J A1 motive base (V 0) (V 0) (idt-refl A1 (V 0))) (list (quote app) base (V 0)))) (newline)
(define ctx (list (idt-Id (V 2) (V 1) (V 0)) (V 1) (V 0) (quote type)))
(display (idt-check ctx (idt-sym (V 3) (V 2) (V 1) (V 0)) (idt-Id (V 3) (V 1) (V 2)))) (newline)
(display (idt-equal? (idt-sym (V 1) (V 0) (V 0) (idt-refl (V 1) (V 0))) (idt-refl (V 1) (V 0)))) (newline)
(define ctxT (list (list (quote app) (V 3) (V 2)) (idt-Id (V 3) (V 1) (V 0)) (V 2) (V 1) (list (quote pi) (V 0) (quote type)) (quote type)))
(display (idt-equal? (idt-infer ctxT (idt-transport (V 5) (V 4) (V 3) (V 2) (V 1) (V 0))) (list (quote app) (V 4) (V 2)))) (newline)
(display (idt-equal? (idt-transport (V 3) (V 2) (V 1) (V 1) (idt-refl (V 3) (V 1)) (V 0)) (V 0))) (newline)
