(import "cas/elliptic3.lisp")
(define q2 (rat-from-poly (list 1 0 1)))
(define g2 (af-make (rat-from-poly (list 0 1)) (rat-one)))
(define om2 (e3-logderiv q2 g2))
(display (e3-certify q2 g2 om2)) (newline)
(display (car (e3-recognize q2 om2 g2))) (newline)
(define q3 (rat-from-poly (list 1 0 0 1)))
(define g3 (af-make (rat-from-poly (list 0 1)) (rat-one)))
(define om3 (e3-logderiv q3 g3))
(display (e3-certify q3 g3 om3)) (newline)
(define g3b (af-make (rat-from-poly (list 1 0 1)) (rat-from-poly (list 2))))
(display (e3-certify q3 g3b (e3-logderiv q3 g3b))) (newline)
(display (car (e3-recognize q3 (af-make (rat-zero) (rat-one)) g3))) (newline)
