(import "cas/rderat.lisp")
(display (int-rat-exp-rat (list -1) (list 0 0 1) (list 1) (list 0 1))) (newline)
(display (int-rat-exp-rat (list -1 1) (list 0 1) (list 1) (list 0 1))) (newline)
(display (int-rat-exp-rat (list 2) (list 0 0 0 1) (list -1) (list 0 0 1))) (newline)
(display (list (int-rat-exp-rat-verify (list 0 2) (list 1) (list 0 0 1) (list 1))
               (int-rat-exp-rat-verify (list -1 1) (list 0 0 1) (list 0 1) (list 1)))) (newline)
(display (rdr-denbound (list 0 0 1) (list 0 0 1))) (newline)
(display (rdr-denbound (list 0 0 0 1) (list 1))) (newline)
(display (car (int-rat-exp-rat (list 1) (list 1) (list 1) (list 0 1)))) (newline)
