(import "cas/superintbasis.lisp")
(display (sib-power-basis 3)) (newline)
(display (sib-element-minpoly 3 (list 0 1) 2)) (newline)
(display (sib-element-integral? 3 (list 0 1) 1)) (display " ") (display (sib-element-integral? 3 (list 0 1) 2)) (newline)
(display (sib-discriminant 3 (list 0 1))) (newline)
(display (sib-squarefree? (list -1 0 1))) (display " ") (display (sib-squarefree? (list 0 0 1))) (newline)
(display (sib-is-maximal? 3 (list 0 1))) (display " ") (display (sib-is-maximal? 2 (list -1 0 1))) (display " ") (display (sib-is-maximal? 2 (list 0 0 1))) (newline)
(display (sib-power-basis 4)) (newline)
(display (poly-deg (sib-repeated-factor 2 (list 0 0 1)))) (newline)
