(import "cas/tower2algn.lisp")
(define MEXP (list 'exp (list 0 1)))
(define Dth2 (list (list (rat-zero) (rat-one)) (list (rat-one) (rat-one))))
(define Ds (list (k1-from-int -2) (k1-zero) (k1-zero) (k1-one)))
(define As (list (k1-iscale 6 Dth2)))
(define q (h2algn-respoly As Ds Dth2 MEXP))
(display q) (newline)
(display (h2algn-irreducible? q)) (newline)
(display (h2-equal? (h2-norm (h2algn-num As Ds Dth2 MEXP q)) (h2-norm As))) (newline)
