(import "cas/intlog.lisp")
(define a2 (list (rat-from-poly (list -1 -3)) (rat-make (list 3 1) (list 0 1))))
(define d2 (list (rat-from-poly (list 0 0 -1)) (rat-zero) (rat-one)))
(define A3 (rfpoly-add (rfpoly-mul (rfpoly-monomial (rat-one) 2) d2) a2))
(display (car (cdr (int-log-rational A3 d2)))) (newline)
(display (int-log-rational-verify A3 d2)) (newline)
(display (int-log-rational-elementary? A3 d2)) (newline)
(display (int-log-rational-verify (rfpoly-monomial (rat-one) 3) (rf-const (rat-one)))) (newline)
(define D5 (list (rat-from-poly (list 0 1)) (rat-zero) (rat-one)))
(display (int-log-rational-elementary? (list (rat-zero) (rat-one)) D5)) (newline)
