(import "cas/cadqe.lisp")
(define x2pb (list (list 0 1) (list) (list 1)))
(define x2mb (list (list 0 -1) (list) (list 1)))
(define justx (list (list 0) (list 1)))
(define xmb2m1 (list (list -1 0 1) (list 0 -2) (list 1)))
(define x2pb2p1 (list (list 1 0 1) (list) (list 1)))
(display (cadqe-formula (quote exists) (cons (quote neg) x2pb))) (newline)
(display (cadqe-formula (quote forall) (cons (quote nonneg) x2mb))) (newline)
(display (cadqe-formula (quote exists) (cons (quote zero) x2mb))) (newline)
(display (cadqe-formula (quote exists) (list (quote and) (cons (quote zero) x2mb) (cons (quote pos) justx)))) (newline)
(display (cadqe-formula (quote exists) (cons (quote neg) xmb2m1))) (newline)
(display (cadqe-formula (quote exists) (cons (quote neg) x2pb2p1))) (newline)
