(import "cas/twotower.lisp")
(define one (rat-one)) (define zero (rat-zero))
(define E (list (list) (list zero one)))
(define B (tt-deriv E))
(display (tt-tcoeff B 1)) (newline)
(display (tt-tcoeff B 0)) (newline)
(display (tt-certify E B)) (newline)
(display (tt-solve B 1 1 0)) (newline)
(define res (tt-integrate B))
(display (car res)) (newline)
(define Ee (list (list zero one)))
(define Be (tt-deriv Ee))
(display (tt-solve Be 0 1 0)) (newline)
