(import "cas/polycf.lisp")
(display (pcf-is-square? (list 1 0 2 0 1))) (newline)
(display (pcf-unit-status (list 1 0 2 0 1) 30)) (newline)
(display (pcf-is-square? (list 0 1 0 0 0 0 1))) (newline)
(display (car (pcf-unit-status (list 1 0 0 0 0 0 1) 30))) (newline)
(display (car (pcf-unit-status (list 0 1 0 0 0 0 1) 30))) (newline)
(display (pcf-unit-status (list 1 0 1 0 0 0 1) 30)) (newline)
(define A (list 1 0 1 0 1))
(define Bp (list 0 1))
(define f1 (car (poly-divmod (poly-sub (poly-mul A A) (list 1)) (poly-mul Bp Bp))))
(display (poly-norm f1)) (newline)
(display (pcf-is-square? f1)) (newline)
(display (pcf-certify-unit f1 60)) (newline)
(display (list (poly-norm (car (cdr (pcf-unit-status f1 60)))) (poly-norm (car (cdr (cdr (pcf-unit-status f1 60))))))) (newline)
