(import "cas/sethird.lisp")
(define g (list 1 0 0 1))
(define u (st-a+y (list 0 1) 3))
(display (cdr (st-nth (st-log g 3 u) 2))) (newline)
(display (st-log-certify g 3 u)) (newline)
(display (st-norm-a+y (list 0 1) g 3)) (newline)
(define rec (st-recognize g 3 (list 1 0 0 2)))
(display (st-nth rec 2)) (newline)
(display (st-recognize-certify g 3 (list 0 1))) (newline)
(display (st-norm-a+y (list 1 1) g 3)) (newline)
(display (st-nth (st-recognize g 3 (st-norm-a+y (list 1 1) g 3)) 2)) (newline)
(display (st-recognize g 3 (list 5 0 1))) (newline)
(define g2 (list 1 0 1))
(display (st-log-certify g2 2 (st-a+y (list 0 1) 2))) (newline)
