(import "cas/odeuler.lisp")
(display (oe-indicial 1 -1)) (newline)
(display (oe-discriminant 1 -1)) (display " ") (display (oe-case 1 -1)) (newline)
(display (oe-exponents 1 -1)) (newline)
(display (oe-certify-int 1 -1 1)) (display " ") (display (oe-certify-int 1 -1 -1)) (display " ") (display (oe-certify-int 1 -1 2)) (newline)
(display (oe-solve 1 -1)) (newline)
(display (oe-discriminant 3 1)) (display " ") (display (oe-repeated-exponent 3 1)) (display " ") (display (oe-certify-int 3 1 -1)) (newline)
(display (oe-solve 3 1)) (newline)
(display (oe-case 1 1)) (newline)
(display (oe-exponents 1 -2)) (newline)
