(import "cas/inettype.lisp")
(kernel-assume (quote A) (quote (Sort 0)))
(kernel-assume (quote B) (quote (Sort 0)))
(display (itt-type-equal? (itt-arrow (quote A) (quote A)) (itt-arrow (quote A) (quote A)))) (newline)
(display (itt-type-equal? (quote A) (itt-arrow (quote A) (quote A)))) (newline)
(define (wt-of builder) (begin (itt-reset! 200) (builder) (itt-well-typed?)))
(display (wt-of (lambda () (itt-build (quote (I A)))))) (newline)
(display (wt-of (lambda () (itt-build (quote (K A B)))))) (newline)
(display (wt-of (lambda () (itt-bad-identity (quote A) (quote B))))) (newline)
(display (itt-agree? (quote (I A)) (quote (lam (x A) x)) (quote (Pi (x A) A)))) (newline)
(display (itt-agree? (quote (K A B)) (quote (lam (x A) (lam (y B) x))) (quote (Pi (x A) (Pi (y B) A))))) (newline)
