(import "cas/normalform.lisp")
(define S (list (list 1 2 3) (list 4 5 6) (list 7 8 9)))
(display "rank = ") (display (mat-rank S)) (newline)
(display "nullspace = ") (display (mat-nullspace S)) (newline)
(define M (list (list 1 2) (list 3 4)))
(display "HNF H = ") (display (car (mat-hnf M))) (newline)
(display "HNF U = ") (display (car (cdr (mat-hnf M)))) (newline)
(display "SNF inv [[2,0],[0,3]] = ") (display (smith-invariants (list (list 2 0) (list 0 3)))) (newline)
(display "SNF inv [[6,0],[0,4]] = ") (display (smith-invariants (list (list 6 0) (list 0 4)))) (newline)
(display "SNF inv 3x3 = ") (display (smith-invariants (list (list 2 4 4) (list -6 6 12) (list 10 4 16)))) (newline)
