(import "cas/rischstruct.lisp")
(define f (rat-make (list 0 2) (list -1 0 1)))
(define g1 (rat-from-poly (list -1 0 1)))
(display (struct-log-solve f (list g1))) (newline)
(define gA (rat-from-poly (list -1 1)))
(define gB (rat-from-poly (list 1 1)))
(define r2 (struct-log-solve f (list gA gB)))
(display (struct-log-certify f (list gA gB) (car (cdr r2)))) (newline)
(define f3 (rat-add (rat-make (list 3) (list -1 1)) (rat-make (list 5) (list 2 1))))
(define gC (rat-from-poly (list 2 1)))
(display (struct-log-solve f3 (list gA gC))) (newline)
(define f4 (rat-make (list 1) (list 1 0 1)))
(display (struct-log-solve f4 (list gA))) (newline)
