(import "cas/linalg.lisp")
(define D (list (list 2 0 0) (list 0 3 0) (list 0 0 5)))
(define M (list (list 1 2) (list 3 4)))
(define F (list (list 0 1) (list 1 1)))
(define R (list (list 0 -1) (list 1 0)))
(display (mat-charpoly->string D)) (newline)
(display (mat-charpoly->string M)) (newline)
(display "det M = ") (display (mat-det M)) (newline)
(display (mat-eigenvalues->string M)) (newline)
(display (mat-eigenvalues->string F)) (newline)
(display (mat-eigenvalues->string R)) (newline)
(display "inv M = ") (display (mat-inverse M)) (newline)
