(import "cas/cadqen.lisp")
(define genq (list (list (cons 1 (list 0 0 1))) (list (cons 1 (list 0 1 0))) (list (cons 1 (list 1 0 0)))))
(define q3factors (list (list (list 1 1 0 0)) (list (list 1 0 1 0)) (list (list 1 0 0 1)) (list (list 1 0 2 0) (list -4 1 0 1))))
(define q3 (cadqen-elim q3factors 3 (quote exists) (cons (quote zero) genq)))
(define (present? v vs) (cond ((null? vs) #f) ((equal? v (car vs)) #t) (else (present? v (cdr vs)))))
(display (length (cdr q3))) (newline)
(display (present? (list 1 1 1 1) (cdr q3))) (newline)
(define axmb (list (list (cons -1 (list 0 1 0 0))) (list (cons 1 (list 1 0 0 0)))))
(define cxmd (list (list (cons -1 (list 0 0 0 1))) (list (cons 1 (list 0 0 1 0)))))
(define phi4 (list (quote and) (cons (quote zero) axmb) (cons (quote zero) cxmd)))
(define q4factors (list (list (list 1 1 0 0 0)) (list (list 1 0 1 0 0)) (list (list 1 0 0 1 0)) (list (list 1 0 0 0 1)) (list (list 1 0 1 1 0) (list -1 1 0 0 1))))
(define q4 (cadqen-elim q4factors 4 (quote exists) phi4))
(display (present? (list 0 0 0 0 0) (cdr q4))) (newline)
(display (present? (list 0 0 0 1 0) (cdr q4))) (newline)
(display (cadqen-holds-at 4 (quote exists) phi4 (list 1 2 1 2))) (newline)
(display (cadqen-holds-at 4 (quote exists) phi4 (list 1 2 1 3))) (newline)
(display (cadqen-holds-at 4 (quote exists) phi4 (list 0 0 1 5))) (newline)
