(import "cas/inet.lisp")
(define (is-identity? g) (and (>= g 0) (= (inet-linked (inet-port g 1)) (inet-port g 2))))
(define (aa ep) (cond ((>= ep 0) (inet-ep-agent ep)) (else -1)))
(define (run-id-app)
  (begin (inet-reset! 100)
         (let ((id1 (inet-mk inet-LAM)))
           (inet-connect! (inet-port id1 1) (inet-port id1 2))
           (let ((id2 (inet-mk inet-LAM)))
             (inet-connect! (inet-port id2 1) (inet-port id2 2))
             (let ((ap (inet-mk inet-APP)) (probe (inet-mk inet-LAM)))
               (inet-connect! (inet-port ap 0) (inet-port id1 0))
               (inet-connect! (inet-port ap 1) (inet-port id2 0))
               (inet-connect! (inet-port ap 2) (inet-port probe 1))
               (inet-reduce!)
               (is-identity? (aa (inet-linked (inet-port probe 1)))))))))
(define (run-dup)
  (begin (inet-reset! 100)
         (let ((lam (inet-mk inet-LAM)))
           (inet-connect! (inet-port lam 1) (inet-port lam 2))
           (let ((dup (inet-mk inet-DUP)) (pa (inet-mk inet-LAM)) (pb (inet-mk inet-LAM)))
             (inet-connect! (inet-port dup 0) (inet-port lam 0))
             (inet-connect! (inet-port dup 1) (inet-port pa 1))
             (inet-connect! (inet-port dup 2) (inet-port pb 1))
             (inet-reduce!)
             (and (is-identity? (aa (inet-linked (inet-port pa 1)))) (is-identity? (aa (inet-linked (inet-port pb 1)))))))))
(display (inet-matching? inet-LAM inet-APP)) (newline)
(display (inet-matching? inet-DUP inet-SUP)) (newline)
(display (inet-matching? inet-LAM inet-DUP)) (newline)
(display (run-id-app)) (newline)
(display (run-dup)) (newline)
