(import "cas/reedsolomon.lisp")
(define p 11) (define xs (rs-points 10)) (define k 4) (define msg (list 3 1 4 1))
(define cw (rs-encode msg xs p))
(display cw) (newline)
(display (rs-info 10 4 11)) (newline)
(display (list (rs-distance 10 4) (rs-t 10 4))) (newline)
(display (rs-decode cw xs k p)) (newline)
(display (rs-decode (rs-corrupt cw (list (cons 2 5)) p) xs k p)) (newline)
(display (rs-decode (rs-corrupt cw (list (cons 1 2) (cons 4 9) (cons 8 6)) p) xs k p)) (newline)
(display (rs-decode (rs-corrupt cw (list (cons 0 1) (cons 1 1) (cons 2 1) (cons 3 1)) p) xs k p)) (newline)
(display (list (rs-roundtrip-ok? msg xs k p (list (cons 0 7) (cons 5 3))) (rs-roundtrip-ok? (list 17 23) (rs-points 8) 2 29 (list (cons 1 11) (cons 3 22) (cons 7 5))))) (newline)
