(import "cas/rischtop.lisp")
(define r (integrate-top-rational (list 0 0 0 2) (list -1 0 1)))
(display (integrate-top-certify-rational (list 0 0 0 2) (list -1 0 1) r)) (newline)
(define ra (integrate-top-rational (list 1) (list 1 0 1)))
(display (integrate-top-certify-rational (list 1) (list 1 0 1) ra)) (newline)
(display (car (integrate-top-rational (list 1) (list -2 0 1)))) (newline)
(define t1 (list (list (quote exp) (rat-from-poly (list 0 1)))))
(display (car (integrate-top-tower t1 1 (list (rat-zero) (rat-one))))) (newline)
(define t1a (list (list (quote alg) 2 (rat-from-poly (list 0 1)))))
(display (car (integrate-top-tower t1a 1 (list (rat-zero) (rat-make (list 1) (list 0 2)))))) (newline)
(define t2 (list (list (quote exp) (rat-from-poly (list 0 1))) (list (quote exp) (list (rat-zero) (rat-one)))))
(display (car (integrate-top-tower t2 2 (list (te-zero 1) (te-one 1))))) (newline)
(define t1log (list (list (quote log) (rat-from-poly (list 0 1)))))
(display (car (integrate-top-laurent t1log 1 (list (rat-make (list 1) (list 0 1))) (quote ())))) (newline)
