(import "cas/mgcd.lisp")
(define x+y (list (list 0 1) (list 1)))
(define x-y (list (list 0 -1) (list 1)))
(define x-1 (list (list -1) (list 1)))
(define x+1 (list (list 1) (list 1)))
(display (xy->string (mgcd (xy-mul x-y x+y) (xy-mul x+y x+y)))) (newline)
(display (xy->string (mgcd (xy-mul x-y x+y) x-y))) (newline)
(display (xy->string (mgcd (xy-mul x+y x-1) (xy-mul x+y x+1)))) (newline)
(display (xy->string (mgcd (xy-mul (xy-mul x+y x+y) x-1) (xy-mul (xy-mul x+y x-1) x-1)))) (newline)
(display (xy->string (mgcd x+y x-y))) (newline)
(display (divides? (mgcd (xy-mul x-y x+y) (xy-mul x+y x+y)) (xy-mul x-y x+y))) (newline)
