(import "cas/inethott.lisp")
(kernel-assume (quote A) (quote (Sort 0)))
(kernel-assume (quote a) (quote A))
(kernel-assume (quote b) (quote A))
(define id-aa (ioe-id (ioe-var (quote A)) (ioe-var (quote a)) (ioe-var (quote a))))
(define refl-a (ioe-refl (ioe-var (quote a))))
(define path-aa (ioe-path (ioe-var (quote A)) (ioe-var (quote a)) (ioe-var (quote a))))
(display (ioe-readback-is? id-aa (quote (Id A a a)))) (newline)
(display (ioe-readback-is? refl-a (quote (refl a)))) (newline)
(display (ioe-check id-aa (quote (Sort 0)))) (newline)
(display (ioe-check refl-a (quote (Id A a a)))) (newline)
(display (not (ioe-check refl-a (quote (Id A a b))))) (newline)
(display (ioe-agree? refl-a (quote (refl a)) (quote (Id A a b)))) (newline)
(display (ioe-observational-equal? (quote (lam (x A) x)) (quote (lam (x A) x)))) (newline)
