(import "cas/groebnerf4.lisp")
(display (f4-rref (list (list 1 1) (list 1 -1)))) (newline)
(define f1 (list (cons 1 (list 1 0)) (cons 1 (list 0 1))))
(define f2 (list (cons 1 (list 1 0)) (cons -1 (list 0 1))))
(display (f4-monomials (list f1 f2))) (newline)
(display (f4-reduce (list f1 f2))) (newline)
(display (f4-spans-same? (list f1 f2))) (newline)
(define f3 (list (cons 2 (list 1 0)) (cons 2 (list 0 1))))
(display (f4-reduce (list f1 f3))) (newline)
(define g1 (list (cons 1 (list 2 0)) (cons 1 (list 0 2))))
(define g2 (list (cons 1 (list 2 0)) (cons -1 (list 0 2))))
(display (f4-reduce (list g1 g2))) (newline)
(display (f4-leading-monomials (list g1 g2))) (newline)
(display (f4-spans-same? (list g1 g2))) (newline)
