(import "cas/tower2.lisp")
(define EXP1 (list 'exp (list 0 1))) (define LOG (list 'log))
(define Dth2 (list (list (rat-zero) (rat-one)) (list (rat-one) (rat-one))))
(display (t2-int-exact-power-verify 0 Dth2 EXP1)) (newline)
(display (t2-int-exact-power-verify 2 Dth2 EXP1)) (newline)
(display (t2-int-exact-power-verify 4 Dth2 EXP1)) (newline)
(define Dth2b (list (list (rat-make (list 1) (list 0 1))) (list (rat-from-poly (list 1)) (rat-from-poly (list 1)))))
(display (t2-int-exact-power-verify 3 Dth2b LOG)) (newline)
(display (not (t2-equal? (t2-deriv (t2-monomial (t2-trrat (/ 1 2)) 2) Dth2 EXP1) (t2-monomial Dth2 2)))) (newline)
