(import "cas/ramplace.lisp")
(define fc (list 0 0 0 1))
(display (ram-mult fc 0)) (display " ") (display (ram-val-x fc 0)) (display " ") (display (ram-val-y fc 0)) (newline)
(display (ram-is-ramified? fc 0)) (display " ") (display (ram-element fc 0)) (display " ") (display (ram-element-sq fc 0)) (display " ") (display (ram-certify fc 0)) (newline)
(define f5 (list 0 0 0 0 0 1))
(display (ram-element f5 0)) (display " ") (display (ram-element-sq f5 0)) (display " ") (display (ram-certify f5 0)) (newline)
(define f31 (poly-mul (poly-mul (list -1 1) (list -1 1)) (list -1 1)))
(display (ram-element-sq f31 1)) (display " ") (display (ram-certify f31 1)) (newline)
(define f2 (list 0 0 1))
(display (ram-place-type f2 0)) (display " ") (display (ram-element-sq f2 0)) (display " ") (display (ram-certify f2 0)) (newline)
(display (ram-mult fc 1)) (display " ") (display (ram-place-type fc 1)) (display " ") (display (ram-element fc 1)) (newline)
