(import "cas/rischtop.lisp")
(display (rat-equal? (rat-add (rat-make (list 1) (list 3)) (rat-make (list 1) (list 6))) (rat-make (list 1) (list 2)))) (newline)
(display (rat-equal? (rat-deriv (rat-from-poly (list -1 0 1))) (rat-from-poly (list 0 2)))) (newline)
(define result (integrate-top-rational (list 0 2) (list -1 0 1)))
(display (integrate-top-certify-rational (list 0 2) (list -1 0 1) result)) (newline)
(define result2 (integrate-top-rational (list 1) (list 1 0 1)))
(display (integrate-top-certify-rational (list 1) (list 1 0 1) result2)) (newline)
(define t2 (list (list (quote exp) (rat-from-poly (list 0 1))) (list (quote exp) (list (rat-zero) (rat-one)))))
(display (car (integrate-top-tower t2 2 (list (te-zero 1) (te-one 1))))) (newline)
