(import "cas/liouvillelog.lisp")
(define d1 (lv-log-decide (list 1)))
(display (cdr d1)) (newline)
(display (lv-log-certify (list 1) (ll-nth d1 1) (ll-nth d1 2) (ll-nth d1 3))) (newline)
(define d2 (lv-log-decide (list 0 1)))
(display (cdr d2)) (newline)
(display (lv-log-certify (list 0 1) (ll-nth d2 1) (ll-nth d2 2) (ll-nth d2 3))) (newline)
(display (lv-log-certify (list 0 0 1) (ll-nth (lv-log-decide (list 0 0 1)) 1) (ll-nth (lv-log-decide (list 0 0 1)) 2) (ll-nth (lv-log-decide (list 0 0 1)) 3))) (newline)
(display (lv-log-li)) (newline)
