(import "cas/algtower2.lisp")
(define Dz (t2-deriv (t2-z)))
(display (af-equal? (t2-a Dz) (af-zero))) (display " ") (display (rat-equal? (af-u (t2-b Dz)) (rat-make (list 1) (list 0 4)))) (newline)
(display (t2-equal? (t2-mul (t2-z) (t2-z)) (t2-y))) (newline)
(display (t2-equal? (t2-mul (t2-mul (t2-z) (t2-z)) (t2-mul (t2-z) (t2-z))) (t2-from-rat (rat-from-poly (list 0 1))))) (newline)
(display (t2-equal? (t2-mul (t2-add (t2-one) (t2-z)) (t2-sub (t2-one) (t2-z))) (t2-sub (t2-one) (t2-y)))) (newline)
(display (rat-equal? (af-v (t2-a (t2-deriv (t2-y)))) (rat-make (list 1) (list 0 2)))) (newline)
(define xz (t2-make (af-zero) (af-from-rat (rat-from-poly (list 0 1)))))
(define ff (t2-make (af-zero) (af-from-rat (rat-from-poly (list (/ 5 4))))))
(display (t2-equal? (t2-deriv xz) ff)) (display " ") (display (t2-certify xz ff)) (newline)
