(import "cas/stnet.lisp")
(define A (quote o)) (define T (stnet-arr A A))
(define (typed-identity)
  (begin (stnet-reset! 50)
         (let ((id (inet-mk inet-LAM)))
           (inet-connect! (inet-port id 1) (inet-port id 2))
           (stnet-set-type! (inet-port id 0) (stnet-arr A A))
           (stnet-set-type! (inet-port id 1) A) (stnet-set-type! (inet-port id 2) A)
           (stnet-check))))
(define (ill-typed)
  (begin (stnet-reset! 50)
         (let ((bad (inet-mk inet-LAM)))
           (inet-connect! (inet-port bad 1) (inet-port bad 2))
           (stnet-set-type! (inet-port bad 0) (stnet-arr (quote o) (quote o)))
           (stnet-set-type! (inet-port bad 1) (quote o)) (stnet-set-type! (inet-port bad 2) (quote nat))
           (stnet-check))))
(define (app-before)
  (begin (stnet-reset! 200)
         (let ((f1 (inet-mk inet-LAM)) (f2 (inet-mk inet-LAM)) (ap (inet-mk inet-APP)))
           (inet-connect! (inet-port f1 1) (inet-port f1 2))
           (stnet-set-type! (inet-port f1 0) (stnet-arr T T)) (stnet-set-type! (inet-port f1 1) T) (stnet-set-type! (inet-port f1 2) T)
           (inet-connect! (inet-port f2 1) (inet-port f2 2))
           (stnet-set-type! (inet-port f2 0) T) (stnet-set-type! (inet-port f2 1) A) (stnet-set-type! (inet-port f2 2) A)
           (stnet-set-type! (inet-port ap 0) (stnet-arr T T)) (stnet-set-type! (inet-port ap 1) T) (stnet-set-type! (inet-port ap 2) T)
           (inet-connect! (inet-port ap 0) (inet-port f1 0))
           (inet-connect! (inet-port ap 1) (inet-port f2 0))
           (let ((b (stnet-check))) (inet-reduce!) (list b (inet-normal-form?) (stnet-check))))))
(display (typed-identity)) (newline)
(display (ill-typed)) (newline)
(display (app-before)) (newline)
