(import "cas/algtuples.lisp")
(define minp (list -2 0 1))
(define g_minp (list (cons 1 (list 2 0)) (cons -2 (list 0 0))))
(define g_yx (list (cons 1 (list 0 1)) (cons -1 (list 1 0))))
(define tup1 (at-tuple minp (list (list 0 1))))
(display tup1) (newline)
(display (at-certify minp (list g_minp g_yx) tup1)) (newline)
(define tup2 (at-tuple minp (list (list 0 0 1))))
(display (at-nth tup2 1)) (newline)
(define g_yx2 (list (cons 1 (list 0 1)) (cons -1 (list 2 0))))
(display (at-certify minp (list g_minp g_yx2) tup2)) (newline)
(define minp3 (list -2 0 0 1))
(define tup3 (at-tuple minp3 (list (list 0 0 1))))
(define g3 (list (cons 1 (list 3 0)) (cons -2 (list 0 0))))
(define g3y (list (cons 1 (list 0 1)) (cons -1 (list 2 0))))
(display (at-certify minp3 (list g3 g3y) tup3)) (newline)
(define wrong (list (at-root minp) (alg-add (at-root minp) (alg-one minp))))
(display (at-certify minp (list g_minp g_yx) wrong)) (newline)
