(import "cas/cadfull.lisp")
(define parab (list (list 0 -1) (list) (list 1)))
(define xm2 (list (list -2 1)))
(define circle (list (list -1 0 1) (list) (list 1)))
(define linexy (list (list 0 1) (list -1)))
(display (cadfull-decide2 (quote exists) (list (quote and) (cons (quote zero) parab) (cons (quote zero) xm2)))) (newline)
(display (cadfull-decide2 (quote exists) (list (quote and) (cons (quote zero) circle) (cons (quote zero) linexy)))) (newline)
(display (cadfull-decide2 (quote exists) (cons (quote neg) circle))) (newline)
(display (cadfull-decide2 (quote exists) (cons (quote neg) (list (list 1 0 1) (list) (list 1))))) (newline)
(display (cadfull-decide2 (quote exists) (list (quote and) (cons (quote zero) parab) (cons (quote zero) (list (list 1 1)))))) (newline)
