(import "cas/rischtfrde.lisp")
(define b (rat-from-poly (list 0 1)))
(define g1 (list (rat-zero) (rat-one)))
(display (tfr-certify b (rat-zero) g1 (tfr-solve b (rat-zero) g1))) (newline)
(define g2 (list (rat-zero) (rat-from-poly (list 0 1))))
(display (tfr-solve b (rat-zero) g2)) (newline)
(display (tfr-certify b (rat-zero) g2 (tfr-solve b (rat-zero) g2))) (newline)
(define g3 (list (rat-zero) (rat-make (list 1) (list 0 1))))
(display (tfr-solve b (rat-zero) g3)) (newline)
(define g4 (list (rat-zero) (rat-one) (rat-from-poly (list 0 1))))
(display (tfr-certify b (rat-zero) g4 (tfr-solve b (rat-zero) g4))) (newline)
(define g5 (list (rat-zero) (rat-one)))
(display (tfr-solve b (rat-one) g5)) (newline)
(display (tfr-certify b (rat-one) g5 (tfr-solve b (rat-one) g5))) (newline)
