(import "cas/sehermite.lisp")
(define g (list 1 0 0 1))
(display (se-integrate (list 0 2 0 0 3) g 1 3)) (newline)
(define Q2 (list 0 1 0 1))
(define P2 (se-dnum Q2 g 2 3))
(display P2) (newline)
(display (se-integrate P2 g 2 3)) (newline)
(display (se-integrate (list 0 0 (/ 3 2)) g 1 2)) (newline)
(display (se-integrate (list 1) g 1 3)) (newline)
