(import "cas/nestexp.lisp")
(define E (list (list) (list (rat-one))))
(define B (ne-deriv E))
(display (ne-scoeff B 1)) (newline)
(display (ne-peq? (ne-scoeff B 1) (list (rat-zero) (rat-one)))) (newline)
(display (ne-solve B 1 1)) (newline)
(display (car (ne-integrate B))) (newline)
(define E2 (list (list) (list) (list (rat-one))))
(define B2 (ne-deriv E2))
(display (ne-scoeff B2 2)) (newline)
(display (ne-solve B2 2 1)) (newline)
