(import "cas/superelliptic.lisp")
(define f3 (list 1 0 0 1))
(define f4 (list 1 0 0 0 1))
(define f5 (list 1 0 0 0 0 1))
(display (sup-genus 2 f3)) (display " ") (display (sup-genus 2 f5)) (newline)
(display (sup-genus 3 f4)) (display " ") (display (sup-genus 3 f5)) (display " ") (display (sup-genus 3 f3)) (newline)
(display (sup-genus 4 f3)) (display " ") (display (sup-genus 4 f5)) (newline)
(display (sup-genus-agrees? 3 f4)) (display " ") (display (sup-genus-agrees? 4 f5)) (display " ") (display (sup-genus-agrees? 6 f4)) (newline)
(display (sup-infinite-places 3 f4)) (display " ") (display (sup-infinite-places 4 f4)) (display " ") (display (sup-infinite-places 2 f4)) (newline)
(display (sup-reduces-to-hyperelliptic? f3)) (display " ") (display (sup-reduces-to-hyperelliptic? f4)) (newline)
