(import "cas/nbox.lisp")
(define (cn c n) (if (= n 0) c (list (cn c (- n 1)))))
(define xm (list (cn (/ -1 2) 2) (cn 1 2)))
(define ym (list (list (cn (/ -1 2) 1) (cn 1 1))))
(define sph (list (list (list -1 0 1) (list) (list 1)) (cn 0 2) (cn 1 2)))
(define box (list (cons (/ 4 10) (/ 6 10)) (cons (/ 4 10) (/ 6 10)) (cons (/ 6 10) (/ 8 10))))
(define pt (nbox-make (list xm ym sph) box))
(display (nbox-sign sph pt)) (display " ") (display (nbox-sign (list (list (list 0 1))) pt)) (newline)
(display (nbox-sign (list (list (list -1 0 2))) pt)) (display " ") (display (nbox-sign (list (list (list 0 -1)) (cn 1 2)) pt)) (newline)
(display (nbox-sign (list (list (list) (list -1)) (cn 1 2)) pt)) (newline)
