(import "cas/alglog.lisp")
(define p (list 0 1))
(define w (sf-set (sf-set (sf-zeros 2) 0 (rat-one)) 1 (rat-one)))
(define tp (al-tprime p 2 w))
(display tp) (newline)
(define Q (list (sf-zeros 2) (sf-one 2)))
(define B (al-deriv p 2 tp Q))
(display (al-certify p 2 tp Q B)) (newline)
(display (al-solve p 2 tp B 0)) (newline)
(define Qt2 (list (sf-zeros 2) (sf-zeros 2) (sf-set (sf-zeros 2) 0 (rat-make (list 1) (list 2)))))
(display (al-solve p 2 tp (al-deriv p 2 tp Qt2) 0)) (newline)
(define p3 (list 0 1))
(define w3 (sf-set (sf-set (sf-zeros 3) 0 (rat-one)) 1 (rat-one)))
(define tp3 (al-tprime p3 3 w3))
(define Q3 (list (sf-zeros 3) (sf-one 3)))
(display (al-solve p3 3 tp3 (al-deriv p3 3 tp3 Q3) 0)) (newline)
