(import "cas/cplxroots.lisp")
(display (cx-name-complex (list 1 0 1))) (newline)
(display (cx-quadratic-of (list (quote complex) 0 1))) (newline)
(display (cx-divides-quadratic? (list 1 0 1) (list (quote complex) 0 1))) (newline)
(display (cx-num-complex (list 1 0 1))) (newline)
(display (cx-name-complex (list 1 1 1))) (newline)
(define cubic (list -1 1 -1 1))
(display (cx-num-complex cubic)) (newline)
(display (cx-name-complex (ps3-deflate cubic (ps3-rational-roots cubic)))) (newline)
(display (cx-name-complex (list -1 0 1))) (display " ") (display (cx-num-complex (list -1 0 1))) (newline)
(display (cx-num-complex (list -1 0 0 0 1))) (newline)
