(import "cas/psubres.lisp")
(define (peval p v) (if (null? p) 0 (+ (car p) (* v (peval (cdr p) v)))))
(define parab (list (list 0 -1) (quote ()) (list 1)))
(define line (list (list -1) (list 1)))
(define two-x (list (quote ()) (list 2)))
(define parab1 (list (list -1) (quote ()) (list 1)))
(display (psubres-resultant parab line)) (newline)
(display (peval (psubres-resultant parab line) 1)) (newline)
(display (peval (psubres-resultant parab two-x) 0)) (newline)
(display (peval (psubres-resultant parab parab1) 1)) (newline)
(display (psubres-gcd-degree parab two-x)) (newline)
(display (psubres-gcd-degree parab parab)) (newline)
