(import "cas/tower2expint.lisp")
(define EXP1 (list 'exp (list 0 1)))
(define t1  (list (list (rat-zero) (rat-one)) (list (rat-one))))
(define a0  (list (list (rat-one)) (list (rat-one) (rat-one))))
(define a1  (k1-add t1 (k1-mul t1 t1)))
(define a2  (k1-iscale 6 t1))
(define P (list a0 a1 a2))
(display (t2e-ps-integrable? P t1 EXP1)) (newline)
(display (t2e-int-powersum-verify P t1 EXP1)) (newline)
