(import "cas/expnrt.lisp")
(define (residues r) (map car (car (cdr (cdr r)))))
(define a1 (list (rat-from-poly (list -6)) (rat-from-poly (list -5))))
(define d1 (list (rat-from-poly (list 2)) (rat-from-poly (list 3)) (rat-one)))
(display (residues (int-exp-rational a1 d1))) (newline)
(display (car (cdr (cdr (cdr (int-exp-rational a1 d1)))))) (newline)
(display (int-exp-rational-verify a1 d1)) (newline)
(define a3 (list (rat-make (list -9) (list 2)) (rat-make (list -1) (list 2))))
(define d3 (list (rat-from-poly (list 3)) (rat-from-poly (list 4)) (rat-one)))
(display (residues (int-exp-rational a3 d3))) (newline)
(display (int-exp-rational-verify a3 d3)) (newline)
(define a5 (list (rat-one))) (define d5 (list (rat-from-poly (list 0 1)) (rat-one)))
(display (int-exp-rational-elementary? a5 d5)) (newline)
