(import "cas/elliptic.lisp")
(define q3 (list 1 0 0 1))
(define q4 (list 1 0 0 0 1))
(define r1 (ell-integrate (list 0 0 (/ 3 2)) q3))
(display (ell-certify (list 0 0 (/ 3 2)) q3 r1)) (newline)
(display (car (cdr r1))) (newline)
(define r5 (ell-integrate (list 0 0 0 2) q4))
(display (ell-certify (list 0 0 0 2) q4 r5)) (newline)
(display (car (ell-integrate (list 1) q3))) (newline)
(display (car (ell-integrate (list 0 1) q3))) (newline)
(display (car (ell-integrate (list 1) q4))) (newline)
(display (car (ell-integrate (list 1 0 (/ 3 2)) q3))) (newline)
(display (car (ell-integrate (list 1) (list 0 0 0 0 1)))) (newline)
(define s1 (ell-split (list 1 0 (/ 3 2)) q3))
(display s1) (newline)
(display (ell-split-elementary? (ell-split (list 0 0 (/ 3 2)) q3))) (newline)
(define ss (ell-split-sqrt (list 1) q3))
(display ss) (newline)
