(import "cas/groebner2.lisp")
(define px2 (list (cons 1 (list 2 0))))
(define py (list (cons 1 (list 0 1))))
(define px (list (cons 1 (list 1 0))))
(define pxy (list (cons 1 (list 1 1))))
(display (coprime-lm? px2 py)) (display " ") (display (coprime-lm? px pxy)) (newline)
(define f1 (list (cons 1 (list 2 0)) (cons 1 (list 0 2)) (cons -1 (list 0 0))))
(define f2 (list (cons 1 (list 1 0)) (cons -1 (list 0 1))))
(display (groebner-ok? (groebner2 (list f1 f2)))) (display " ") (display (groebner2-agrees? (list f1 f2))) (newline)
(define g1 (list (cons 1 (list 2 0)) (cons -1 (list 0 0))))
(define g2 (list (cons 1 (list 0 2)) (cons -1 (list 0 0))))
(display (groebner2-agrees? (list g1 g2))) (newline)
(define h1 (list (cons 1 (list 1 1)) (cons -1 (list 0 0))))
(define h2 (list (cons 1 (list 1 0)) (cons -1 (list 0 1))))
(display (groebner2-agrees? (list h1 h2))) (newline)
(define e1 (list (cons 1 (list 1 0 0)) (cons -1 (list 0 0 0))))
(define e2 (list (cons 1 (list 0 1 0)) (cons -2 (list 0 0 0))))
(define e3 (list (cons 1 (list 0 0 1)) (cons -3 (list 0 0 0))))
(display (groebner2-agrees? (list e1 e2 e3))) (newline)
