(import "cas/radmember.lisp")
(define x (list (cons 1 (list 1))))
(define x2 (list (cons 1 (list 2))))
(define x3 (list (cons 1 (list 3))))
(display (rad-member? x (list x2) 1)) (display " ") (display (rad-member? x (list x3) 1)) (newline)
(display (in-ideal? x (groebner (list x2)))) (newline)
(define xm1 (list (cons 1 (list 1)) (cons -1 (list 0))))
(define xm1sq (list (cons 1 (list 2)) (cons -2 (list 1)) (cons 1 (list 0))))
(display (rad-member? xm1 (list xm1sq) 1)) (display " ") (display (rad-member? x (list xm1sq) 1)) (newline)
(define x2b (list (cons 1 (list 2 0))))
(define y (list (cons 1 (list 0 1))))
(display (rad-member? x2b (list x2b y) 2)) (newline)
