(import "cas/radideal.lisp")
(define x2 (list (cons 1 (list 2))))
(define x (list (cons 1 (list 1))))
(display (ri-in-radical? (list x2) x 1)) (display " ") (display (ri-in-ideal? (list x2) x 1)) (newline)
(display (ri-in-radical? (list (list (cons 1 (list 3)))) (list (cons 1 (list 2))) 1)) (newline)
(define f1 (list (cons 1 (list 2 0)) (cons 1 (list 0 2)) (cons -1 (list 0 0))))
(define f2 (list (cons 1 (list 1 0)) (cons -1 (list 0 1))))
(display (ri-in-radical? (list f1 f2) (list (cons 1 (list 1 0)) (cons -1 (list 0 1))) 2)) (newline)
(display (ri-in-radical? (list f1 f2) (list (cons 1 (list 1 0)) (cons 1 (list 0 1))) 2)) (newline)
(display (ri-in-radical? (list x2) (list (cons 1 (list 1)) (cons -1 (list 0))) 1)) (newline)
(display (ri-in-radical? (list (list (cons 1 (list 1))) (list (cons 1 (list 1)) (cons -1 (list 0)))) (list (cons 1 (list 0))) 1)) (newline)
