(import "cas/cadtower.lisp")
(define f2 (list (list 0 -1) (list) (list 1)))
(define f3 (list (list 0 -1) (list) (list 1)))
(define p (cadtower-make (list -2 0 1) 1 2 (list (list f2 1 (/ 3 2)) (list f3 1 (/ 6 5)))))
(display (cadtower-height p)) (newline)
(display (cadtower-vanishes? (list (list 0 -2) (list) (list 2)) p)) (newline)
(display (cadtower-top-sign (list (list) (list 1)) p)) (display " ") (display (cadtower-top-sign (list (list -1) (list 1)) p)) (display " ") (display (cadtower-top-sign (list (list (/ -6 5)) (list 1)) p)) (newline)
(display (cadtower-vanishes? (list (list) (list 1)) p)) (newline)
(define f2b (list (list 0 -1) (list) (list 1)))
(define ym1b (list (list -1) (list 1)))
(define ym2b (list (list -2) (list 1)))
(define xmyb (list (list 0 1) (list -1)))
(display (cadtower-exists-chain (list -2 0 1) (list (list 1 2)) (list (list f2b 1 (/ 3 2))) (list (cons (quote pos) ym1b)))) (display " ") (display (cadtower-exists-chain (list -2 0 1) (list (list 1 2)) (list (list f2b 1 (/ 3 2))) (list (cons (quote pos) ym2b)))) (display " ") (display (cadtower-exists-chain (list -2 0 1) (list (list 1 2)) (list (list f2b 1 (/ 3 2))) (list (cons (quote pos) xmyb)))) (newline)
