(import "cas/rischint1.lisp")
(define b (rat-from-poly (list 0 1)))
(define e1 (ri1-integrate-exp b (list (rat-zero) (rat-one))))
(display e1) (newline)
(display (ri1-certify-exp b (list (rat-zero) (rat-one)) (car (cdr e1)))) (newline)
(define e2 (ri1-integrate-exp b (list (rat-zero) (rat-from-poly (list 0 1)))))
(display (ri1-certify-exp b (list (rat-zero) (rat-from-poly (list 0 1))) (car (cdr e2)))) (newline)
(display (ri1-integrate-exp b (list (rat-zero) (rat-make (list 1) (list 0 1))))) (newline)
(define l1 (ri1-integrate-log (rat-make (list 1) (list 0 1)) (list (rat-zero) (rat-one))))
(display l1) (newline)
(display (ri1-certify-log (rat-make (list 1) (list 0 1)) (list (rat-zero) (rat-one)) (car (cdr l1)))) (newline)
(define l2 (ri1-integrate-log (rat-make (list 1) (list 0 1)) (list (rat-zero) (rat-zero) (rat-one))))
(display l2) (newline)
(display (ri1-certify-log (rat-make (list 1) (list 0 1)) (list (rat-zero) (rat-zero) (rat-one)) (car (cdr l2)))) (newline)
