(import "cas/elliptic3residue.lisp")
(define a1 (rat-make (list 0 1) (list -1 0 1)))
(display (e3r-residues-2a a1)) (newline)
(display (e3r-all-integer-residues? a1)) (display " ") (display (e3r-residue-at a1 1)) (newline)
(display (e3r-third-kind-possible? (list a1 (rat-make (list) (list 1))))) (newline)
(define a3 (rat-make (list 1) (list -2 1)))
(display (e3r-all-integer-residues? a3)) (newline)
(define a2 (rat-make (list (/ 1 4)) (list -1 1)))
(display (e3r-residues-2a a2)) (display " ") (display (e3r-all-integer-residues? a2)) (newline)
(display (e3r-all-integer-residues? (rat-make (list) (list 1)))) (newline)
