(import "cas/contfrac.lisp")
(display (cf->string (cf-rational (/ 415 93)))) (newline)
(display (cf->string (cf-rational (/ 355 113)))) (newline)
(display (cf-rational (/ 22 7))) (newline)
(display (cf->rational (list 4 2 6 7))) (newline)
(display (cf-sqrt->string 7)) (newline)
(display (cf-sqrt->string 13)) (newline)
(display (list (pell-solution 2) (pell-value 2))) (newline)
(display (list (pell-solution 7) (pell-value 7))) (newline)
(display (pell-solution 61)) (newline)
(display (list (cf-sqrt-ok? 991) (pell-value 991))) (newline)
