(import "cas/rqe.lisp")
(define (cn c n) (if (= n 0) c (list (cn c (- n 1)))))
(display (rqe-decide 1 (quote exists) (rqe-eq (list -2 0 1)))) (display " ") (display (rqe-decide 1 (quote forall) (rqe-gt (list 1 0 1)))) (display " ") (display (rqe-decide 1 (quote forall) (rqe-ge (list -1 0 1)))) (newline)
(define parab (list (list 0 -1) (list) (list 1)))
(define circle (list (list -1 0 1) (list) (list 1)))
(display (rqe-decide 2 (quote exists) (list (quote and) (rqe-eq parab) (rqe-eq (list (list -2 1)))))) (display " ") (display (rqe-decide 2 (quote exists) (rqe-lt circle))) (display " ") (display (rqe-decide 2 (quote forall) (rqe-ge (list (list 0 0 1) (list) (list 1))))) (newline)
(define ball3 (list (list (list -1 0 1) (list) (list 1)) (cn 0 2) (cn 1 2)))
(define sph (list (list (list -1 0 1) (list) (list 1)) (cn 0 2) (cn 1 2)))
(define xy (list (list (list) (list -1)) (cn 1 2)))
(define yz (list (list (list 0 -1) (list 1))))
(define xc (list (list) (list (list 1))))
(display (rqe-decide 3 (quote exists) (rqe-lt ball3))) (display " ") (display (rqe-decide 3 (quote exists) (list (quote and) (rqe-eq sph) (rqe-eq xy) (rqe-eq yz) (rqe-gt xc)))) (newline)
