(import "cas/algresn.lisp")
(define LOG (list 'log)) (define EXP (list 'exp (list 0 1)))
(define dc (list (rat-from-poly (list -2)) (rat-zero) (rat-zero) (rat-one)))
(define ac (list (rat-make (list 6) (list 0 1))))
(display (car (int-prim-rational-algn ac dc LOG))) (newline)
(display (int-prim-rational-algn-verify ac dc LOG)) (newline)
(define de (list (rat-from-poly (list -2)) (rat-zero) (rat-zero) (rat-one)))
(define ae (list (rat-zero) (rat-zero) (rat-from-poly (list 6))))
(display (int-prim-rational-algn-verify ae de EXP)) (newline)
(define dq (list (rat-from-poly (list -2)) (rat-zero) (rat-one)))
(define aq (list (rat-make (list 1) (list 0 1))))
(display (int-prim-rational-algn-verify aq dq LOG)) (newline)
