(import "cas/cadproj.lisp")
(define (trim p) (cond ((null? p) (quote ())) ((= (car (rv p)) 0) (trim (fr p))) (else p)))
(define (rv l) (rva l (quote ()))) (define (rva l a) (if (null? l) a (rva (cdr l) (cons (car l) a))))
(define (fr l) (if (null? (cdr l)) (quote ()) (cons (car l) (fr (cdr l)))))
(define parab (list (list 0 -1) (list) (list 1)))
(define line (list (list 0 -1) (list 1)))
(display (trim (cad-resultant parab line))) (newline)
(display (trim (cad-discriminant parab))) (newline)
(define circle (list (list -1 0 1) (list) (list 1)))
(define yaxis (list (list) (list 1)))
(display (trim (cad-resultant circle yaxis))) (newline)
(display (cad-projection-roots (list circle))) (newline)
(display (cad-bivar-deg parab)) (display " ") (display (cad-bivar-deg line)) (newline)
