(import "cas/rischintn.lisp")
(define t1a (list (list (quote alg) 2 (rat-from-poly (list 0 1)))))
(define f1 (list (rat-zero) (rat-make (list 1) (list 0 2))))
(define r1 (te-integrate t1a 1 f1))
(display (te-int-certify t1a 1 f1 (car (cdr r1)))) (newline)
(define f2 (list (rat-one) (rat-make (list 1) (list 0 2))))
(define r2 (te-integrate t1a 1 f2))
(display (te-int-certify t1a 1 f2 (car (cdr r2)))) (newline)
(define f3 (list (rat-zero) (rat-make (list 1) (list 0 0 1))))
(define r3 (te-integrate t1a 1 f3))
(display (car (cdr r3))) (newline)
(display (te-int-certify t1a 1 f3 (car (cdr r3)))) (newline)
(display (if (te-int-certify t1a 1 f1 (list (rat-from-poly (list 0 1)) (rat-zero))) (quote bad) (quote good))) (newline)
