(import "cas/liouvillerat.lisp")
(display (lr-decide (list) (list 1))) (newline)
(display (lr-decide (list) (list 0 1))) (newline)
(define d3 (lr-decide (list) (list 1 -1)))
(display d3) (newline)
(display (lr-certify (list) (list 1 -1) (lr-nth d3 1) (lr-nth d3 2))) (newline)
(define d4 (lr-decide (list 0 1) (list)))
(display d4) (newline)
(display (lr-certify (list 0 1) (list) (lr-nth d4 1) (lr-nth d4 2))) (newline)
(define d5 (lr-decide (list) (list 0 1 -2)))
(display (lr-certify (list) (list 0 1 -2) (lr-nth d5 1) (lr-nth d5 2))) (newline)
