(import "cas/tower2ff.lisp")
(define MEXP (list 'exp (list 0 1)))
(define TH1 (list (list (rat-zero) (rat-one)) (list (rat-one))))
(define Dth2 (list (list (rat-zero) (rat-one)) (list (rat-one) (rat-one))))
(define (clear h2) (ff-clear-poly h2 (ff-denlcm h2 (rf-one))))
(define fa (list (k1-zero) (k1-neg (k1-mul TH1 TH1)) (k1-zero) (k1-one)))
(define ga (list TH1 (k1-zero) (k1-one)))
(display (tr-equal? (tr-reduce (h2-resultant fa ga)) (tr-reduce (h2-resultant-ff (clear fa) (clear ga))))) (newline)
(define v1 (list (k1-neg TH1) (k1-one))) (define v2 (list (k1-zero) (k1-one))) (define v3 (list TH1 (k1-one)))
(define D (h2-mul (h2-mul v1 v2) v3))
(define A (h2-add (h2-add
            (h2-cscale (k1-from-int 1) (h2-mul (t2-deriv v1 Dth2 MEXP) (h2-mul v2 v3)))
            (h2-cscale (k1-from-int 2) (h2-mul (t2-deriv v2 Dth2 MEXP) (h2-mul v1 v3))))
            (h2-cscale (k1-from-int 3) (h2-mul (t2-deriv v3 Dth2 MEXP) (h2-mul v1 v2)))))
(define lg (h2rt-logpart-ff A D Dth2 MEXP))
(display (car lg)) (newline)
(display (map car (car (cdr lg)))) (newline)
(display (h2tr-equal? (h2rt-logderiv (car (cdr lg)) Dth2 MEXP (h2tr-zero)) (list A D))) (newline)
