(import "cas/itexpsolve.lisp")
(define (mono c v) (cons (rat-from-poly (list c)) v))
(define B1 (ie-deriv 2 (list (mono 1 (list 1 0)))))
(display (ie-certify 2 (ies-solve 2 B1) B1)) (newline)
(define B2 (ie-deriv 2 (list (mono 1 (list 1 0)) (mono 1 (list 0 1)))))
(display (ies-vecs (ies-solve 2 B2))) (newline)
(display (ie-certify 2 (ies-solve 2 B2) B2)) (newline)
(define B3 (ie-deriv 2 (list (mono 1 (list 1 1)))))
(display (ie-certify 2 (ies-solve 2 B3) B3)) (newline)
(define B4 (ie-deriv 3 (list (mono 1 (list 0 0 1)))))
(display (ie-certify 3 (ies-solve 3 B4) B4)) (newline)
