(import "cas/rischratmono.lisp")
(define r1 (ratmono-exp-integrate (list 1) (list 1 1)))
(display (ratmono-exp-certify (list 1) (list 1 1) r1)) (newline)
(define r2 (ratmono-exp-integrate (list 0 1) (list 1 1)))
(display (ratmono-exp-certify (list 0 1) (list 1 1) r2)) (newline)
(define r3 (ratmono-exp-integrate (list 1) (list -1 1)))
(display (ratmono-exp-certify (list 1) (list -1 1) r3)) (newline)
(define r4 (ratmono-exp-integrate (list 1) (list 1 0 1)))
(display (ratmono-exp-certify (list 1) (list 1 0 1) r4)) (newline)
