(import "cas/tower2expfull.lisp")
(define MEXP (list 'exp (list 0 1)))
(define TH1 (list (list (rat-zero) (rat-one)) (list (rat-one))))
(define UP TH1)
(define v (list (k1-neg TH1) (k1-one)))
(define dv (t2e-deriv v UP MEXP))
(define r1 (t2ef-newlog dv v UP MEXP))
(display (car r1)) (display " ") (display (equal? (car (cdr r1)) (k1-one))) (newline)
(display (t2ef-newlog-verify dv v UP MEXP)) (newline)
(define As2 (h2-cscale (k1-iscale 2 (k1-one)) dv))
(display (equal? (car (cdr (t2ef-newlog As2 v UP MEXP))) (k1-iscale 2 (k1-one)))) (display " ") (display (t2ef-newlog-verify As2 v UP MEXP)) (newline)
(define notlog (list (k1-zero) (k1-one)))
(display (t2ef-newlog notlog v UP MEXP)) (newline)
(display (car (t2ef-proper dv v UP MEXP))) (display " ") (display (t2ef-proper notlog v UP MEXP)) (newline)
