(import "cas/sternbrocot.lisp")
(define (all? l) (cond ((null? l) #t) ((car l) (all? (cdr l))) (else #f)))
(display (path->string (sb-path (/ 3 2)))) (newline)
(display (path->string (sb-path (/ 2 5)))) (newline)
(display (sb-runs (/ 355 113))) (newline)
(display (sb-runs (/ 22 7))) (newline)
(display (sb-from-path (list 'R 'L))) (newline)
(display (level-rationals 3)) (newline)
(display (list (sb-roundtrip-ok? (/ 355 113)) (sb-farey-ok? (/ 355 113)) (sb-farey-ok? (/ 8 13)))) (newline)
(display (map level-distinct-ok? (list 1 2 3 4 5 6 7))) (newline)
