(import "cas/tower2primrat.lisp")
(define EXP1 (list 'exp (list 0 1)))
(define Dth2 (list (list (rat-zero) (rat-one)) (list (rat-one) (rat-one))))
(define A3 (list (k1-iscale 2 Dth2) (k1-iscale -10 Dth2) (k1-iscale 6 Dth2)))
(define D3 (list (k1-from-int 0) (k1-from-int 2) (k1-from-int -3) (k1-from-int 1)))
(display (int-h2-prim-rat-elementary? A3 D3 Dth2 EXP1)) (newline)
(display (int-h2-prim-rat-verify A3 D3 Dth2 EXP1)) (newline)
(define D4 (list (k1-from-int 0) (k1-from-int -6) (k1-from-int 11) (k1-from-int -6) (k1-from-int 1)))
(define A4 (list (k1-iscale -6 Dth2) (k1-iscale 22 Dth2) (k1-iscale -18 Dth2) (k1-iscale 4 Dth2)))
(display (int-h2-prim-rat-verify A4 D4 Dth2 EXP1)) (newline)
