(import "cas/hyperjactor.lisp")
(define f (list 1 0 0 0 0 1))
(display (hjt-order f (hj-identity) 20)) (newline)
(display (hjt-order f (hj-point -1 0) 20)) (newline)
(display (hjt-order f (hj-point 0 1) 30)) (newline)
(display (hjt-third-kind-decision f -1 0 20)) (newline)
(display (hjt-third-kind-decision f 0 1 30)) (newline)
(display (hjt-order f (hj-point 0 1) 2)) (newline)
(display (car (hjt-third-kind-decision f 0 1 2))) (newline)
(define f2 (list 0 -1 0 0 0 1))
(display (hjt-order f2 (hj-point 1 0) 20)) (newline)
