(import "cas/algtower2log.lisp")
(define e1 (t2-add (t2-one) (t2-z)))
(display (t2-equal? (t2-mul e1 (t2l-inv e1)) (t2-one))) (newline)
(display (t2l-cleared-cert e1)) (display " ") (display (t2l-verify-log e1)) (newline)
(display (rat-equal? (af-u (t2-a (t2l-logderiv (t2-z)))) (rat-make (list 1) (list 0 4)))) (newline)
(display (rat-equal? (af-u (t2-a (t2l-logderiv (t2-y)))) (rat-make (list 1) (list 0 2)))) (newline)
(display (t2l-cleared-cert (t2-z))) (newline)
(display (t2l-is-logderiv? e1 (t2-z))) (display " ") (display (t2l-is-logderiv? e1 (t2l-logderiv e1))) (newline)
(define exz (t2-add (t2-from-rat (rat-from-poly (list 0 1))) (t2-z)))
(display (t2-equal? (t2-mul exz (t2l-inv exz)) (t2-one))) (display " ") (display (t2l-cleared-cert exz)) (newline)
