(import "cas/pade.lisp")
(import "cas/series.lisp")
(define expc (list 1 1 (/ 1 2) (/ 1 6) (/ 1 24)))
(display (pade->string (pade-approx expc 2 2) "x")) (newline)
(display (pade->string (pade-approx (list 1 1 1) 1 1) "x")) (newline)
(display (pade->string (pade-approx (list 1 2 4) 1 1) "x")) (newline)
(define ratser (ser-trunc (ser-mul (list 1 1) (ser-inverse (list 1 -1 1) 6) 6) 6))
(display (pade->string (pade-approx ratser 2 2) "x")) (newline)
(display (pade->string (pade-approx (list 0 1 (/ -1 2) (/ 1 3) (/ -1 4)) 2 2) "x")) (newline)
(display (pade-ok? expc (car (pade-approx expc 2 2)) (car (cdr (pade-approx expc 2 2))) 2 2)) (newline)
