(import "cas/rischintn.lisp")
(define t1 (list (list (quote exp) (rat-from-poly (list 0 1)))))
(define r1 (te-integrate t1 1 (list (rat-zero) (rat-one))))
(display (te-int-certify t1 1 (list (rat-zero) (rat-one)) (car (cdr r1)))) (newline)
(define r2 (te-integrate t1 1 (list (rat-zero) (rat-from-poly (list 0 1)))))
(display (te-int-certify t1 1 (list (rat-zero) (rat-from-poly (list 0 1))) (car (cdr r2)))) (newline)
(display (car (te-integrate t1 1 (list (rat-zero) (rat-make (list 1) (list 0 1)))))) (newline)
(define t1log (list (list (quote log) (rat-from-poly (list 0 1)))))
(define r4 (te-integrate t1log 1 (list (rat-zero) (rat-one))))
(display (te-int-certify t1log 1 (list (rat-zero) (rat-one)) (car (cdr r4)))) (newline)
(define t2log (list (list (quote exp) (rat-from-poly (list 0 1))) (list (quote log) (list (rat-one) (rat-one)))))
(define integ2 (list (te-zero 1) (te-one 1)))
(define r5 (te-integrate t2log 2 integ2))
(display (car r5)) (newline)
(display (if (equal? (car r5) (quote elementary)) (te-int-certify t2log 2 integ2 (car (cdr r5))) (quote na))) (newline)
(define t2 (list (list (quote exp) (rat-from-poly (list 0 1))) (list (quote exp) (list (rat-zero) (rat-one)))))
(display (car (te-integrate t2 2 (list (te-zero 1) (te-one 1))))) (newline)
