(import "cas/polycf.lisp")
(display (poly-norm (pcf-polypart (list 1 0 0 0 0 0 1)))) (newline)
(display (pcf-polypart (list 1 0 0 0 0 1))) (newline)
(define f1 (list 1 0 0 0 0 0 1))
(display (pcf-period f1 30)) (newline)
(define u1 (pcf-unit-verified f1 30))
(display (list (poly-norm (car u1)) (poly-norm (car (cdr u1))))) (newline)
(display (poly-norm (pcf-unit-norm f1 (car u1) (car (cdr u1))))) (newline)
(display (pcf-certify-unit f1 30)) (newline)
(display (pcf-certify-unit (list 2 0 1 0 2 0 1) 30)) (newline)
(display (pcf-certify-unit (list 1 0 1) 30)) (newline)
(display (pcf-unit-verified (list 1 0 1 0 0 0 1) 30)) (newline)
(display (pcf-period (list 0 1 0 0 0 0 1) 30)) (newline)
(display (pcf-certify-unit (list 0 1 0 0 0 0 1) 30)) (newline)
(define u3 (pcf-unit-verified (list 0 1 0 0 0 0 1) 30))
(display (list (poly-norm (car u3)) (poly-norm (car (cdr u3))))) (newline)
(display (poly-norm (pcf-unit-norm (list 0 1 0 0 0 0 1) (car u3) (car (cdr u3))))) (newline)
