(import "cas/rischtoweralgn.lisp")
(import "cas/rischintn.lisp")
(define t1c (list (list (quote alg) 3 (rat-from-poly (list 0 1)))))
(define th (list (rat-zero) (rat-one) (rat-zero)))
(define th2 (list (rat-zero) (rat-zero) (rat-one)))
(display (rat-equal? (tn2-coeff 1 (tean-mul t1c 1 3 th th2) 0) (rat-from-poly (list 0 1)))) (newline)
(display (rat-equal? (tn2-coeff 1 (tean-mul t1c 1 3 th2 th2) 1) (rat-from-poly (list 0 1)))) (newline)
(display (rat-equal? (tn2-coeff 1 (tean-pow t1c 1 3 th 3) 0) (rat-from-poly (list 0 1)))) (newline)
(define f (list (rat-zero) (rat-make (list 1) (list 0 3)) (rat-zero)))
(define r (te-integrate t1c 1 f))
(display (te-int-certify t1c 1 f (car (cdr r)))) (newline)
