(import "cas/rischcrdeh.lisp")
(define t1 (list (list (quote exp) (rat-from-poly (list 0 1)))))
(define t2 (list (list (quote exp) (rat-from-poly (list 0 1))) (list (quote exp) (list (rat-zero) (rat-one)))))
(define f2 (list (te-zero 1) (list (rat-zero) (rat-one))))
(define r (te-crdeh-integrate t2 2 f2))
(display (car r)) (newline)
(display (if (equal? (car r) (quote elementary)) (te-crde-certify t2 2 (te-zero 2) f2 (car (cdr r))) (quote na))) (newline)
(define c (te-crdeh-solve t1 1 (list (rat-zero) (rat-one)) (list (rat-zero) (rat-one))))
(display c) (newline)
(display (car (te-crdeh-integrate t2 2 (list (te-zero 1) (te-one 1))))) (newline)
(display (car (te-crdeh-integrate t1 1 (list (rat-zero) (rat-make (list 1) (list 0 1)))))) (newline)
