(import "cas/senorm.lisp")
(define g (list 1 0 0 1))
(define y (sf-y 3))
(display (sn-norm g 3 y)) (newline)
(define u (list (rat-from-poly (list 0 1)) (rat-one) (rat-from-poly (list 2))))
(display (sn-norm g 3 u)) (newline)
(display (sn-ubar g 3 y)) (newline)
(display (sf-product g 3 y (sn-inverse g 3 y))) (newline)
(define u2 (list (rat-from-poly (list 0 1)) (rat-one) (rat-zero)))
(display (sn-logderiv-check g 3 u2)) (display " ") (display (sn-logderiv-check g 3 u)) (newline)
(define g2 (list 1 0 1))
(display (sn-norm g2 2 (list (rat-from-poly (list 0 1)) (rat-one)))) (newline)
