(import "cas/hyperint.lisp")
(define f (list 1 0 0 0 0 1))
(display (hi-genus f)) (newline)
(define P (list 0 0 0 0 (/ 5 2)))
(display (car (hi-integrate f 'second P))) (display " ") (display (hi-decides? f 'second P)) (newline)
(display (car (hi-integrate f 'second (list 1)))) (display " ") (display (hi-decides? f 'second (list 1))) (newline)
(define D (ht-norm f (list 0 1)))
(display (car (hi-integrate f 'third D))) (display " ") (display (car (cdr (hi-integrate f 'third D)))) (display " ") (display (hi-decides? f 'third D)) (newline)
(display (car (hi-integrate f 'third (list 1 1 1)))) (newline)
(define fe (list 1 0 0 1))
(display (hi-genus fe)) (display " ") (display (car (hi-integrate fe 'second (list 0 0 (/ 3 2))))) (display " ") (display (car (hi-integrate fe 'third (ht-norm fe (list 0 1))))) (newline)
