(import "cas/mixedexp.lisp")
(define px (rat-from-poly (list 0 1)))
(define hp (rat-from-poly (list 1)))
(define Ay (af-make (rat-zero) (rat-from-poly (list 1))))
(define B (mx-rhs px hp Ay))
(display B) (newline)
(display (mx-certify px hp Ay B)) (newline)
(display (mx-solve-sqrt hp (af-u B) (af-v B) 0 0)) (newline)
(display (mx-integrate-sqrt hp B 2)) (newline)
(define Axy (af-make (rat-from-poly (list 0 1)) (rat-from-poly (list 1))))
(define B2 (mx-rhs px hp Axy))
(display (mx-solve-sqrt hp (af-u B2) (af-v B2) 1 0)) (newline)
(define Ahi (af-make (rat-from-poly (list 0 0 1)) (rat-from-poly (list 1))))
(define B3 (mx-rhs px hp Ahi))
(display (mx-solve-sqrt hp (af-u B3) (af-v B3) 0 0)) (display " ") (display (mx-solve-sqrt hp (af-u B3) (af-v B3) 2 0)) (newline)
