(import "cas/linrec.lisp")
(display (crec->string (crec-solve (list 5 -6) (list 0 1)))) (newline)
(display (crec->string (crec-solve (list 2 -1) (list 1 3)))) (newline)
(display (crec->string (crec-solve (list 3) (list 2)))) (newline)
(display (crec->string (crec-solve (list 1 2) (list 2 1)))) (newline)
(display (crec->string (crec-solve (list 6 -11 6) (list 0 1 5)))) (newline)
(display (crec->string (crec-solve (list 1 1) (list 0 1)))) (newline)
(display (crec-terms (list 1 1) (list 0 1) 9)) (newline)
(display (crec-ok? (list 5 -6) (list 0 1) (crec-solve (list 5 -6) (list 0 1)))) (newline)
