(import "cas/elliptic3split.lisp")
(display (esp-trim (esp-poly-sqrt (list 0 0 1)))) (newline)
(display (esp-poly-sqrt (list 1 2 1))) (newline)
(display (esp-poly-sqrt (list 1 0 2 0 1))) (newline)
(display (esp-is-square? (list 1 0 1))) (display " ") (display (esp-is-square? (list 0 0 0 1))) (newline)
(define q (list 1 0 1))
(display (esp-split-const (list -1) q 1)) (newline)
(display (esp-verify (list -1) q (list 0 1) 1)) (newline)
(display (esp-recover-g (list -1) q 1)) (newline)
(display (esp-verify (list -1 0 -1 0 1) q (list 0 0 1) 1)) (newline)
(display (esp-recover-g (list 1) q 1)) (newline)
(display (esp-verify (list -1) q (list 1 1) 1)) (newline)
