(import "cas/algfunc.lisp")
(define (cert-lin a b p) (let ((r (int-sqrt-linear a b p)))
  (af-certify p (car r) (car (cdr r)) (car (cdr (cdr r))) (int-sqrt-linear-integrand a b p))))
(define (cert-quad p) (let ((r (int-sqrt-quad p)))
  (af-certify p (car r) (car (cdr r)) (car (cdr (cdr r))) (int-sqrt-quad-integrand p))))
(define P1 (rat-from-poly (list 1 0 1)))
(define P2 (rat-from-poly (list 5 2 1)))
(display (cert-lin 0 1 P1)) (display " ") (display (cert-lin 1 0 P1)) (display " ") (display (cert-lin 2 3 P1)) (newline)
(display (cert-lin 0 1 P2)) (display " ") (display (cert-lin 5 -4 P2)) (newline)
(display (cert-quad P1)) (display " ") (display (cert-quad P2)) (newline)
