(import "cas/lucas.lisp")
(define (all? l) (cond ((null? l) #t) ((car l) (all? (cdr l))) (else #f)))
(display (mersenne-prime-exponents 2 40)) (newline)
(display (list (mersenne-prime-ll? 13) (mersenne-prime-ll? 11) (mersenne-prime-ll? 31) (mersenne-prime-ll? 127))) (newline)
(display (mersenne 127)) (newline)
(display (all? (map lucas-lehmer-agrees? (list 3 5 7 11 13 17 19 23 29 31)))) (newline)
(display (map fib (range 10 15))) (newline)
(display (map lucasnum (range 0 8))) (newline)
(display (all? (map (lambda (n) (lucas-identity-ok? 1 -1 n)) (range 1 12)))) (newline)
(display (all? (map (lambda (n) (lucas-identity-ok? 3 2 n)) (range 1 10)))) (newline)
