(import "cas/elliptic3solve.lisp")
(define q1 (rat-from-poly (list -1 0 1)))
(define om1 (e3-logderiv q1 (af-make (rat-from-poly (list 0 1)) (rat-one))))
(define r1 (e3s-search q1 om1 1))
(display (car r1)) (display " ") (display (e3-certify q1 (car (cdr r1)) om1)) (newline)
(define q3 (rat-from-poly (list 1 0 0 1)))
(define om3 (e3-logderiv q3 (af-make (rat-from-poly (list 0 1)) (rat-one))))
(define r3 (e3s-search q3 om3 1))
(display (car r3)) (display " ") (display (e3-certify q3 (car (cdr r3)) om3)) (newline)
(display (car (e3s-integrate q3 om3 1))) (newline)
(display (car (e3s-search q3 (af-make (rat-zero) (rat-make (list 1) (list 1 0 0 1))) 1))) (newline)
