(import "cas/mixedlog.lisp")
(define p (rat-from-poly (list 0 1)))
(define tp (rat-make (list 1) (list 0 1)))
(define y (af-make (rat-zero) (rat-from-poly (list 1))))
(define Q (list (af-zero) y))
(define B (ml-deriv p tp Q))
(display B) (newline)
(display (ml-certify p tp Q B)) (newline)
(display (ml-solve-sqrt tp B 2 1)) (newline)
(display (ml-integrate-sqrt tp B 2)) (newline)
(define Qx (list (af-zero) (af-from-rat (rat-from-poly (list 0 1)))))
(define Bx (ml-deriv p tp Qx))
(display (ml-solve-sqrt tp Bx 2 1)) (newline)
(define Qt2 (list (af-zero) (af-zero) (af-from-rat (rat-make (list 1) (list 2)))))
(define Bt2 (ml-deriv p tp Qt2))
(display (ml-solve-sqrt tp Bt2 2 0)) (newline)
