(import "cas/inetmodal.lisp")
(display (itm-readback-is? (itm-box (itm-sort 0)) (quote (box (U 0))))) (newline)
(define delta_x (itm-delta (list (list (quote x) 0))))
(define gamma_y (itm-gamma (list (list (quote y) 0))))
(define r1 (infer-modal (context) (context) (box (U 0))))
(display (itm-accepted? r1)) (newline)
(define r2 (infer-modal delta_x (context) (box (quote x))))
(display (itm-accepted? r2)) (newline)
(define r3 (infer-modal delta_x (context) (box (box (box (quote x))))))
(display (itm-accepted? r3)) (newline)
(define rr (infer-modal (context) gamma_y (box (quote y))))
(display (itm-rejected? rr)) (newline)
(display (cond ((and (itm-accepted? r2) (itm-rejected? rr)) #t) (else #f))) (newline)
