(import "cas/polysolve3.lisp")
(display (ps3-named-real-roots (list -2 0 1))) (newline)
(display (ps3-num-complex (list -2 0 1))) (newline)
(define r2 (ps3-named-real-roots (list -2 0 1)))
(display (ps3-verify-root (list -2 0 1) (car r2))) (display " ") (display (ps3-verify-root (list -2 0 1) (car (cdr r2)))) (newline)
(display (ps3-named-real-roots (list 2 -2 -1 1))) (newline)
(display (ps3-irrational-factor (list 2 -2 -1 1))) (newline)
(display (ps3-named-real-roots (list 1 0 1))) (display " ") (display (ps3-num-complex (list 1 0 1))) (newline)
(display (ps3-named-real-roots (list 2 -3 1))) (newline)
