(import "cas/vanhoeijmb.lisp")
(define fn (list 0 0 1 1))
(display (mbc-trace fn (list 0) (list 1) (list 0 1))) (newline)
(display (mbc-norm fn (list 0) (list 1) (list 0 1))) (newline)
(display (mbc-is-integral? fn (list 0) (list 1) (list 0 1))) (newline)
(display (mbc-minpoly fn (list 0) (list 1) (list 0 1))) (newline)
(display (mbc-certify fn (list 0) (list 1) (list 0 1))) (newline)
(display (mbc-is-integral? fn (list 0) (list 1) (list 0 0 1))) (newline)
(define fn2 (poly-mul (poly-mul (list 0 1) (list 0 1)) (poly-mul (poly-mul (list -1 1) (list -1 1)) (list 1 1))))
(define dd (poly-mul (list 0 1) (list -1 1)))
(display (mbc-is-integral? fn2 (list 0) (list 1) dd)) (display " ") (display (mbc-certify fn2 (list 0) (list 1) dd)) (newline)
(display (mbc-is-integral? (list 0 2 -3 1) (list 0) (list 1) (list 1))) (display " ") (display (mbc-is-integral? (list 0 2 -3 1) (list 0) (list 1) (list -1 1))) (newline)
