(import "cas/cadcomplete.lisp")
(define (cn c n) (if (= n 0) c (list (cn c (- n 1)))))
(define sph (list (list (list -1 0 1) (list) (list 1)) (cn 0 2) (cn 1 2)))
(define zz (list (list (list 0 1))))
(define xx (list (list) (list (list 1))))
(define yy (list (list (list) (list 1))))
(display (cadcomplete-exists (cons (quote neg) sph) 3)) (newline)
(display (cadcomplete-exists (list (quote and) (cons (quote zero) sph) (cons (quote zero) zz) (cons (quote pos) xx) (cons (quote pos) yy)) 3)) (newline)
(display (cadcomplete-exists (list (quote and) (cons (quote zero) sph) (cons (quote zero) xx) (cons (quote zero) yy) (cons (quote pos) zz)) 3)) (newline)
