(import "cas/msqfree.lisp")
(define x+y (list (list 0 1) (list 1)))
(define x-y (list (list 0 -1) (list 1)))
(define x-1 (list (list -1) (list 1)))
(display (sqfree->string (sqfree (xy-mul (xy-mul x+y x+y) x-1)))) (newline)
(display (sqfree->string (sqfree (xy-mul (xy-mul x+y x+y) x+y)))) (newline)
(display (sqfree->string (sqfree (xy-mul x-y x+y)))) (newline)
(display (sqfree->string (sqfree (xy-mul (xy-mul x-1 x-1) (xy-mul (xy-mul x+y x+y) x+y))))) (newline)
(display (sqfree-ok? (xy-mul (xy-mul x+y x+y) x-1) (sqfree (xy-mul (xy-mul x+y x+y) x-1)))) (newline)
