(import "cas/cyclic.lisp")
(define g (list 1 1 0 1)) (define n 7)
(display (cyc-xn-1 7)) (newline)
(display (list (cyc-generates-ok? g n) (cyc-k n g))) (newline)
(define c (cyc-encode (list 1 0 0 0) g n))
(display c) (newline)
(display (cyc-shift c n)) (newline)
(display (list (cyc-codeword? c g) (cyc-shift-all-ok? (list 1 0 1 1) g n) (cyc-detects-ok? (list 1 0 1 1) g n (list 2)) (cyc-detects-ok? (list 1 0 1 1) g n (list 1 5)))) (newline)
(define gp (list 1 1))
(display (list (cyc-generates-ok? gp 6) (cyc-k 6 gp) (cyc-shift-all-ok? (list 1 0 1 1 0) gp 6))) (newline)
