(import "cas/groebner4.lisp")
(define f1 (list (cons 1 (list 2 0)) (cons 1 (list 0 2)) (cons -1 (list 0 0))))
(define f2 (list (cons 1 (list 1 0)) (cons -1 (list 0 1))))
(define R (gb4-reduced (list f1 f2)))
(display R) (newline)
(display (gb4-is-reduced? R)) (display " ") (display (groebner-ok? R)) (display " ") (display (gb4-set-equal? (gb4-reduce R) R)) (newline)
(display (gb4-is-reduced? (groebner (list f1 f2)))) (newline)
(define h1 (list (cons 1 (list 1 0)) (cons -1 (list 0 1))))
(define h2 (list (cons 2 (list 2 0)) (cons -1 (list 0 0))))
(display (gb4-ideal-equal? (list f2 f1) (list h1 h2))) (newline)
(define h3 (list (cons 1 (list 2 0)) (cons 1 (list 0 2)) (cons -4 (list 0 0))))
(display (gb4-ideal-equal? (list f2 f1) (list h1 h3))) (newline)
