(import "cas/translimit.lisp")
(define N 12)
(display (limit->string (slimit (sin-series N) (id-series N)))) (newline)
(display (limit->string (slimit (ser-sub (const-series 1 N) (cos-series N)) (xpow 2 N)))) (newline)
(display (limit->string (slimit (ser-sub (exp-series N) (const-series 1 N)) (id-series N)))) (newline)
(display (limit->string (slimit (log1p-series N) (id-series N)))) (newline)
(display (limit->string (slimit (ser-sub (sin-series N) (id-series N)) (xpow 3 N)))) (newline)
(display (limit->string (slimit (tan-series N) (id-series N)))) (newline)
(display (limit->string (slimit (ser-sub (const-series 1 N) (cos-series N)) (ser-mul (id-series N) (sin-series N) N)))) (newline)
(display (limit->string (slimit (xpow 2 N) (sin-series N)))) (newline)
(display (limit->string (slimit (sin-series N) (xpow 2 N)))) (newline)
(display (list (slimit-ok? (sin-series N) (id-series N)) (slimit-ok? (ser-sub (sin-series N) (id-series N)) (xpow 3 N)) (slimit-ok? (sin-series N) (xpow 2 N)))) (newline)
