(import "cas/rischcrde.lisp")
(define t1 (list (list (quote exp) (rat-from-poly (list 0 1)))))
(define t2 (list (list (quote exp) (rat-from-poly (list 0 1))) (list (quote exp) (list (rat-zero) (rat-one)))))
(display (te-crde-solve t1 1 (list (rat-zero) (rat-one)) (list (rat-one)))) (newline)
(define ytest (list (rat-zero) (rat-one)))
(define gtest (te-add t1 1 (te-deriv t1 1 ytest) (te-mul t1 1 (list (rat-zero) (rat-one)) ytest)))
(define v2 (te-crde-solve t1 1 (list (rat-zero) (rat-one)) gtest))
(display (te-crde-certify t1 1 (list (rat-zero) (rat-one)) gtest v2)) (newline)
(display (te-crde-solve t2 2 (te-zero 2) (list (te-zero 1) (te-one 1)))) (newline)
(display (rat-equal? (te-crde-solve t1 0 (rat-from-poly (list 1)) (rat-from-poly (list 0 1))) (rat-from-poly (list -1 1)))) (newline)
