(import "cas/sos.lisp")
(display (sos-decide (list 0 0 1))) (display " ") (display (sos-nonneg? (list 0 0 1))) (display " ") (display (sos-positive? (list 0 0 1))) (newline)
(display (sos-positive? (list 1 0 1))) (display " ") (display (sos-positive? (list 1 0 0 0 1))) (newline)
(define q (poly-mul (poly-mul (list -1 1) (list -1 1)) (poly-mul (list -2 1) (list -2 1))))
(display (sos-decide q)) (display " ") (display (sos-verify q)) (newline)
(display (sos-decide (list -1 0 1))) (display " ") (display (sos-decide (list 0 0 0 1))) (newline)
(define r (poly-mul (list 0 0 1) (list -1 1)))
(display (sos-trim (sos-odd-factor r))) (display " ") (display (sos-decide r)) (newline)
(display (sos-decide (list -1 0 -1))) (newline)
