(import "cas/algquadint.lisp")
(display (aq-integrate 1 0 1 0 1)) (newline)
(display (aq-second-kind-verify 1 0 1)) (newline)
(display (aq-integrate 1 0 1 1 0)) (newline)
(display (aq-integrate 1 0 1 2 3)) (newline)
(display (aq-integrate -1 0 4 0 1)) (newline)
(display (aq-integrate -1 0 1 0 1)) (newline)
(display (aq-integrate -1 0 -1 0 1)) (newline)
(display (aq-disc 1 0 1)) (display " ") (display (aq-disc -1 0 4)) (newline)
