(import "cas/algpoint.lisp")
(define A (list (list -1 0 1) (list) (list 1)))
(define B (list (list 0 1) (list -1)))
(define pt (apt-make A B (/ 6 10) (/ 8 10) (/ 6 10) (/ 8 10)))
(display (apt-sign (list (list 0 1)) pt)) (display " ") (display (apt-sign (list (list) (list 1)) pt)) (display " ") (display (apt-sign (list (list -1 1) (list 1)) pt)) (newline)
(display (apt-sign (list (list -1 1)) pt)) (display " ") (display (apt-sign (list (list -1 2)) pt)) (newline)
(display (apt-sign B pt)) (display " ") (display (apt-sign A pt)) (newline)
(display (apt-sign (list (list) (list 0 1)) pt)) (display " ") (display (apt-sign (list (list -1) (list 0 2)) pt)) (newline)
(display (asec-sign (list -1 0 2) (apt-x-alpha pt))) (newline)
