(import "cas/galois.lisp")
(display (galois-prime? 5)) (newline)
(display (galois-eisenstein? (list 2 -4 0 0 0 1) 2)) (newline)
(display (galois-irreducible? (list 2 -4 0 0 0 1))) (newline)
(display (galois-real-root-count (list 2 -4 0 0 0 1))) (newline)
(display (galois-nonreal-count (list 2 -4 0 0 0 1))) (newline)
(display (galois-Sp-by-radicals? (list 2 -4 0 0 0 1))) (newline)
(display (galois-solvable-by-radicals? (list 2 -4 0 0 0 1))) (newline)
(display (galois-solvable-by-radicals? (list 3 -6 0 0 0 1))) (newline)
(display (galois-solvable-by-radicals? (list -1 -1 0 0 0 1))) (newline)
(display (galois-irreducible? (list -1 0 1))) (newline)
