(import "cas/groebner.lisp")
(define vars (list "x" "y"))
(define x-y (list (cons 1 (list 1 0)) (cons -1 (list 0 1))))
(display (map (lambda (g) (mpoly->str g vars))
  (reduced-groebner (list (list (cons 1 (list 2 0)) (cons 1 (list 0 2)) (cons -1 (list 0 0))) x-y)))) (newline)
(display (map (lambda (g) (mpoly->str g vars))
  (reduced-groebner (list (list (cons 1 (list 1 1)) (cons -1 (list 0 0))) x-y)))) (newline)
(display (map (lambda (g) (mpoly->str g vars))
  (reduced-groebner (list (list (cons 1 (list 2 0)) (cons 1 (list 0 2)) (cons -4 (list 0 0)))
                          (list (cons 1 (list 2 0)) (cons 1 (list 0 2)) (cons -2 (list 1 0))))))) (newline)
(display (in-ideal? (mpoly-mul (list (cons 1 (list 1 0)) (cons 1 (list 0 1))) x-y) (list x-y))) (newline)
