(import "cas/groebner3.lisp")
(define g1 (list (cons 1 (list 2 0)) (cons -1 (list 0 0))))
(define g2 (list (cons 1 (list 0 2)) (cons -1 (list 0 0))))
(define lxy (list (cons 1 (list 1 1))))
(display (gb3-chain-redundant? g1 g2 (list g1 g2 lxy))) (newline)
(define f1 (list (cons 1 (list 2 0)) (cons 1 (list 0 2)) (cons -1 (list 0 0))))
(define f2 (list (cons 1 (list 1 0)) (cons -1 (list 0 1))))
(display (groebner-ok? (groebner3 (list f1 f2)))) (display " ") (display (groebner3-agrees? (list f1 f2))) (newline)
(define p1 (list (cons 1 (list 2 0)) (cons 1 (list 0 2)) (cons -1 (list 0 0))))
(define p2 (list (cons 1 (list 2 0)) (cons -1 (list 0 1))))
(display (groebner3-agrees? (list p1 p2))) (newline)
(display (groebner3-agrees? (list g1 g2))) (newline)
(define e1 (list (cons 1 (list 1 0 0)) (cons -1 (list 0 0 0))))
(define e2 (list (cons 1 (list 0 1 0)) (cons -2 (list 0 0 0))))
(define e3 (list (cons 1 (list 0 0 1)) (cons -3 (list 0 0 0))))
(display (groebner3-agrees? (list e1 e2 e3))) (newline)
