(import "cas/cdcl3.lisp")
(define (pv i j h) (+ (* (- i 1) h) j))
(define (build-php p h) (append (be p h 1) (bn p h 1)))
(define (be p h i) (cond ((> i p) (quote ())) (else (cons (row i h 1) (be p h (+ i 1))))))
(define (row i h j) (cond ((> j h) (quote ())) (else (cons (pv i j h) (row i h (+ j 1))))))
(define (bn p h j) (cond ((> j h) (quote ())) (else (append (pfh p h j 1) (bn p h (+ j 1))))))
(define (pfh p h j i) (cond ((> i p) (quote ())) (else (append (pik p h j i (+ i 1)) (pfh p h j (+ i 1))))))
(define (pik p h j i k) (cond ((> k p) (quote ())) (else (cons (list (- 0 (pv i j h)) (- 0 (pv k j h))) (pik p h j i (+ k 1))))))
(define (setup-levels) (begin (c3-init! 5 (list (list 1 2 3 4 5))) (vector-set! c3-level 1 0) (vector-set! c3-level 2 2) (vector-set! c3-level 3 2) (vector-set! c3-level 4 5) (c3-lbd (list 1 2 3 4))))
(display (setup-levels)) (newline)
(display (c3-lbd (list 2 3))) (newline)
(display (cdcl3-solve 2 (list (list 1 2) (list -1 2) (list 1 -2) (list -1 -2)))) (newline)
(display (cdcl3-solve 3 (list (list 1) (list -1 2) (list -2 3) (list -3)))) (newline)
(display (cdcl3-solve 12 (build-php 4 3))) (newline)
(display (cdcl3-solve 20 (build-php 5 4))) (newline)
(display (cdcl3-solve 30 (build-php 6 5))) (newline)
