(import "cas/towerrt.lisp")
(define LOG (list 'log))
(define (residues r) (map car (car (cdr (cdr r)))))
(define a1 (list (rat-from-poly (list -1 -3)) (rat-make (list 3 1) (list 0 1))))
(define d1 (list (rat-from-poly (list 0 0 -1)) (rat-zero) (rat-one)))
(display (residues (int-prim-rational a1 d1 LOG))) (newline)
(display (int-prim-rational-verify a1 d1 LOG)) (newline)
(define a4 (list (rat-zero) (rat-one)))
(define d4 (list (rat-from-poly (list 0 1)) (rat-zero) (rat-one)))
(display (int-prim-rational-elementary? a4 d4 LOG)) (newline)
(define a5 (list (rat-make (list 1) (list 0 1))))
(define d5 (list (rat-from-poly (list -2)) (rat-zero) (rat-one)))
(display (car (int-prim-rational a5 d5 LOG))) (newline)
