(import "cas/ellint.lisp")
(display (car (ei-integrate (rat-from-poly (list 1 0 0 1)) 0))) (display " ")
(display (car (ei-integrate (rat-from-poly (list 4 0 0 1)) 0))) (newline)
(display (car (ei-integrate (rat-from-poly (list 1 0 0 1)) 2))) (display " ")
(display (car (ei-integrate (rat-from-poly (list 0 4 0 1)) 2))) (display " ")
(display (car (ei-integrate (rat-from-poly (list -2 0 0 1)) 3))) (display " ")
(display (car (ei-integrate (rat-from-poly (list 1 0 0 1)) 1))) (newline)
(display (ei-remainder-lambda (rat-from-poly (list 1 0 0 1)) 0)) (display " ")
(display (ei-remainder-lambda (rat-from-poly (list 1 0 0 1)) 2)) (newline)
