(import "cas/hyperthird.lisp")
(define f (list 1 0 0 0 0 1))
(display (ht-cert f (list 0 1))) (newline)
(display (poly-norm (ht-norm f (list 0 1)))) (newline)
(display (poly-norm (ht-recover-a f (ht-norm f (list 0 1))))) (newline)
(display (car (ht-recognize f (ht-norm f (list 0 1))))) (newline)
(display (ht-cert f (list 0 0 1))) (display " ") (display (poly-norm (ht-recover-a f (ht-norm f (list 0 0 1))))) (newline)
(display (ht-cert f (list 1 0 1))) (display " ") (display (poly-norm (ht-recover-a f (ht-norm f (list 1 0 1))))) (newline)
(display (ht-recognize f (list 1 1 1))) (newline)
(define fe (list 1 0 0 1))
(display (ht-cert fe (list 0 1))) (newline)
