(import "cas/sosmv.lisp")
(define x+y (list (cons 1 (list 1 0)) (cons 1 (list 0 1))))
(define p1 (list (cons 1 (list 2 0)) (cons 2 (list 1 1)) (cons 1 (list 0 2))))
(display (mvsos-is-certificate? p1 (list x+y))) (display " ") (display (mvsos-certify p1 (list x+y))) (newline)
(define qx (list (cons 1 (list 1 0))))
(define qy (list (cons 1 (list 0 1))))
(define p2 (list (cons 1 (list 2 0)) (cons 1 (list 0 2))))
(display (mvsos-is-certificate? p2 (list qx qy))) (display " ") (display (mvsos-residual p2 (list x+y))) (newline)
(define one (list (cons 1 (list 0 0))))
(define g (mvsos-gauss-product qx one qy one))
(define lhs (mpoly-mul (mpoly-add (mvsos-square qx) (mvsos-square one)) (mpoly-add (mvsos-square qy) (mvsos-square one))))
(display (mvsos-is-certificate? lhs g)) (newline)
(define M (list (cons 1 (list 4 2)) (cons 1 (list 2 4)) (cons -3 (list 2 2)) (cons 1 (list 0 0))))
(display (mvsos-is-certificate? M (quote ()))) (newline)
