(import "cas/rischradn.lisp")
(define r (radn-integrate (list 0 0 1) 0 1))
(display (car (cdr r))) (newline)
(display (car (cdr (cdr r)))) (newline)
(display (radn-certify (list 0 0 1) 0 1 r)) (newline)
(display (radn-certify (list 1) 0 1 (radn-integrate (list 1) 0 1))) (newline)
(display (radn-certify (list 0 0 0 1) 0 1 (radn-integrate (list 0 0 0 1) 0 1))) (newline)
(display (radn-certify (list 1 1 1) 0 1 (radn-integrate (list 1 1 1) 0 1))) (newline)
(display (radn-certify (list 0 0 1) 2 5 (radn-integrate (list 0 0 1) 2 5))) (newline)
