(import "cas/elliptic3pell.lisp")
(define q (list 1 0 1))
(display (e3p-a0 q)) (display " ") (display (e3p-fundamental-norm q)) (newline)
(display (e3p-unit-power q 1)) (newline)
(display (e3p-unit-power q 2)) (display " ") (display (e3p-B-nonconstant? q 2)) (display " ") (display (e3p-certify q 2)) (newline)
(display (e3p-unit-power q 3)) (display " ") (display (e3p-certify q 3)) (newline)
(display (e3p-certify q 4)) (newline)
(define q2 (list 5 2 1))
(display (e3p-a0 q2)) (display " ") (display (e3p-fundamental-norm q2)) (newline)
(display (e3p-certify q2 2)) (display " ") (display (e3p-certify q2 3)) (display " ") (display (e3p-B-nonconstant? q2 2)) (newline)
