(import "cas/intexp.lisp")
(define A1 (rf-const (rat-one)))
(define D1 (list (rat-zero) (rat-one) (rat-one)))
(define d1 (iexp-decompose A1 D1))
(display (iexp-j d1)) (newline)
(display (int-exp-rational-full-verify A1 D1)) (newline)
(define D2 (list (rat-from-poly (list 2)) (rat-from-poly (list 3)) (rat-one)))
(define A2 (rfpoly-add (rfpoly-mul (rfpoly-monomial (rat-one) 2) D2) (list (rat-from-poly (list -6)) (rat-from-poly (list -5)))))
(display (int-exp-rational-full-verify A2 D2)) (newline)
(display (int-exp-rational-full-elementary? A2 D2)) (newline)
(define D4 (list (rat-zero) (rat-from-poly (list 0 1)) (rat-one)))
(display (int-exp-rational-full-elementary? (rf-const (rat-one)) D4)) (newline)
