(import "cas/dtt.lisp")
(define (V n) (list (quote var) n))
(define (LAM T b) (list (quote lam) T b))
(define (PI T b) (list (quote pi) T b))
(define (APP f a) (list (quote app) f a))
(define polyId (LAM (quote type) (LAM (V 0) (V 0))))
(define polyIdType (PI (quote type) (PI (V 0) (V 1))))
(define someType (PI (quote type) (quote type)))
(display (dtt-equal? (APP (LAM (quote type) (V 0)) (V 3)) (V 3))) (newline)
(display (dtt-infer (list (quote type)) (LAM (V 0) (V 0)))) (newline)
(display (dtt-infer (quote ()) polyId)) (newline)
(display (dtt-check (quote ()) polyId polyIdType)) (newline)
(display (dtt-equal? (dtt-infer (quote ()) (APP polyId someType)) (PI someType someType))) (newline)
(display (dtt-infer (quote ()) (APP (quote type) (quote type)))) (newline)
(display (dtt-infer (quote ()) (V 0))) (newline)
(display (dtt-check (list (quote type)) (LAM (V 0) (V 0)) (PI (V 0) (quote type)))) (newline)
(display (dtt-infer (list (quote type) (quote type)) (APP (LAM (V 1) (V 0)) (V 0)))) (newline)
