(import "cas/idealops.lisp")
(define vars (list "x" "y"))
(define x-y (list (cons 1 (list 1 0)) (cons -1 (list 0 1))))
(define G (reduced-groebner (list (list (cons 1 (list 2 0)) (cons 1 (list 0 2)) (cons -1 (list 0 0))) x-y)))
(display (map (lambda (g) (mpoly->str g vars)) (elim-ideal G 1))) (newline)
(define Ix (list (list (cons 1 (list 1 0)))))
(define Iy (list (list (cons 1 (list 0 1)))))
(display (map (lambda (g) (mpoly->str g vars)) (ideal-intersect Ix Iy 2))) (newline)
(display (map (lambda (g) (mpoly->str g vars)) (ideal-intersect (list (list (cons 1 (list 2 0)))) Ix 2))) (newline)
(display (mv->uni (last-generator G 2) 2)) (newline)
(display (solve-last->string G 2)) (newline)
