(import "cas/linalgfp.lisp")
(define p 7)
(define B (list (list 2 0 1) (list 1 3 2) (list 0 1 1)))
(define S (list (list 1 2 3) (list 2 4 6) (list 1 1 1)))
(display (list (fm-det (list (list 1 2) (list 3 4)) p) (fm-det B p))) (newline)
(display (fm-inverse B p)) (newline)
(display (fm-mul B (fm-inverse B p) p)) (newline)
(display (list (fm-rank S p) (length (fm-nullspace S p)))) (newline)
(display (fm-nullspace S p)) (newline)
(display (fm-solve (list (list 2 1 1) (list 1 3 2) (list 1 0 0)) (list 5 6 2) p)) (newline)
(display (list (fm-inverse-ok? B p) (fm-detmul-ok? B S p) (fm-ranknull-ok? S p) (fm-null-ok? S p) (fm-solve-ok? (list (list 2 1 1) (list 1 3 2) (list 1 0 0)) (list 5 6 2) p))) (newline)
