(import "cas/galquartic.lisp")
(display (galq-group 0 0 0 1)) (newline)
(display (galq-group 0 0 1 1)) (newline)
(display (galq-group 0 0 8 12)) (newline)
(display (galq-group 0 0 0 -2)) (newline)
(display (galq-group 0 0 0 4)) (newline)
(display (galq-group 0 -5 0 6)) (newline)
(display (galq-resolvent 0 0 0 1)) (newline)
(display (galq-discriminant 0 0 1 1)) (newline)
(display (galq-discriminant 0 0 8 12)) (newline)
