(import "cas/polysolve.lisp")
(define f1 (list (cons 1 (list 2 0)) (cons 1 (list 0 2)) (cons -1 (list 0 0))))
(define f2 (list (cons 1 (list 1 0)) (cons -1 (list 0 1))))
(define S1 (list f1 f2))
(display (psys-consistent? S1)) (display " ") (display (psys-zero-dim? S1 2)) (newline)
(display (psys-eliminant S1 2 1)) (newline)
(display (psys-consequence? f1 S1)) (display " ") (display (psys-consequence? (list (cons 1 (list 1 0))) S1)) (newline)
(define g1 (list (cons 1 (list 1 0)) (cons 1 (list 0 1)) (cons -2 (list 0 0))))
(define g2 (list (cons 1 (list 1 0)) (cons 1 (list 0 1)) (cons -3 (list 0 0))))
(display (psys-consistent? (list g1 g2))) (newline)
(define h1 (list (cons 1 (list 1 1)) (cons -1 (list 0 0))))
(display (psys-consistent? (list h1))) (display " ") (display (psys-zero-dim? (list h1) 2)) (newline)
