(import "cas/gaussint.lisp")
(define (rng a b) (if (> a b) '() (cons a (rng (+ a 1) b))))
(define (all? l) (cond ((null? l) #t) ((car l) (all? (cdr l))) (else #f)))
(display (gi->string (gi-mul (cons 2 1) (cons 2 -1)))) (newline)
(display (list (gi-norm (cons 3 2)) (gi-norm (cons 1 1)))) (newline)
(display (list (gi->string (gi-split 5)) (gi->string (gi-split 13)) (gi->string (gi-split 29)) (gi->string (gi-split 97)))) (newline)
(display (list (gi->string (gi-gcd (cons 5 0) (cons 2 1))) (gi->string (gi-gcd (cons 6 8) (cons 4 4))))) (newline)
(display (list (gi-prime? (cons 2 1)) (gi-prime? (cons 3 0)) (gi-prime? (cons 5 0)) (gi-prime? (cons 7 0)) (gi-prime? (cons 1 1)))) (newline)
(display (list (gi-norm-mult-ok? (cons 3 2) (cons 1 4)) (gi-div-ok? (cons 17 5) (cons 3 2)) (gi-gcd-divides? (cons 11 3) (cons 1 8)))) (newline)
(display (all? (map gi-split-ok? (filter (lambda (p) (and (prime? p) (= (imod p 4) 1))) (rng 5 200))))) (newline)
