(import "cas/hyperpellcf.lisp")
(define f (list 0 1 0 0 0 0 1))
(display (hpc-has-unit? f 30)) (newline)
(display (list (poly-norm (car (hpc-unit f 30))) (poly-norm (car (cdr (hpc-unit f 30)))))) (newline)
(display (hpc-log-cert f 30 1)) (display " ") (display (hpc-log-cert f 30 2)) (display " ") (display (hpc-log-cert f 30 3)) (newline)
(define f1 (list 1 0 0 0 0 0 1))
(display (hpc-has-unit? f1 30)) (newline)
(display (list (poly-norm (car (hpc-unit f1 30))) (poly-norm (car (cdr (hpc-unit f1 30)))))) (newline)
(display (hpc-log-cert f1 30 2)) (newline)
(define fn (list 1 0 1 0 0 0 1))
(display (hpc-has-unit? fn 30)) (newline)
(display (hpc-log fn 30 2)) (newline)
