(import "cas/inetdep.lisp")
(kernel-assume (quote Nat) (quote (Sort 0)))
(kernel-assume (quote F) (quote (Pi (n Nat) (Sort 0))))
(kernel-assume (quote mk) (quote (Pi (n Nat) (app F n))))
(define poly-id (itd-lam (quote A) (itd-sort 0) (itd-lam (quote x) (itd-var (quote A)) (itd-var (quote x)))))
(define ty-polyid (itd-pi (quote A) (itd-sort 0) (itd-pi (quote x) (itd-var (quote A)) (itd-var (quote A)))))
(define app-mk-zero (itd-app (itd-const (quote mk)) (itd-const (quote zero))))
(display (itd-readback-is? poly-id (quote (lam (A (Sort 0)) (lam (x A) x))))) (newline)
(display (itd-readback-is? ty-polyid (quote (Pi (A (Sort 0)) (Pi (x A) A))))) (newline)
(display (itd-check poly-id (itd-readback ty-polyid))) (newline)
(display (itd-check app-mk-zero (quote (app F zero)))) (newline)
(display (not (itd-check app-mk-zero (quote (app F (succ zero)))))) (newline)
(display (itd-agree? app-mk-zero (quote (app mk zero)) (quote (app F zero)))) (newline)
(display (itd-agree? app-mk-zero (quote (app mk zero)) (quote (app F (succ zero))))) (newline)
