(import "cas/newton.lisp")
(define node (list (list 0 0 -1 -1) (list) (list 1)))
(display (nw-slopes node)) (display " ") (display (car (cdr (car (nw-newton-polygon node))))) (newline)
(define se (list (list 0 -1) (list) (list 1)))
(display (nw-slopes se)) (newline)
(define cusp (list (list 0 0 0 -1) (list) (list 1)))
(display (nw-slopes cusp)) (newline)
(define two (list (list 0 0 0 1) (list 0 -1 -1) (list 1)))
(display (nw-slopes two)) (newline)
(define tac (list (list 0 0 0 0 -1) (list) (list 1)))
(display (nw-slopes tac)) (newline)
(define smooth (list (list 0 -1 -1) (list 1)))
(display (nw-slopes smooth)) (newline)
