(import "cas/hermite.lisp")
(define D1 (poly-mul (list 0 0 1) (list -1 1)))
(display (square-free (poly-monic D1))) (newline)
(display (hermite (list 1) D1)) (newline)
(display (hermite-radical D1)) (newline)
(display (hermite-verify (list 1) D1)) (newline)
(define D2 (hm-pow (list -1 1) 3))
(display (hermite (list 1) D2)) (newline)
(display (list (hermite-verify (list 1) D2) (poly-zero? (car (cdr (cdr (hermite (list 1) D2))))))) (newline)
(display (list (hermite-verify (list 0 1) (hm-pow (list 1 0 1) 2))
               (hermite-verify (list 1 0 1) (poly-mul (hm-pow (list 0 1) 2) (hm-pow (list -1 1) 2)))
               (hermite-verify (list 5) (hm-pow (list -2 0 1) 3))
               (hermite-verify (list 5 1 0 2) (hm-pow (list 1 1 1) 2)))) (newline)
