(import "cas/infplaces.lisp")
(define q3 (list 1 0 0 1))
(define q4 (list 1 0 0 0 1))
(define q5 (list 1 0 0 0 0 1))
(define q6 (list 1 0 0 0 0 0 1))
(display (ip-infinite-ramified? q3)) (display " ") (display (ip-num-infinite-places q3)) (display " ") (display (ip-genus-rh q3)) (newline)
(display (ip-infinite-ramified? q4)) (display " ") (display (ip-num-infinite-places q4)) (display " ") (display (ip-genus-rh q4)) (newline)
(display (ip-num-infinite-places (list 1 0 0 0 2))) (newline)
(display (ip-genus-agrees? q3)) (display " ") (display (ip-genus-agrees? q4)) (display " ") (display (ip-genus-agrees? q5)) (display " ") (display (ip-genus-agrees? q6)) (newline)
(display (ip-genus-rh q5)) (display " ") (display (ip-genus-rh q6)) (newline)
