(import "cas/puiseuxg.lisp")
(define F1 (list (list -1 -1) (list) (list 1)))
(define bs1 (pg-branches F1 5))
(display (length bs1)) (display " ") (display (pg-zero-series? (pg-verify F1 (car bs1) 5) 4)) (newline)
(define Fc (list (list 0 0 0 -1) (list) (list 1)))
(display (pg-nth (car (pg-branches Fc 6)) 1)) (display " ") (display (pg-nth (car (pg-branches Fc 6)) 2)) (newline)
(define Fcat (list (list 0 -1) (list 1) (list -1)))
(display (pg-nth (car (pg-branches Fcat 6)) 3)) (newline)
(define Ft (list (list 0 0 0 1) (list 0 -1 -1) (list 1)))
(display (nw-slopes Ft)) (newline)
(define Fr (list (list -2 -1) (list) (list 1)))
(display (car (car (pg-branches Fr 4)))) (newline)
