(import "cas/radgen.lisp")
(define f (list -2 5 -4 1))
(display (rg-radical f)) (newline)
(display (rg-decomposition f)) (newline)
(display (rg-decomposition-ok? f)) (newline)
(display (rg-is-radical-ideal? (list 2 -3 1))) (display " ") (display (rg-is-radical-ideal? f)) (newline)
(display (rg-in-radical? f (list 2 -3 1))) (display " ") (display (rg-in-radical? f (poly-mul (list 2 -3 1) (list -5 1)))) (newline)
(display (rg-in-radical? f (list -1 1))) (display " ") (display (rg-in-radical? f (list -3 1))) (newline)
(define f2 (poly-mul (list -1 1) (poly-mul (list -1 1) (list -1 1))))
(display (rg-radical f2)) (display " ") (display (rg-decomposition-ok? f2)) (newline)
