(import "cas/hyperjac.lisp")
(define f (list 1 0 0 0 0 1))
(define eg (hj-egcd (list -1 0 1) (list -1 1)))
(display (poly-norm (car eg))) (newline)
(define P (hj-point 0 1))
(define Q (hj-point -1 0))
(display (hj-valid? f (hj-identity))) (display " ") (display (hj-valid? f P)) (display " ") (display (hj-valid? f Q)) (newline)
(display (hj-equal? (hj-add f P (hj-identity)) P)) (newline)
(display (hj-add f P Q)) (newline)
(display (hj-valid? f (hj-add f P Q))) (newline)
(display (hj-equal? (hj-add f P (hj-neg P)) (hj-identity))) (newline)
(display (hj-equal? (hj-double f Q) (hj-identity))) (newline)
(display (hj-equal? (hj-mul f 3 Q) Q)) (newline)
