(import "cas/algexp.lisp")
(define p (list 0 1))
(define y (sf-y 2))
(define wp (ae-wprime p 2 y))
(display wp) (newline)
(define A1 (sf-one 2))
(define B1 (ae-rhs p 2 wp A1))
(display (ae-certify p 2 wp A1 B1)) (newline)
(display (ae-solve p 2 wp B1 0)) (newline)
(display (ae-solve p 2 wp (ae-rhs p 2 wp y) 0)) (newline)
(define Axy (sf-set (sf-set (sf-zeros 2) 0 (rat-from-poly (list 0 1))) 1 (rat-one)))
(display (ae-solve p 2 wp (ae-rhs p 2 wp Axy) 1)) (newline)
(define p3 (list 0 1))
(define y3 (sf-y 3))
(define wp3 (ae-wprime p3 3 y3))
(display (ae-solve p3 3 wp3 (ae-rhs p3 3 wp3 y3) 0)) (newline)
