(import "cas/rischtower.lisp")
(display (rt-rde-exp-const-solvable? (list 1) (list 0 1))) (newline)
(display (rt-rde-exp-const-solvable? (list 0 2) (list 1))) (newline)
(display (rt-rde-exp-const-solvable? (list 0 2) (list 0 2))) (newline)
(display (rt-decide-iterated-exp 1)) (newline)
(display (rt-decide-iterated-exp 2)) (newline)
(display (rt-decide-iterated-exp 3)) (newline)
(display (rt-decide-iterated-product 3)) (newline)
(display (rt-reduce-exp (list (list 0 1) (list 1)) (list 0 1))) (newline)
(display (rt-bottom-rational)) (newline)
