(import "cas/tower2risch.lisp")
(define MEXP (list (quote exp) (list 0 1)))
(define uprime (list (list (rat-zero) (rat-one)) (list (rat-one))))
(define Aelem (list (k1-zero) (list (list (rat-zero) (rat-one)) (list (rat-one)))))
(define Anon (list (k1-zero) (k1-one)))
(display (h2-integrate-verify Aelem (list (k1-one)) (quote exp) uprime MEXP)) (display " ")
(display (h2int-status (h2-integrate Anon (list (k1-one)) (quote exp) uprime MEXP))) (newline)
(display (h2-integrate-verify (h2-monomial (k1-one) 2) (list (k1-one)) (quote prim) (t2-trrat 1) MEXP)) (display " ")
(display (h2-integrate-decides? Anon (list (k1-one)) (quote exp) uprime MEXP)) (newline)
