(import "cas/smt.lisp")
(define apps (list (list 5 100 0) (list 6 100 2)))
(define eqs (list (list 0 1) (list 1 2) (list 5 3) (list 6 4)))
(define cc (smt-cc-build 7 eqs apps))
(display (smt-cc-same? cc 5 6)) (newline)
(display (smt-cc-same? cc 3 4)) (newline)
(display (smt-euf-consistent? 7 eqs (quote ()) apps)) (newline)
(display (smt-euf-consistent? 7 eqs (list (list 3 4)) apps)) (newline)
(define atoms (list (list 0 1) (list 1 2) (list 0 2)))
(display (smt-solve 3 atoms (quote ()) (list (list 1) (list 2) (list -3)))) (newline)
(display (smt-solve 3 atoms (quote ()) (list (list 1) (list 2) (list 3)))) (newline)
(display (smt-solve 7 (list (list 0 1) (list 5 6)) (list (list 5 100 0) (list 6 100 1)) (list (list 1) (list -2)))) (newline)
