(import "cas/itlogsolve.lisp")
(define (mono c v) (cons (rat-from-poly (list c)) v))
(define B1 (il-deriv 2 (list (mono 1 (list 0 2)))))
(display (ils-vecs (ils-solve 2 B1))) (newline)
(display (il-certify 2 (ils-solve 2 B1) B1)) (newline)
(define B2 (il-deriv 2 (list (mono 1 (list 1 0)) (mono 1 (list 0 1)))))
(display (ils-vecs (ils-solve 2 B2))) (newline)
(display (il-certify 2 (ils-solve 2 B2) B2)) (newline)
(define B3 (il-deriv 3 (il-top 3)))
(display (il-certify 3 (ils-solve 3 B3) B3)) (newline)
