(import "cas/weaknorm.lisp")
(display (weak-normalizer (list -6 5/2) (list 0 -3 1))) (newline)
(display (list (poly-const? (weak-normalizer (list 1) (list -6 2))) (poly-const? (weak-normalizer (list -1) (list 0 0 1))))) (newline)
(define fa (list -6 5/2)) (define fd (list 0 -3 1))
(define ga (list 1)) (define gd (poly-scale 2 (poly-mul (list 0 0 1) (list -3 1))))
(display (rdr-solve fa fd ga gd)) (newline)
(define y (rde-general fa fd ga gd))
(display y) (newline)
(display (rde-general-verify fa fd ga gd y)) (newline)
