(import "cas/series.lisp")
(display (exp-series 7)) (newline)
(display (sin-series 8)) (newline)
(display (cos-series 8)) (newline)
(display (log1p-series 7)) (newline)
(display (binom-series (/ 1 2) 6)) (newline)
(display (ratfun->series (list 1) (list 1 -1 -1) 9)) (newline)
(display (exp-of (sin-series 7) 7)) (newline)
(display (limit-ratio (sin-series 8) (list 0 1))) (newline)
(display (limit-ratio (ser-sub (list 1) (cos-series 8)) (list 0 0 1))) (newline)
(display (ser->string (exp-series 5) "x")) (newline)
