(import "cas/stirling.lisp")
(display (stirling2-row 5)) (newline)
(display (stirling2-row 6)) (newline)
(display (stirling1-row 5)) (newline)
(display (bell-list-str 8)) (newline)
(display (list (stirling2 4 2) (stirling2 5 3) (stirling1 4 2) (stirling1 5 2))) (newline)
(display (map stirling2-ok? (prange 1 7))) (newline)
(display (map stirling1-ok? (prange 1 7))) (newline)
(display (map stirling1-sum-ok? (prange 1 7))) (newline)
(display (map bell-ok? (prange 0 8))) (newline)
