(import "cas/cadnd.lisp")
(define p (list (list (cons -1 (list 1 0))) (list (cons 1 (list 0 0)))))
(define q (list (list (cons -1 (list 0 1))) (list (cons 1 (list 0 0)))))
(display (cadn-resultant p q)) (newline)
(define zsq (list (list (cons -1 (list 1 0))) (quote ()) (list (cons 1 (list 0 0)))))
(display (cadn-discriminant zsq)) (display " ") (display (cadn-deg zsq)) (newline)
(define ball (cons (quote neg) (lambda (x y z) (- (+ (+ (* x x) (* y y)) (* z z)) 1))))
(display (cadn-exists3 (list ball))) (newline)
(define ballpos (cons (quote neg) (lambda (x y z) (+ (+ (+ (* x x) (* y y)) (* z z)) 1))))
(display (cadn-exists3 (list ballpos))) (newline)
(display (cadn-exists3 (list (cons (quote pos) (lambda (x y z) x)) (cons (quote pos) (lambda (x y z) y)) (cons (quote pos) (lambda (x y z) z)) (cons (quote neg) (lambda (x y z) (- (+ (+ x y) z) 1)))))) (newline)
