(import "cas/positivstellensatz.lisp")
(define g1 (list -1 1))
(define cert1 (cons (list 1) (list (cons (list 1) g1))))
(display (psatz-rhs cert1)) (display " ") (display (psatz-valid? (list 0 1) cert1)) (display " ") (display (psatz-on-set? (list 0 1) cert1)) (newline)
(define s0 (poly-mul g1 g1))
(define cert2 (cons s0 (list (cons (list 2) g1))))
(display (psatz-valid? (list -1 0 1) cert2)) (display " ") (display (psatz-certify (list -1 0 1) cert2)) (newline)
(define bad (cons (list -2) (list (cons (list 1) g1))))
(display (psatz-valid? (list -3 1) bad)) (display " ") (display (psatz-certify (list -3 1) bad)) (newline)
(define brk (cons (list 1) (list (cons (list 2) g1))))
(display (psatz-certify (list 0 1) brk)) (newline)
(display (psatz-valid? (list 1 0 1) (cons (list 1 0 1) (quote ())))) (newline)
