(import "cas/lra.lisp")
(display (lra-sat? 1 (list (list (quote ge) -1 1) (list (quote ge) 3 -1)))) (newline)
(display (lra-sat? 1 (list (list (quote ge) -3 1) (list (quote ge) 1 -1)))) (newline)
(display (lra-sat? 1 (list (list (quote gt) -2 1) (list (quote gt) 5 -1)))) (newline)
(display (lra-sat? 1 (list (list (quote gt) -2 1) (list (quote gt) 2 -1)))) (newline)
(display (lra-sat? 1 (list (list (quote ge) -2 1) (list (quote gt) 2 -1)))) (newline)
(display (lra-sat? 1 (list (list (quote eq) -4 2) (list (quote ge) -2 1)))) (newline)
(display (lra-sat? 1 (list (list (quote eq) -4 2) (list (quote ge) -3 1)))) (newline)
(display (lra-sat? 3 (list (list (quote ge) 10 -1 -1 -1) (list (quote ge) -1 1 0 0) (list (quote ge) -2 0 1 0) (list (quote ge) -3 0 0 1)))) (newline)
(display (lra-sat? 3 (list (list (quote ge) 5 -1 -1 -1) (list (quote ge) -1 1 0 0) (list (quote ge) -2 0 1 0) (list (quote ge) -3 0 0 1)))) (newline)
