(import "cas/algresfull.lisp")
(define LOG (list 'log))
(define d (list (rat-from-poly (list 2)) (rat-from-poly (list -2)) (rat-from-poly (list -1)) (rat-one)))
(define a (list (rat-make (list -3) (list 0 1)) (rat-make (list 1) (list 0 1)) (rat-make (list 1) (list 0 1))))
(display (car (int-prim-rational-full a d LOG))) (newline)
(display (int-prim-rational-full-verify a d LOG)) (newline)
(define dc (list (rat-from-poly (list -2)) (rat-zero) (rat-zero) (rat-one)))
(define ac (list (rat-make (list 6) (list 0 1))))
(display (int-prim-rational-full-verify ac dc LOG)) (newline)
