(import "cas/cadqe2.lisp")
(import "cas/cadqesimp.lisp")
(define quad (list (list (cons 1 (list 0 1))) (list (cons 1 (list 1 0))) (list (cons 1 (list 0 0)))))
(define r (cadqe2-elim (quote exists) (cons (quote zero) quad)))
(display (cadqs-simplify (car r) (cdr r))) (newline)
(define f1 (list (list 1 1 0)))
(define f2 (list (list 1 0 1)))
(display (cadqs-simplify (list f1 f2) (list (list 1 1) (list 1 -1) (list 1 0)))) (newline)
(display (cadqs-simplify (list f1) (list (list 1) (list 0)))) (newline)
(display (cadqs-simplify (list f1) (list (list 1) (list -1)))) (newline)
