(import "cas/rischde.lisp")
(define (rat B E) (cons B E))
(display (rischde '() (rat (list 0 0 3) (list 1)))) (newline)
(display (int-rat-exp (rat (list -1 1) (list 0 0 1)) (list 0 1))) (newline)
(display (int-rat-exp (rat (list 0 2) (list 1)) (list 0 0 1))) (newline)
(display (int-rat-exp (rat (list 0 1) (list 1 2 1)) (list 0 1))) (newline)
(display (list (int-rat-exp-verify (rat (list 1 0 2) (list 1)) (list 0 0 1))
               (int-rat-exp-verify (rat (list 0 2 0 2) (list 1)) (list 0 0 1)))) (newline)
(display (list (car (int-rat-exp (rat (list 1) (list 1)) (list 0 0 1)))
               (car (int-rat-exp (rat (list 1) (list 0 1)) (list 0 1))))) (newline)
