(import "cas/rischtoweralg.lisp")
(define t1a (list (list (quote alg) 2 (rat-from-poly (list 0 1)))))
(define sx (list (rat-zero) (rat-one)))
(display (rat-equal? (te-acoeff 1 (tea-deriv t1a 1 sx) 1) (rat-make (list 1) (list 0 2)))) (newline)
(define sq (tea-sq t1a 1 sx))
(display (te-acoeff 1 sq 0)) (newline)
(display (rat-equal? (te-acoeff 1 sq 1) (rat-zero))) (newline)
(define asq (list (rat-from-poly (list 0 1)) (rat-zero)))
(display (rat-equal? (te-acoeff 1 (tea-deriv t1a 1 asq) 0) (rat-from-poly (list 1)))) (newline)
(display (tea-w t1a 1)) (newline)
