(import "cas/sefield.lisp")
(define g (list 1 0 0 1))
(define y (sf-y 3))
(define y3 (sf-product g 3 (sf-product g 3 y y) y))
(display (sf-nth y3 0)) (newline)
(display (sf-deriv g 3 y)) (newline)
(define u (sf-set (sf-set (sf-zeros 3) 0 (rat-from-poly (list 0 1))) 1 (rat-one)))
(display (sf-deriv g 3 u)) (newline)
(define f_gg (sf-set (sf-zeros 3) 0 (rat-make (poly-deriv g) g)))
(define ug (sf-set (sf-zeros 3) 0 (rat-from-poly g)))
(display (sf-log-certify g 3 f_gg ug (rat-one))) (newline)
(define g2 (list 1 0 1))
(display (sf-deriv g2 2 (sf-y 2))) (newline)
