(import "cas/tptp/core.lisp")
(define x (list (cons 1 (list 1))))
(define x-1 (list (cons 1 (list 1)) (cons -1 (list 0))))
(display (tptp-decide (list (quote poly-unsat) (list x x-1)))) (display " ") (display (tptp-route-name (tptp-shape (list (quote poly-unsat) (list x x-1))))) (newline)
(display (tptp-decide (list (quote poly-unsat) (list (list (cons 1 (list 1)) (cons -5 (list 0))))))) (newline)
(display (tptp-decide (list (quote poly-identity) (list 1 2 1) (list 1 2 1)))) (display " ") (display (tptp-decide (list (quote poly-identity) (list 1 2 1) (list 1 1 1)))) (newline)
(display (tptp-decide (list (quote nonneg) (list 1 0 1)))) (display " ") (display (tptp-decide (list (quote nonneg) (list -1 0 1)))) (newline)
(define qx (list (cons 1 (list 1 0))))
(define qy (list (cons 1 (list 0 1))))
(define p2 (list (cons 1 (list 2 0)) (cons 1 (list 0 2))))
(display (tptp-decide (list (quote nonneg-sos) p2 (list qx qy)))) (newline)
(define M (list (cons 1 (list 4 2)) (cons 1 (list 2 4)) (cons -3 (list 2 2)) (cons 1 (list 0 0))))
(display (tptp-decide (list (quote nonneg-sos) M (quote ())))) (newline)
(display (tptp-decide (list (quote ground) (quote =) 4 4))) (display " ") (display (tptp-decide (list (quote ground) (quote <) 3 2))) (newline)
(display (tptp-decide (list (quote some-fol-formula) 1 2))) (newline)
(display (tptp-explain (list (quote poly-unsat) (list x x-1)))) (newline)
(define g1c (list -1 1))
(define certc (cons (list 1) (list (cons (list 1) g1c))))
(display (tptp-decide (list (quote nonneg-on-set) (list 0 1) certc))) (display " ") (display (tptp-route-name (tptp-shape (list (quote nonneg-on-set) (list 0 1) certc)))) (newline)
(display (tptp-decide (list (quote real-qe) (quote forall) (cons (quote pos) (list 1 0 1))))) (display " ") (display (tptp-route-name (tptp-shape (list (quote real-qe) (quote forall) (cons (quote pos) (list 1 0 1)))))) (newline)
