(import "cas/laurent.lisp")
(define L (lr-expand-ratfun (list 1) (list 0 0 1 -1) 5))
(display (lr-lo L)) (display " ") (display (lr-residue L)) (display " ") (display (lr-coeff L 0)) (newline)
(display (lr-residue-at (list 0 1) (list 2 -3 1) 1 4)) (display " ") (display (lr-residue-at (list 0 1) (list 2 -3 1) 2 4)) (newline)
(define A (lr-make -1 (list 1 1)))
(display (lr-terms (lr-mul A A))) (newline)
(display (lr-terms (lr-inverse A 5))) (newline)
(define I (lr-integrate (lr-make -2 (list 1 1 1))))
(display (cdr I)) (display " ") (display (lr-coeff (car I) -1)) (newline)
