(import "cas/axmode.lisp")
(define base (ax-assume-rule (ax-assume (ax-assume (ax-env) (quote (human socrates))) (quote (human plato))) (quote (mortal ?x)) (list (quote (human ?x)))))
(display (ax-check base (quote (mortal socrates)))) (newline)
(display (ax-check base (quote (mortal zeus)))) (newline)
(display (ax-theorem base (quote (mortal plato)))) (newline)
(define withneg (ax-assume-not base (quote (mortal zeus))))
(display (ax-check withneg (quote (mortal zeus)))) (newline)
(display (ax-check withneg (quote (mortal socrates)))) (newline)
(define anc (ax-assume-rule (ax-assume-rule (ax-assume (ax-assume (ax-env) (quote (parent abe homer))) (quote (parent homer bart))) (quote (anc ?x ?y)) (list (quote (parent ?x ?y)))) (quote (anc ?x ?z)) (list (quote (parent ?x ?y)) (quote (anc ?y ?z)))))
(display (ax-check anc (quote (anc abe bart)))) (newline)
(display (ax-check (ax-assume-not (ax-assume (ax-env) (quote (p))) (quote (p))) (quote (p)))) (newline)
