(import "cas/algherm.lisp")
(define (ppow b n) (if (= n 0) (list 1) (poly-mul b (ppow b (- n 1)))))
(define pq (rat-from-poly (list 1 0 1)))
(define pe (rat-from-poly (list 1 0 0 1)))
(display (ah-verify (rat-make (list 1) (ppow (list -2 1) 2)) pq)) (display " ")
(display (ah-verify (rat-make (list 1) (ppow (list -2 1) 3)) pq)) (newline)
(display (ah-verify (rat-make (list 1) (poly-mul (ppow (list -2 1) 2) (ppow (list 1 1) 2))) pq)) (display " ")
(display (ah-verify (rat-make (list 1) (ppow (list -2 1) 2)) pe)) (newline)
(display (rat-zero? (car (cdr (ah-reduce (rat-make (list 1) (list -2 1)) pq))))) (display " ")
(display (ah-verify (rat-from-poly (list 0 0 1)) pq)) (newline)
