(import "cas/rothstein.lisp")
(define a1 (list 1)) (define b1 (list -1 0 1))
(display (rt-resultant a1 b1)) (newline)
(display (rt-log-part a1 b1)) (newline)
(display (list (ros-squarefree? b1) (rt-verify a1 b1) (rt-complete? a1 b1))) (newline)
(define b2 (list 0 -1 0 1))
(display (rt-log-part (list 1) b2)) (newline)
(display (list (rt-verify (list 1) b2) (rt-complete? (list 1) b2))) (newline)
(define b3 (poly-mul (list -1 1) (list -2 1)))
(display (rt-log-part (list 1 3) b3)) (newline)
(display (list (rt-verify (list 1 3) b3) (rt-complete? (list 1) (list 1 0 1)))) (newline)
