(import "cas/lll.lisp")
(define B (list (list 1 2) (list 3 4)))
(define R (lll B))
(display R) (newline)
(display (lll-transform R B)) (newline)
(display (list (lll-size-reduced? R) (lll-lovasz-ok? R) (lll-same-lattice? R B) (lll-det-preserved? R B))) (newline)
(define C (list (list 1 1 1) (list -1 0 2) (list 3 5 6)))
(define RC (lll C))
(display RC) (newline)
(display (list (lll-size-reduced? RC) (lll-lovasz-ok? RC) (lll-same-lattice? RC C))) (newline)
(define S (list (list 1 0 0) (list 10 1 0) (list 100 10 1)))
(display (lll S)) (newline)
