(import "cas/cadqe3.lisp")
(define genq (list (list (cons 1 (list 0 0 1))) (list (cons 1 (list 0 1 0))) (list (cons 1 (list 1 0 0)))))
(define factors (list (list (list 1 1 0 0)) (list (list 1 0 1 0)) (list (list 1 0 0 1)) (list (list 1 0 2 0) (list -4 1 0 1))))
(define result (cadqe3-elim factors (quote exists) (cons (quote zero) genq)))
(define vecs (cdr result))
(define (cadr l) (car (cdr l))) (define (caddr l) (car (cdr (cdr l)))) (define (cadddr l) (car (cdr (cdr (cdr l)))))
(define (target sa sb sc sd) (cond ((not (= sa 0)) (>= sd 0)) (else (if (not (= sb 0)) #t (= sc 0)))))
(define (all-match vs) (cond ((null? vs) #t) ((target (car (car vs)) (cadr (car vs)) (caddr (car vs)) (cadddr (car vs))) (all-match (cdr vs))) (else #f)))
(define (present? v vs) (cond ((null? vs) #f) ((equal? v (car vs)) #t) (else (present? v (cdr vs)))))
(display (all-match vecs)) (newline)
(display (present? (list 1 1 1 1) vecs)) (newline)
(display (present? (list 0 1 1 1) vecs)) (newline)
(display (present? (list 0 0 0 0) vecs)) (newline)
; degenerate exists x. a=0,b=0 forces c=0: the point a=0,b=0,c=1 must be EXCLUDED
(display (cadqe3-holds-at (quote exists) (cons (quote zero) genq) 0 0 1)) (newline)
(display (cadqe3-holds-at (quote exists) (cons (quote zero) genq) 0 0 0)) (newline)
