(import "cas/puiseux.lisp")
(define r1 (px-superelliptic (list 0 1) 2 6))
(display (px-nth r1 1)) (display " ") (display (px-verify (list 0 1) 2 6)) (newline)
(define r3 (px-superelliptic (list 0 0 0 1) 2 8))
(display (px-nth r3 2)) (display " ") (display (px-verify (list 0 0 0 1) 2 8)) (newline)
(display (px-verify (list 0 1 1) 2 6)) (display " ") (display (px-verify (list 0 1) 3 6)) (newline)
(define r5 (px-superelliptic (list 4 1) 2 5))
(display (car (px-nth r5 3))) (display " ") (display (px-verify (list 4 1) 2 5)) (newline)
(display (car (px-superelliptic (list 2 1) 2 5))) (newline)
