(import "cas/mixedlogn.lisp")
(define g (list 1 0 0 1))
(define tp (rat-make (list 1) (list 0 1)))
(define y (sf-y 3))
(define Q (list (sf-zeros 3) y))
(define B (mln-deriv g 3 tp Q))
(display (mln-nth B 1)) (newline)
(display (mln-certify g 3 tp Q B)) (newline)
(display (mln-solve g 3 tp B 0)) (newline)
(define Qt2 (list (sf-zeros 3) (sf-zeros 3) (sf-set (sf-zeros 3) 0 (rat-make (list 1) (list 2)))))
(display (mln-solve g 3 tp (mln-deriv g 3 tp Qt2) 0)) (newline)
(define Qy2 (list (sf-zeros 3) (sf-set (sf-zeros 3) 2 (rat-one))))
(display (mln-solve g 3 tp (mln-deriv g 3 tp Qy2) 0)) (newline)
(define gx (list 0 1))
(define ys (sf-y 2))
(define Qs (list (sf-zeros 2) ys))
(display (mln-solve gx 2 tp (mln-deriv gx 2 tp Qs) 0)) (newline)
