(import "cas/cadqe2.lisp")
(define quad (list (list (cons 1 (list 0 1))) (list (cons 1 (list 1 0))) (list (cons 1 (list 0 0)))))
(define xmb (list (list (cons -1 (list 1 0))) (list (cons 1 (list 0 0)))))
(define xmc (list (list (cons -1 (list 0 1))) (list (cons 1 (list 0 0)))))
(display (cadqe2-formula (quote exists) (cons (quote zero) quad))) (newline)
(display (cadqe2-formula (quote exists) (cons (quote neg) quad))) (newline)
(display (cadqe2-formula (quote forall) (cons (quote pos) quad))) (newline)
(display (cadqe2-formula (quote forall) (cons (quote nonneg) quad))) (newline)
(display (cadqe2-formula (quote exists) (list (quote and) (cons (quote zero) xmb) (cons (quote zero) xmc)))) (newline)
