(import "cas/subresultant.lisp")
(display (subres-resultant (list -1 0 1) (list 2 1))) (newline)
(display (subres-resultant (list -1 0 1) (list 0 2))) (newline)
(display (subres-resultant (list 0 -1 0 1) (list -1 0 1))) (newline)
(display (subres-resultant (list -1 0 1) (list -1 1))) (newline)
(display (subres-gcd-degree (list -1 0 1) (list 0 2))) (newline)
(display (subres-gcd-degree (list 1 -2 1) (list -2 2))) (newline)
(display (subres-gcd-degree (list -1 3 -3 1) (list 3 -6 3))) (newline)
(display (subres-psc-tower (list -1 3 -3 1) (list 3 -6 3))) (newline)
