(import "cas/permgroup.lisp")
(define a (list 1 0 2)) (define b (list 0 2 1)) (define gens (list a b))
(display (perm-compose a b)) (newline)
(display (perm-inverse (list 1 2 0))) (newline)
(display (perm-cycles (list 1 2 0))) (newline)
(display (list (group-order gens 3) (perm-element-order (list 1 2 0)))) (newline)
(display (list (closure-has-id? gens 3) (closure-closed? gens 3) (closure-inverse-closed? gens 3))) (newline)
(display (list (pg-len (orbit 0 gens 3)) (pg-len (stabilizer 0 gens 3)) (orbit-stabilizer-ok? 0 gens 3))) (newline)
(display (list (group-order (list (list 1 0 2 3) (list 1 2 3 0)) 4)
               (group-order (list (list 1 2 0 3) (list 0 2 3 1)) 4)
               (group-order (list (list 1 2 3 0) (list 0 3 2 1)) 4))) (newline)
