(import "cas/inetbridge.lisp")
(kernel-assume (quote A) (quote (Sort 0)))
(kernel-assume (quote a) (quote A))
(display (ibr-net-class (quote (app I I)))) (newline)
(display (ibr-kernel-class (quote (app (lam (x A) x) (lam (y A) y))))) (newline)
(display (ibr-net-class (quote (app K I)))) (newline)
(display (ibr-kernel-class (quote (app (lam (x A) (lam (y A) x)) (lam (z A) z))))) (newline)
(display (ibr-net-class (quote (app I (app I I))))) (newline)
(display (kernel-equal? (quote (app (lam (x A) x) (lam (y A) y))) (quote (lam (w A) w)))) (newline)
(display (ibr-divergence-demo)) (newline)
