(import "cas/defint.lisp")
(display (dint-antideriv (list 0 0 1))) (newline)
(display (dint-certify (list 0 0 1))) (newline)
(display (dint-value (list 0 0 1) 0 1)) (newline)
(display (dint-value (list 1 2 3) 0 2)) (newline)
(display (dint-value (list 0 0 1) -1 1)) (newline)
(display (dint-value (list 1 2 3 4) 3 3)) (newline)
(display (dint-prove (list 0 0 1) 0 1)) (newline)
(display (dint-recheck (dint-prove (list 1 2 3) 0 2))) (newline)
