(import "cas/mixedexpn.lisp")
(define g (list 1 0 0 1))
(define hp (rat-from-poly (list 1)))
(define Ay (sf-y 3))
(define B (mxn-rhs g 3 hp Ay))
(display (mxn-nth B 1)) (newline)
(display (mxn-certify g 3 hp Ay B)) (newline)
(display (mxn-solve g 3 hp B 0)) (newline)
(define Ay2 (sf-set (sf-zeros 3) 2 (rat-one)))
(display (mxn-solve g 3 hp (mxn-rhs g 3 hp Ay2) 0)) (newline)
(define Amix (sf-set (sf-set (sf-set (sf-zeros 3) 0 (rat-from-poly (list 0 1))) 1 (rat-one)) 2 (rat-one)))
(display (mxn-solve g 3 hp (mxn-rhs g 3 hp Amix) 1)) (newline)
(define gx (list 0 1))
(define Ays (sf-y 2))
(display (mxn-solve gx 2 hp (mxn-rhs gx 2 hp Ays) 0)) (newline)
