(import "cas/cadgen.lisp")
(define (cn c n) (if (= n 0) c (list (cn c (- n 1)))))
(display (cadgen-decide (quote exists) (cons (quote neg) (list -1 0 1)) 1)) (display " ") (display (cadgen-decide (quote forall) (cons (quote nonneg) (list -1 0 1)) 1)) (newline)
(define disk (list (list -1 0 1) (list) (list 1)))
(display (cadgen-decide (quote exists) (cons (quote neg) disk) 2)) (display " ") (display (cadgen-decide (quote forall) (cons (quote nonneg) disk) 2)) (newline)
(display (cadgen-decide (quote exists) (list (quote and) (cons (quote pos) (list (list) (list 1))) (cons (quote pos) (list (list 0 1))) (cons (quote neg) (list (list -1 1) (list 1)))) 2)) (newline)
(define ball3 (list (list (list -1 0 1) (list) (list 1)) (cn 0 2) (cn 1 2)))
(display (cadgen-decide (quote exists) (cons (quote neg) ball3) 3)) (newline)
(define s2 (list (list -1 0 1) (list) (list 1)))
(define ball4 (list (list s2 (cn 0 2) (cn 1 2)) (cn 0 3) (cn 1 3)))
(display (cadgen-decide (quote exists) (cons (quote neg) ball4) 4)) (newline)
