(import "cas/algresnsf.lisp")
(define LOG (list 'log)) (define EXP (list 'exp (list 0 1)))
(define d1 (list (rat-from-poly (list -2)) (rat-zero) (rat-one)))
(define a1 (list (rat-zero) (rat-make (list 2) (list 0 1))))
(display (car (int-prim-rational-nsf a1 d1 LOG))) (newline)
(display (int-prim-rational-nsf-verify a1 d1 LOG)) (newline)
(define de (list (rat-from-poly (list -1)) (rat-from-poly (list 1)) (rat-one)))
(define ae (list (rat-from-poly (list 2)) (rat-from-poly (list -1))))
(display (int-prim-rational-nsf-verify ae de EXP)) (newline)
