(import "cas/elliptic3norm.lisp")
(define res1 (list (cons 1 1) (cons 2 2)))
(display (e3n-build-norm res1)) (newline)
(display (e3n-degree-from-residues res1)) (newline)
(display (e3n-verifies? res1 (e3n-logder-half (e3n-build-norm res1)))) (newline)
(define res2 (list (cons 0 1)))
(display (e3n-build-norm res2)) (newline)
(display (e3n-logder-half (e3n-build-norm res2))) (newline)
(display (e3n-verifies? res2 (e3n-logder-half (e3n-build-norm res2)))) (newline)
(display (e3n-build-norm (list (cons 1 1) (cons -1 1)))) (newline)
(display (e3n-verifies? res2 (e3n-logder-half (e3n-build-norm res1)))) (newline)
