; -*- lisp -*-
; src/cas/cadqesimp.lisp -- a step toward minimal solution-formula construction for parametric quantifier
; elimination.  The parametric eliminators report the eliminated condition as a raw disjunction of full SIGN
; VECTORS over every projection factor: correct, but verbose.  This module minimizes the set of true sign vectors
; the way Quine-McCluskey minimizes a Boolean cover, by two merge rules applied to a fixpoint.
;   Rule 1, FACTOR ELIMINATION: if three cubes agree on every factor except one, where the three take all three
;   signs, that factor is dropped there (marked star).
;   Rule 2, SIGN MERGING: if two cubes agree except at one factor taking two signs, they merge to a relation at
;   that factor: positive-or-zero becomes ge, negative-or-zero becomes le, positive-or-negative becomes ne.
; Each merge preserves the covered parameter points, so the simplified formula is equivalent to the raw disjunction.
; It is not guaranteed globally minimal, but it removes the bulk of the redundancy and yields the canonical formula
; on the standard examples, turning the nineteen-vector general-quadratic output into a three-branch formula.
;
; Public:
;   cadqs-simplify factors vecs   the minimized readable formula equivalent to the disjunction of the sign vectors
;
; A cube is a list, one entry per factor, each entry one of: 1, 0, -1, the symbol star, or a relation ge, le, ne.

(define (cadqs-app a b) (if (null? a) b (cons (car a) (cadqs-app (cdr a) b))))
(define (cadqs-len l) (if (null? l) 0 (+ 1 (cadqs-len (cdr l)))))
(define (cadqs-simplify factors vecs) (cadqs-render factors (cadqs-fixpoint (cadqs-dedup vecs))))
(define (cadqs-fixpoint cubes) (cadqs-fix cubes (cadqs-pass cubes)))
(define (cadqs-fix old new) (if (= (cadqs-len old) (cadqs-len new)) new (cadqs-fix new (cadqs-pass new))))
(define (cadqs-pass cubes) (cadqs-absorb (cadqs-dedup (cadqs-merge2 (cadqs-merge3 cubes)))))
(define (cadqs-merge3 cubes) (cadqs-m3-go cubes cubes))
(define (cadqs-m3-go cubes all) (if (null? cubes) all (cadqs-m3-go (cdr cubes) (cadqs-m3-try (car cubes) all))))
(define (cadqs-m3-try cube all) (cadqs-m3-pos cube all 0 (cadqs-len cube) all))
(define (cadqs-m3-pos cube all k n acc)
  (cond ((>= k n) acc)
        ((cadqs-is-sign? (cadqs-at cube k))
         (cadqs-m3-pos cube all (+ k 1) n (cadqs-m3-atk cube all k acc)))
        (else (cadqs-m3-pos cube all (+ k 1) n acc))))
(define (cadqs-m3-atk cube all k acc)
  (if (and (cadqs-has-variant all cube k 1) (and (cadqs-has-variant all cube k 0) (cadqs-has-variant all cube k -1)))
      (cadqs-add (cadqs-set cube k (quote star)) acc)
      acc))
(define (cadqs-has-variant all cube k s) (cadqs-hv all cube k s))
(define (cadqs-hv all cube k s) (cond ((null? all) #f) ((cadqs-match-except (car all) cube k s) #t) (else (cadqs-hv (cdr all) cube k s))))
(define (cadqs-match-except c cube k s) (and (equal? (cadqs-at c k) s) (cadqs-eq-except c cube k 0 (cadqs-len cube))))
(define (cadqs-eq-except c cube k i n)
  (cond ((>= i n) #t)
        ((= i k) (cadqs-eq-except c cube k (+ i 1) n))
        ((equal? (cadqs-at c i) (cadqs-at cube i)) (cadqs-eq-except c cube k (+ i 1) n))
        (else #f)))
(define (cadqs-merge2 cubes) (cadqs-m2-go cubes cubes))
(define (cadqs-m2-go cubes all) (if (null? cubes) all (cadqs-m2-go (cdr cubes) (cadqs-m2-try (car cubes) all))))
(define (cadqs-m2-try cube all) (cadqs-m2-pos cube all 0 (cadqs-len cube) all))
(define (cadqs-m2-pos cube all k n acc)
  (cond ((>= k n) acc)
        ((cadqs-is-sign? (cadqs-at cube k)) (cadqs-m2-pos cube all (+ k 1) n (cadqs-m2-atk cube all k acc)))
        (else (cadqs-m2-pos cube all (+ k 1) n acc))))
(define (cadqs-m2-atk cube all k acc)
  (cadqs-m2-rel cube all k acc (cadqs-at cube k)))
(define (cadqs-m2-rel cube all k acc s)
  (cond ((= s 1) (if (cadqs-has-variant all cube k 0) (cadqs-add (cadqs-set cube k (quote ge)) acc) acc))
        ((= s -1) (if (cadqs-has-variant all cube k 0) (cadqs-add (cadqs-set cube k (quote le)) acc) acc))
        (else acc)))
(define (cadqs-merge-ne cubes) (cadqs-mne-go cubes cubes))
(define (cadqs-mne-go cubes all) (if (null? cubes) all (cadqs-mne-go (cdr cubes) (cadqs-mne-try (car cubes) all))))
(define (cadqs-mne-try cube all) (cadqs-mne-pos cube all 0 (cadqs-len cube) all))
(define (cadqs-mne-pos cube all k n acc)
  (cond ((>= k n) acc)
        ((and (cadqs-is-sign? (cadqs-at cube k)) (and (= (cadqs-at cube k) 1) (cadqs-has-variant all cube k -1)))
         (cadqs-mne-pos cube all (+ k 1) n (cadqs-add (cadqs-set cube k (quote ne)) acc)))
        (else (cadqs-mne-pos cube all (+ k 1) n acc))))
(define (cadqs-absorb cubes) (cadqs-abs-go cubes cubes))
(define (cadqs-abs-go cubes all) (cadqs-keep-uncovered cubes all))
(define (cadqs-keep-uncovered cubes all)
  (cond ((null? cubes) (quote ()))
        ((cadqs-covered-by-other (car cubes) all) (cadqs-keep-uncovered (cdr cubes) all))
        (else (cons (car cubes) (cadqs-keep-uncovered (cdr cubes) all)))))
(define (cadqs-covered-by-other c all) (cadqs-cbo c all))
(define (cadqs-cbo c all)
  (cond ((null? all) #f)
        ((equal? (car all) c) (cadqs-cbo c (cdr all)))
        ((cadqs-subsumes (car all) c) #t)
        (else (cadqs-cbo c (cdr all)))))
(define (cadqs-subsumes g c) (cadqs-sub g c 0 (cadqs-len c)))
(define (cadqs-sub g c k n) (cond ((>= k n) #t) ((cadqs-implies (cadqs-at c k) (cadqs-at g k)) (cadqs-sub g c (+ k 1) n)) (else #f)))
(define (cadqs-implies cc gc)
  (cond ((equal? gc (quote star)) #t)
        ((equal? gc cc) #t)
        ((equal? gc (quote ge)) (cadqs-in cc (list 1 0)))
        ((equal? gc (quote le)) (cadqs-in cc (list -1 0)))
        ((equal? gc (quote ne)) (cadqs-in cc (list 1 -1)))
        (else #f)))
(define (cadqs-in x s) (cond ((null? s) #f) ((equal? x (car s)) #t) (else (cadqs-in x (cdr s)))))
(define (cadqs-at cube k) (cond ((null? cube) (quote star)) ((= k 0) (car cube)) (else (cadqs-at (cdr cube) (- k 1)))))
(define (cadqs-set cube k v) (if (= k 0) (cons v (cdr cube)) (cons (car cube) (cadqs-set (cdr cube) (- k 1) v))))
(define (cadqs-is-sign? x) (cadqs-in x (list 1 0 -1)))
(define (cadqs-add cube acc) (if (cadqs-member cube acc) acc (cons cube acc)))
(define (cadqs-member cube acc) (cond ((null? acc) #f) ((equal? cube (car acc)) #t) (else (cadqs-member cube (cdr acc)))))
(define (cadqs-dedup cubes) (cadqs-dd cubes (quote ())))
(define (cadqs-dd cubes acc) (cond ((null? cubes) (cadqs-rev acc)) ((cadqs-member (car cubes) acc) (cadqs-dd (cdr cubes) acc)) (else (cadqs-dd (cdr cubes) (cons (car cubes) acc)))))
(define (cadqs-rev l) (cadqs-rev-go l (quote ())))
(define (cadqs-rev-go l acc) (if (null? l) acc (cadqs-rev-go (cdr l) (cons (car l) acc))))
(define (cadqs-render factors cubes)
  (cond ((null? cubes) (quote false))
        ((cadqs-any-alltrue? cubes (cadqs-len factors)) (quote true))
        (else (cons (quote or) (cadqs-render-cubes factors cubes)))))
(define (cadqs-any-alltrue? cubes nf) (cond ((null? cubes) #f) ((cadqs-allstar? (car cubes)) #t) (else (cadqs-any-alltrue? (cdr cubes) nf))))
(define (cadqs-allstar? cube) (cond ((null? cube) #t) ((equal? (car cube) (quote star)) (cadqs-allstar? (cdr cube))) (else #f)))
(define (cadqs-render-cubes factors cubes) (if (null? cubes) (quote ()) (cons (cadqs-render-cube factors (car cubes)) (cadqs-render-cubes factors (cdr cubes)))))
(define (cadqs-render-cube factors cube) (cadqs-conj (cadqs-render-lits factors cube)))
(define (cadqs-conj lits) (cond ((null? lits) (quote true)) ((null? (cdr lits)) (car lits)) (else (cons (quote and) lits))))
(define (cadqs-render-lits factors cube)
  (cond ((null? factors) (quote ()))
        ((equal? (car cube) (quote star)) (cadqs-render-lits (cdr factors) (cdr cube)))
        (else (cons (cadqs-lit (car factors) (car cube)) (cadqs-render-lits (cdr factors) (cdr cube))))))
(define (cadqs-lit factor sgn)
  (cond ((equal? sgn 1) (list (quote >) (cadqs-show factor) 0))
        ((equal? sgn -1) (list (quote <) (cadqs-show factor) 0))
        ((equal? sgn 0) (list (quote =) (cadqs-show factor) 0))
        ((equal? sgn (quote ge)) (list (quote >=) (cadqs-show factor) 0))
        ((equal? sgn (quote le)) (list (quote <=) (cadqs-show factor) 0))
        ((equal? sgn (quote ne)) (list (quote neq) (cadqs-show factor) 0))
        (else (cadqs-show factor))))
(define (cadqs-show factor) (cons (quote poly) factor))
