; -*- lisp -*-
; src/cas/cas.lisp -- the BREADTH FACADE: a single discoverable entry point to sangaku's decision and computation
; procedures.  The system spans more than two hundred modules -- real quantifier elimination, symbolic integration
; (the Risch algorithm and its algebraic extensions), differential equations, elliptic and hyperelliptic function
; theory, Groebner bases and ideal membership, the Nullstellensatz and Positivstellensatz, sums of squares, factoring
; and root isolation, number theory, coding theory, and cryptography -- but that breadth is hard to see when each
; capability lives in its own module.  This facade gathers the headline procedures under one import and one naming
; scheme, and provides a machine-readable catalogue of what the system can decide, so the question "what can sangaku
; do?" has a single answer to read and a single place to start.
;
; The facade RE-EXPORTS verified top-level procedures (it adds no new mathematics); each cas- name is a thin alias
; for the procedure documented in its own module, where the algorithm, the certificate it emits, and the honest
; scope are described in full.  Importing this module imports those modules.
;
; Decision procedures (return a verdict, often with a checkable certificate available in the underlying module):
;   cas-decide-real n quant phi   -> real quantifier elimination: decide a quantified real sentence in n variables
;                                    (Tarski atoms rqe-gt / rqe-lt / rqe-ge / rqe-le / rqe-eq / rqe-ne; quant in
;                                    {exists forall}).  Complete on cells of every dimension for the covered cases.
;   cas-sat n phi / cas-valid n phi -> the existential / universal real decision
;   cas-refutes-over-C system     -> Nullstellensatz: is a polynomial system unsatisfiable over the complex numbers?
;   cas-nonneg? p                 -> is a univariate polynomial nonnegative on all of R? (sum-of-squares decision)
;   cas-nonneg-on? p constraints  -> Positivstellensatz: is p nonnegative on the basic closed semialgebraic set?
;
; Computation procedures:
;   cas-groebner basis            -> a Groebner basis of the ideal generated by the given multivariate polynomials
;
; Capability catalogue:
;   cas-capabilities              -> a list of (domain . one-line-summary) pairs naming the system's main areas
;   cas-domains                   -> just the domain names
;
; Each underlying module carries its own examples, golden output, and a precisely stated scope (including where a
; procedure is a complete decision procedure, where it is a sound checker, and where the frontier lies); this facade
; is the index, not a replacement for those statements.

(import "cas/rqe.lisp")
(import "cas/nullstellensatz.lisp")
(import "cas/sos.lisp")
(import "cas/positivstellensatz.lisp")
(import "cas/groebner.lisp")

; ----- decision procedures (aliases for the verified entry points) -----
(define (cas-decide-real n quant phi) (rqe-decide n quant phi))
(define (cas-sat n phi) (rqe-sat n phi))
(define (cas-valid n phi) (rqe-valid n phi))
(define (cas-refutes-over-C system) (nss-refutes? system))
(define (cas-nonneg? p) (sos-nonneg? p))
(define (cas-nonneg-on? p constraints) (psatz-valid? p constraints))

; ----- computation procedures -----
(define (cas-groebner basis) (groebner basis))

; ----- the capability catalogue -----
(define (cas-capabilities)
  (list
    (cons (quote real-quantifier-elimination) (quote "decide quantified real sentences; complete on cells of every dimension for the covered cases"))
    (cons (quote symbolic-integration) (quote "Risch algorithm with algebraic, exponential, logarithmic, and elliptic/hyperelliptic extensions"))
    (cons (quote differential-equations) (quote "linear and structured ODE solving"))
    (cons (quote algebraic-geometry) (quote "Groebner bases, ideal membership, the Nullstellensatz over C"))
    (cons (quote real-algebra) (quote "sums of squares and the Positivstellensatz for nonnegativity on semialgebraic sets"))
    (cons (quote polynomial-algebra) (quote "factoring, root isolation, resultants, real algebraic numbers"))
    (cons (quote number-theory) (quote "primality, factoring, modular arithmetic, continued fractions, Diophantine tools"))
    (cons (quote coding-theory) (quote "Reed-Solomon, BCH, Hamming, Reed-Muller, the number-theoretic transform"))
    (cons (quote cryptography) (quote "elliptic-curve arithmetic, discrete logarithms, secret sharing"))
    (cons (quote special-functions) (quote "orthogonal polynomials, partitions, elliptic and hypergeometric functions"))))
(define (cas-domains) (cas-doms (cas-capabilities)))
(define (cas-doms l) (if (null? l) (quote ()) (cons (car (car l)) (cas-doms (cdr l)))))
