; -*- lisp -*-
; lib/cas/cyclic.lisp -- binary cyclic codes generated by g(x) | x^n - 1.
;
; A cyclic code of length n is an ideal in GF(2)[x]/(x^n - 1): it is generated by a single
; polynomial g(x) that divides x^n - 1 (= x^n + 1 over GF(2)), and its codewords are exactly
; the multiples of g of degree < n.  A k = n - deg g bit message m is encoded as c = m*g, so a
; word is a codeword precisely when it is divisible by g -- the syndrome r mod g is then zero.
; The defining feature is cyclic closure: rotating a codeword's coefficients (multiplying by x
; modulo x^n - 1) yields another codeword.  Reed-Muller aside, the Hamming and BCH codes are
; all cyclic, so this is the framework beneath them; the [7,4] Hamming code is the cyclic code
; with generator x^3 + x + 1, and g = x + 1 gives the even-weight parity-check code.  Builds on
; ffactor.lisp (polynomial arithmetic over GF(2)).

(import "cas/ffactor.lisp")

; ---------- bit / list helpers ----------
(define (cyc-bxor a b) (if (= a b) 0 1))
(define (cyc-nth v i) (if (= i 0) (car v) (cyc-nth (cdr v) (- i 1))))
(define (cyc-set v i x) (if (= i 0) (cons x (cdr v)) (cons (car v) (cyc-set (cdr v) (- i 1) x))))
(define (cyc-take v k) (if (= k 0) '() (cons (car v) (cyc-take (cdr v) (- k 1)))))
(define (cyc-pad c n) (if (>= (length c) n) c (append c (zeros (- n (length c))))))

; ---------- the modulus x^n - 1 = x^n + 1 over GF(2) ----------
(define (cyc-xn-1 n) (append (list 1) (append (zeros (- n 1)) (list 1))))   ; 1 + x^n
(define (cyc-deg g) (- (length (trim g)) 1))
(define (cyc-k n g) (- n (cyc-deg g)))
(define (cyc-valid-generator? g n) (null? (trim (pmod (cyc-xn-1 n) (trim g) 2))))

; ---------- encode / syndrome / membership ----------
(define (cyc-encode m g n) (cyc-pad (pnorm (pmul (pnorm m 2) (trim g) 2) 2) n))
(define (cyc-syndrome r g) (trim (pmod (trim (pnorm r 2)) (trim g) 2)))
(define (cyc-codeword? c g) (null? (cyc-syndrome c g)))

; ---------- cyclic shift: multiply by x modulo x^n - 1 (rotate coefficients) ----------
(define (cyc-shift c n) (let ((p (cyc-pad (pnorm c 2) n))) (cons (cyc-nth p (- n 1)) (cyc-take p (- n 1)))))
(define (cyc-shift-k c n k) (if (= k 0) (cyc-pad (pnorm c 2) n) (cyc-shift-k (cyc-shift c n) n (- k 1))))

; ---------- error injection ----------
(define (cyc-corrupt c positions) (if (null? positions) c (cyc-corrupt (cyc-set c (car positions) (cyc-bxor (cyc-nth c (car positions)) 1)) (cdr positions))))

; ---------- certificates ----------
(define (cyc-generates-ok? g n) (cyc-valid-generator? g n))
(define (cyc-encode-codeword-ok? m g n) (cyc-codeword? (cyc-encode m g n) g))
; defining property: a cyclic shift of a codeword is a codeword
(define (cyc-shift-closed-ok? m g n) (cyc-codeword? (cyc-shift (cyc-encode m g n) n) g))
(define (cyc-shift-all-ok? m g n) (csa (cyc-encode m g n) g n 1 n))
(define (csa c g n k stop) (if (>= k stop) #t (and (cyc-codeword? (cyc-shift-k c n k) g) (csa c g n (+ k 1) stop))))
; error detection: corrupting a codeword makes the syndrome nonzero
(define (cyc-detects-ok? m g n positions) (not (cyc-codeword? (cyc-corrupt (cyc-encode m g n) positions) g)))

; ---------- display ----------
(define (cyc-info g n) (string-append "[" (number->string n) "," (number->string (cyc-k n g)) "] binary cyclic code"))
