; -*- lisp -*-
; lib/cas/orthopoly.lisp -- the classical orthogonal polynomials, generated by their three-term
; recurrences and CERTIFIED by the second-order ODE each family satisfies.
;
; Special functions become checkable here the same way integrals do: a closed-form object is produced and
; an exact identity is verified.  Each family P_n is built from its three-term recurrence over Q, and then
; substituted into its defining differential equation; the residual is computed as an exact polynomial and
; checked to be identically zero.
;   Chebyshev T_n :  T_0=1, T_1=x,    T_n = 2x T_{n-1} - T_{n-2}          ; (1-x^2)y'' - x y' + n^2 y = 0
;   Legendre  P_n :  P_0=1, P_1=x,    n P_n = (2n-1)x P_{n-1} - (n-1)P_{n-2} ; (1-x^2)y'' - 2x y' + n(n+1)y = 0
;   Hermite   H_n :  H_0=1, H_1=2x,   H_n = 2x H_{n-1} - 2(n-1)H_{n-2}    ; y'' - 2x y' + 2n y = 0
;   Laguerre  L_n :  L_0=1, L_1=1-x,  n L_n = (2n-1-x)L_{n-1} - (n-1)L_{n-2} ; x y'' + (1-x)y' + n y = 0
; Builds on poly.lisp only (exact rational polynomial arithmetic).

(import "cas/poly.lisp")

(define (op-x) (list 0 1))
(define (op-x2m1) (list -1 0 1))                                  ; x^2 - 1
(define (op-1mx2) (list 1 0 -1))                                  ; 1 - x^2
; ---- Chebyshev T ----
(define (cheb-T-up k n a b) (let ((c (poly-sub (poly-mul (list 0 2) b) a))) (if (= k n) c (cheb-T-up (+ k 1) n b c))))
(define (cheb-T n) (if (= n 0) (list 1) (if (= n 1) (op-x) (cheb-T-up 2 n (list 1) (op-x)))))
(define (cheb-T-residual n) (let ((y (cheb-T n)))
  (poly-add (poly-mul (op-1mx2) (poly-deriv (poly-deriv y)))
            (poly-add (poly-mul (list 0 -1) (poly-deriv y)) (poly-scale (* n n) y)))))
(define (cheb-T-certify n) (poly-zero? (cheb-T-residual n)))
; ---- Legendre P ----
(define (leg-P-up k n a b)
  (let ((c (poly-scale (/ 1 k) (poly-sub (poly-mul (list 0 (- (* 2 k) 1)) b) (poly-scale (- k 1) a)))))
    (if (= k n) c (leg-P-up (+ k 1) n b c))))
(define (leg-P n) (if (= n 0) (list 1) (if (= n 1) (op-x) (leg-P-up 2 n (list 1) (op-x)))))
(define (leg-P-residual n) (let ((y (leg-P n)))
  (poly-add (poly-mul (op-1mx2) (poly-deriv (poly-deriv y)))
            (poly-add (poly-mul (list 0 -2) (poly-deriv y)) (poly-scale (* n (+ n 1)) y)))))
(define (leg-P-certify n) (poly-zero? (leg-P-residual n)))
; ---- Hermite H (physicists') ----
(define (herm-H-up k n a b) (let ((c (poly-sub (poly-mul (list 0 2) b) (poly-scale (* 2 (- k 1)) a)))) (if (= k n) c (herm-H-up (+ k 1) n b c))))
(define (herm-H n) (if (= n 0) (list 1) (if (= n 1) (list 0 2) (herm-H-up 2 n (list 1) (list 0 2)))))
(define (herm-H-residual n) (let ((y (herm-H n)))
  (poly-add (poly-deriv (poly-deriv y)) (poly-add (poly-mul (list 0 -2) (poly-deriv y)) (poly-scale (* 2 n) y)))))
(define (herm-H-certify n) (poly-zero? (herm-H-residual n)))
; ---- Laguerre L ----
(define (lag-L-up k n a b)
  (let ((c (poly-scale (/ 1 k) (poly-sub (poly-mul (list (- (* 2 k) 1) -1) b) (poly-scale (- k 1) a)))))
    (if (= k n) c (lag-L-up (+ k 1) n b c))))
(define (lag-L n) (if (= n 0) (list 1) (if (= n 1) (list 1 -1) (lag-L-up 2 n (list 1) (list 1 -1)))))
(define (lag-L-residual n) (let ((y (lag-L n)))
  (poly-add (poly-mul (list 0 1) (poly-deriv (poly-deriv y)))
            (poly-add (poly-mul (list 1 -1) (poly-deriv y)) (poly-scale n y)))))
(define (lag-L-certify n) (poly-zero? (lag-L-residual n)))
