; -*- lisp -*-
; lib/cas/weierstrass.lisp -- the WEIERSTRASS GAP SEQUENCE and pole SEMIGROUP at a Weierstrass point of a
; hyperelliptic curve y^2 = q, an exact structural invariant of the curve beyond its genus (docs/CAS.md -- summit
; S2, the integral/pole structure at a place).
;
; At a Weierstrass point of a hyperelliptic curve of genus g, the orders of poles of functions regular elsewhere
; form a numerical semigroup, and the integers NOT in it are the "gaps".  For the hyperelliptic case the pole
; semigroup is generated by 2 and 2g+1, so:
;   - the GAP SEQUENCE is exactly the g odd numbers {1, 3, 5, ..., 2g-1};
;   - the NON-GAPS (pole numbers) are the elements of the numerical semigroup <2, 2g+1>;
;   - the number of gaps is g, which is the Weierstrass-point form of the Riemann-Roch / genus count -- an
;     INDEPENDENT confirmation of the genus from the local pole structure.
; By the Weierstrass gap theorem the largest gap (the Frobenius number of the semigroup) is 2g-1, and every
; integer beyond it is a pole number.  Everything here is exact integer arithmetic: membership in <2, 2g+1> is
; decided by a reachability computation, and the gap sequence is generated directly.  This exposes, at a place,
; the structure that the genus formulas summarize globally, and the gap count cross-checks the genus.
;
; Public (g the genus, n a nonnegative integer):
;   ws-gaps g                  -> the gap sequence {1, 3, ..., 2g-1} (the g Weierstrass gaps)
;   ws-num-gaps g              -> the number of gaps, which equals g (the genus cross-check)
;   ws-semigroup-gens g        -> the generators (2, 2g+1) of the pole semigroup
;   ws-is-pole-number? g n     -> #t iff n is a non-gap (in the semigroup <2, 2g+1>)
;   ws-is-gap? g n             -> #t iff n is a gap (a positive integer not in the semigroup)
;   ws-frobenius g             -> the largest gap 2g-1 (the Frobenius number of the semigroup)
;   ws-genus-from-gaps g       -> the genus recovered as the number of gaps (must equal g)
;
; Verified: genus 2 gives gaps {1,3}, semigroup <2,5>, with 2,4,5 pole numbers and 1,3 gaps; genus 3 gives gaps
; {1,3,5}, semigroup <2,7>; the gap count equals the genus for g = 1..5; the Frobenius number is 2g-1.
;
; Builds on poly.lisp (kept for representation consistency; the content is integer arithmetic).

(import "cas/poly.lisp")

; ----- the gap sequence {1,3,...,2g-1} -----
(define (ws-gaps g) (ws-odds 1 g))
(define (ws-odds start count) (if (<= count 0) (quote ()) (cons start (ws-odds (+ start 2) (- count 1)))))
(define (ws-num-gaps g) (ws-len (ws-gaps g)))
(define (ws-len l) (if (null? l) 0 (+ 1 (ws-len (cdr l)))))

; ----- the pole semigroup generators -----
(define (ws-semigroup-gens g) (list 2 (+ (* 2 g) 1)))

; ----- membership in the numerical semigroup <2, 2g+1> by reachability -----
(define (ws-is-pole-number? g n) (if (= n 0) #t (ws-reach n (+ (* 2 g) 1))))
; n is a pole number iff n is even, OR n >= 2g+1 and (n - (2g+1)) is even (>=0).  Equivalently n in <2,2g+1>:
; n even -> yes; n odd -> yes iff n >= 2g+1.
(define (ws-reach n gen) (if (= (remainder n 2) 0) #t (>= n gen)))

(define (ws-is-gap? g n) (if (> n 0) (if (ws-is-pole-number? g n) #f #t) #f))

; ----- Frobenius number (largest gap) -----
(define (ws-frobenius g) (- (* 2 g) 1))

; ----- genus from the gap count (cross-check) -----
(define (ws-genus-from-gaps g) (ws-num-gaps g))
