; 221-cyclic-codes.lisp -- binary cyclic codes generated by g(x) | x^n - 1.
;
; A cyclic code of length n is generated by a polynomial g dividing x^n - 1 (= x^n + 1 over
; GF(2)); its codewords are the multiples of g, so a word is a codeword exactly when g divides
; it (syndrome r mod g = 0).  The defining property is cyclic closure -- rotating a codeword's
; coefficients yields another codeword -- which is verified directly here.  The Hamming and BCH
; codes are cyclic, so this is the framework beneath them: x^3 + x + 1 generates the [7,4]
; Hamming code, and x + 1 generates the even-weight parity-check code.  `must` raises on failure.

(import "cas/cyclic.lisp")
(define (must label x)
  (display "  ") (display label) (display " : ") (display (if x "ok" "FAIL")) (newline)
  (if x #t (raise 'cyc-check-failed)))

(display "binary cyclic codes") (newline) (newline)

(display "1. the [7,4] Hamming code as a cyclic code, generator x^3 + x + 1") (newline)
(define g (list 1 1 0 1)) (define n 7)
(display "    x^7 + 1 = ") (display (cyc-xn-1 7)) (newline)
(must "the generator divides x^7 + 1"  (cyc-generates-ok? g n))
(must "k = n - deg g = 4"              (= (cyc-k n g) 4))
(define c (cyc-encode (list 1 0 0 0) g n))
(display "    encode (1 0 0 0) = ") (display c) (display ", its cyclic shift = ") (display (cyc-shift c n)) (newline)
(must "the encoded word is a codeword" (cyc-codeword? c g))
(newline)

(display "2. cyclic closure: every rotation of a codeword is a codeword") (newline)
(must "one shift stays a codeword"     (cyc-shift-closed-ok? (list 1 0 0 0) g n))
(must "all n shifts stay codewords"    (cyc-shift-all-ok? (list 1 0 1 1) g n))
(newline)

(display "3. error detection (syndrome becomes nonzero)") (newline)
(must "a single-bit error is detected" (cyc-detects-ok? (list 1 0 1 1) g n (list 2)))
(must "a double-bit error is detected" (cyc-detects-ok? (list 1 0 1 1) g n (list 1 5)))
(newline)

(display "4. g = x + 1 gives the even-weight parity-check code") (newline)
(define gp (list 1 1)) (define np 6)
(display "    ") (display (cyc-info gp np)) (newline)
(define cp (cyc-encode (list 1 0 1 1 0) gp np))
(must "x + 1 divides x^6 + 1"          (cyc-generates-ok? gp np))
(must "the parity code has dimension 5" (= (cyc-k np gp) 5))
(must "its codewords have even weight"  (= (remainder (apply + cp) 2) 0))
(must "the parity code is cyclic"       (cyc-shift-all-ok? (list 1 0 1 1 0) gp np))
(newline)

(display "all cyclic-code checks passed.") (newline)
