; The classical orthogonal polynomials (Chebyshev, Legendre, Hermite, Laguerre), generated by their
; three-term recurrences and CERTIFIED by the second-order ODE each family satisfies: the polynomial is
; substituted into its differential equation and the residual is checked to be the exact zero polynomial.
(import "cas/orthopoly.lisp")
(define (must l x) (display "  ") (display l) (display " : ") (display (if x "ok" "FAIL")) (newline) (if x #t (raise 'fail)))
(define (allc f lo hi) (allc-go f lo hi #t))
(define (allc-go f k hi acc) (if (> k hi) acc (allc-go f (+ k 1) hi (if (f k) acc #f))))
(display "Chebyshev T_5 = ") (display (cheb-T 5)) (display "  (16x^5 - 20x^3 + 5x)") (newline)
(display "Legendre  P_4 = ") (display (leg-P 4)) (display "  ((35x^4 - 30x^2 + 3)/8)") (newline)
(display "Hermite   H_5 = ") (display (herm-H 5)) (display "  (32x^5 - 160x^3 + 120x)") (newline)
(display "Laguerre  L_3 = ") (display (lag-L 3)) (display "  ((-x^3 + 9x^2 - 18x + 6)/6)") (newline) (newline)
(must "Chebyshev T_n satisfies (1-x^2)y'' - x y' + n^2 y = 0  (n=0..10)" (allc cheb-T-certify 0 10))
(must "Legendre  P_n satisfies (1-x^2)y'' - 2x y' + n(n+1) y = 0  (n=0..10)" (allc leg-P-certify 0 10))
(must "Hermite   H_n satisfies y'' - 2x y' + 2n y = 0  (n=0..10)" (allc herm-H-certify 0 10))
(must "Laguerre  L_n satisfies x y'' + (1-x) y' + n y = 0  (n=0..10)" (allc lag-L-certify 0 10))
(newline) (display "classical orthogonal polynomials certified against their defining ODEs.") (newline)
