; The WEIERSTRASS GAP SEQUENCE and pole SEMIGROUP at a Weierstrass point of a hyperelliptic curve y^2 = q -- an
; exact structural invariant beyond the genus (docs/CAS.md -- summit S2, the integral/pole structure at a place).
;
; At a Weierstrass point of a genus-g hyperelliptic curve the pole semigroup is <2, 2g+1>, so the gaps are exactly
; the g odd numbers {1, 3, ..., 2g-1}, the non-gaps are the semigroup elements, and the number of gaps is g -- the
; Weierstrass-point form of the genus count, an independent confirmation.  All exact integer arithmetic.
(import "cas/weierstrass.lisp")
(define (chk l x) (display "  ") (display l) (display " : ") (display (if x "ok" "FAIL")) (newline) (if x #t (raise (quote fail))))

(display "Weierstrass gaps and the pole semigroup of a hyperelliptic curve: local structure beyond the genus.") (newline) (newline)

(display "genus 2: the gaps are {1, 3} and the pole semigroup is generated by 2 and 5:") (newline)
(chk "the gap sequence is {1, 3}" (equal? (ws-gaps 2) (list 1 3)))
(chk "the pole semigroup generators are (2, 5)" (equal? (ws-semigroup-gens 2) (list 2 5)))
(chk "the number of gaps equals the genus, 2" (= (ws-num-gaps 2) 2))

(display "the pole numbers and gaps for genus 2:") (newline)
(chk "2 is a pole number" (ws-is-pole-number? 2 2))
(chk "4 is a pole number" (ws-is-pole-number? 2 4))
(chk "5 = 2g+1 is the first odd pole number" (ws-is-pole-number? 2 5))
(chk "1 is a gap" (ws-is-gap? 2 1))
(chk "3 is a gap (the largest one)" (ws-is-gap? 2 3))
(chk "6 is a pole number, not a gap" (if (ws-is-gap? 2 6) #f #t))
(chk "the Frobenius number (largest gap) is 2g-1 = 3" (= (ws-frobenius 2) 3))

(display "genus 3: the gaps are {1, 3, 5} and the semigroup is <2, 7>:") (newline)
(chk "the gap sequence is {1, 3, 5}" (equal? (ws-gaps 3) (list 1 3 5)))
(chk "the semigroup generators are (2, 7)" (equal? (ws-semigroup-gens 3) (list 2 7)))

(display "the gap count recovers the genus across cases -- an independent cross-check:") (newline)
(chk "genus 1 has one gap" (= (ws-genus-from-gaps 1) 1))
(chk "genus 4 has four gaps" (= (ws-genus-from-gaps 4) 4))
(chk "genus 5 has five gaps" (= (ws-genus-from-gaps 5) 5))

(newline)
(display "The Weierstrass gap sequence and pole semigroup now expose, at a place, the integral structure that the") (newline)
(display "genus formulas summarize globally, with the gap count independently confirming the genus.  The full") (newline)
(display "integral closure at every place of a general curve remains the open frontier.") (newline)
