(example "392-nullstellensatz-decision.lisp" :expect pass)
(example "393-sos-positivity.lisp" :expect pass)
(example "394-multivariate-sos-certificate.lisp" :expect pass)
(example "395-tptp-arith-bridge.lisp" :expect pass)
(example "396-constrained-positivstellensatz.lisp" :expect pass)
(example "397-univariate-real-qe.lisp" :expect pass)
(example "398-cad-projection.lisp" :expect pass)
(example "399-two-variable-cad.lisp" :expect pass)
