-- Generated by sangaku (certlean bridge). Check with: lake env lean sangaku_certificates.lean
-- Each theorem is a fact sangaku decided; the proof is re-checked by Lean's kernel, trusting nothing
-- about sangaku.  Nonnegativity facts reduce to the order axioms (sum-of-squares); existence facts to
-- the completeness axiom (the intermediate value theorem).  See docs/DOWN_TO_AXIOMS.md.
import Mathlib.Tactic
import Mathlib.Analysis.SpecialFunctions.Polynomials

-- Nonnegativity, via explicit sum-of-squares (order-axiom chain):

theorem sangaku_shifted_square (x : ℝ) : 1 + (-2) * x + (1) * x^2 ≥ 0 := by
  nlinarith [sq_nonneg (-1 + (1) * x), sq_nonneg (1)]

theorem sangaku_pos_def_quad (x : ℝ) : 1 + (1) * x + (1) * x^2 ≥ 0 := by
  nlinarith [sq_nonneg ((1 / 2 : ℝ) + (1) * x), sq_nonneg (1)]

theorem sangaku_nonmonic (x : ℝ) : 1 + (-4) * x + (5) * x^2 ≥ 0 := by
  nlinarith [sq_nonneg ((-2 / 5 : ℝ) + (1) * x), sq_nonneg (1)]

-- Existence of a real root, via the intermediate value theorem (completeness-axiom chain):

theorem sangaku_sqrt2_exists : ∃ x : ℝ, 1 ≤ x ∧ x ≤ 2 ∧ (-2 + (1) * x^2) = 0 := by
  -- Sangaku isolates the root by a sign change: f(1) < 0 < f(2).
  -- The kernel re-proves existence by the intermediate value theorem for the continuous polynomial.
  have hf : Continuous (fun x : ℝ => -2 + (1) * x^2) := by continuity
  have hlo : (fun x : ℝ => -2 + (1) * x^2) 1 ≤ 0 := by norm_num
  have hhi : (0 : ℝ) ≤ (fun x : ℝ => -2 + (1) * x^2) 2 := by norm_num
  obtain ⟨x, hx, hfx⟩ := intermediate_value_Icc (by norm_num) hf.continuousOn hlo hhi
  exact ⟨x, hx.1, hx.2, hfx⟩

theorem sangaku_cubic_root_exists : ∃ x : ℝ, 0 ≤ x ∧ x ≤ 2 ∧ (-1 + (1) * x^3) = 0 := by
  -- Sangaku isolates the root by a sign change: f(0) < 0 < f(2).
  -- The kernel re-proves existence by the intermediate value theorem for the continuous polynomial.
  have hf : Continuous (fun x : ℝ => -1 + (1) * x^3) := by continuity
  have hlo : (fun x : ℝ => -1 + (1) * x^3) 0 ≤ 0 := by norm_num
  have hhi : (0 : ℝ) ≤ (fun x : ℝ => -1 + (1) * x^3) 2 := by norm_num
  obtain ⟨x, hx, hfx⟩ := intermediate_value_Icc (by norm_num) hf.continuousOn hlo hhi
  exact ⟨x, hx.1, hx.2, hfx⟩
